### PR TITLE
Update terraform configs to use Kubernetes 1.13

### PR DESCRIPTION
**Pull request by roberthbailey**
Part of https://github.com/googleforgames/agones/issues/1044

/hold

Adding a hold until https://github.com/googleforgames/agones/pull/1167 is merged.

/assign @aLekSer

### CODE REVIEW

**Comment by roberthbailey** [comment]
```
--- FAIL: TestGameServerRestartBeforeReadyCrash (268.32s)
    gameserver_test.go:304: 
        	Error Trace:	gameserver_test.go:304
        	Error:      	Could not make GameServer Ready: %v
        	Test:       	TestGameServerRestartBeforeReadyCrash
        	Messages:   	timed out waiting for the condition
FAIL
```

This is https://github.com/googleforgames/agones/issues/1173.

**Comment by aLekSer** [comment]
PR looks good, I will verify this with E2E tests once #1167 would be merged.

**Comment by roberthbailey** [comment]
@aLekSer and I were waiting on #1167 to merge first as I was hoping to save @amitlevy21 from having to rebase.

**Comment by markmandel** [comment]
Doh! I didn't see the hold!

**Pull request merged**
