### PR TITLE
Mitigate panic when no ports allocated in E2E tests

### PR DESCRIPTION
**Pull request by aLekSer**
There could be a situation when no ports are allocated to GameServer.
Now E2E test would return fail not Panic.
Minor example comments fix.

### CODE REVIEW

**Comment by aLekSer** [comment]
Issue was found at  #1166 
```
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 96 [running]:
testing.tRunner.func1(0xc000612700)
	/usr/local/go/src/testing/testing.go:830 +0x68a
panic(0x1967760, 0x2968a20)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
agones.dev/agones/test/e2e/framework.SendGameServerUDP(0xc000a211b0, 0x1acebb5, 0x9, 0x1cd6840, 0x1905360, 0xc0009296b0, 0x0)
	/go/src/agones.dev/agones/test/e2e/framework/framework.go:305 +0x1fe
agones.dev/agones/test/e2e.TestFleetRecreateGameServers.func3(0xc000612700, 0xc0001f8000)
	/go/src/agones.dev/agones/test/e2e/fleet_test.go:935 +0x108
agones.dev/agones/test/e2e.TestFleetRecreateGameServers.func4(0xc000612700)
	/go/src/agones.dev/agones/test/e2e/fleet_test.go:968 +0x590
testing.tRunner(0xc000612700, 0xc00043e070)
```

**Comment by aLekSer** [comment]
New error in cloud build:
```
Step #22 - "sdk-conformance": Creating SDK instance
Step #22 - "sdk-conformance": {"grpcEndpoint":":59357","message":"Starting SDKServer grpc service...","severity":"info","source":"main","time":"2019-11-04T14:38:17.361288815Z"}
Step #22 - "sdk-conformance": {"httpEndpoint":":59358","message":"Starting SDKServer grpc-gateway...","severity":"info","source":"main","time":"2019-11-04T14:38:17.361619252Z"}
Step #22 - "sdk-conformance": {"error":"listen tcp :59358: bind: address already in use","message":"Could not serve http server","severity":"fatal","source":"main","time":"2019-11-04T14:38:17.361722313Z"}
Step #22 - "sdk-conformance": includes/sdk.mk:139: recipe for target 'run-sdk-conformance-no-build' failed
Step #22 - "sdk-conformance": make[2]: *** [run-sdk-conformance-no-build] Error 1
Step #22 - "sdk-conformance": make[1]: *** [run-sdk-conformance-test] Error 2
Step #22 - "sdk-conformance": includes/sdk.mk:146: recipe for target 'run-sdk-conformance-test' failed
Step #22 - "sdk-conformance": includes/sdk.mk:156: recipe for target 'run-sdk-conformance-test-rust' failed
Step #22 - "sdk-conformance": make: *** [run-sdk-conformance-test-rust] Error 2
Step #21: ok agones.dev/agones/test/e2e 219.090s
Step #21: echo "Finishing e2e test runner!"
Step #21: Finishing e2e test runner!
Step #21: completed e2e test
Step #21: Child terminated, releasing lock
Step #21: Cleanup succeeded
Step #21: successfully killed kubectl proxy
Finished Step #21
```

**Comment by aLekSer** [comment]
I was able to reproduce the original failed test - set MAX_PORT to 7010, then run only one test which is failing:
```
go_test_cmd = go test -mod=vendor $(RACE_DETECTOR_ARGS) -run  TestFleetRecreateGameServers -v 
```
`make test-e2e` run output:
```
time="2019-11-04 15:12:51.645" level=info msg="fleet simple-fleet-r992j has 10/10 ready replicas"
--- FAIL: TestFleetRecreateGameServers (0.00s)
    --- FAIL: TestFleetRecreateGameServers/gameserver_shutdown (11.45s)
        fleet_test.go:927: Could not message GameServer: Empty Ports array
    --- PASS: TestFleetRecreateGameServers/pod_deletion (28.78s)
    --- PASS: TestFleetRecreateGameServers/gameserver_unhealthy (49.10s)
FAIL
time="2019-11-04 15:12:51.840" level=info msg="Cleaning up now."
time="2019-11-04 15:12:52.784" level=info msg="Finished cleanup."
FAIL    agones.dev/agones/test/e2e      51.658s
make: *** [test-e2e] Error 1
BY-IT:build alexander$
```

**Comment by aLekSer** [comment]
Controller logs output:
```
error updating GameServer  to Scheduled state: Operation cannot be fulfilled on gameservers.agones.dev "simple-fleet-r992j-zflxh-njqw4": the object has been modified; please apply your changes to the latest version and try again"   
  stack: [
   0: "agones.dev/agones/pkg/gameservers.(*Controller).syncGameServerStartingState
	/go/src/agones.dev/agones/pkg/gameservers/controller.go:722"    
   1: "agones.dev/agones/pkg/gameservers.(*Controller).syncGameServer
	/go/src/agones.dev/agones/pkg/gameservers/controller.go:376"
```

**Comment by markmandel** [comment]
Looks like conformance flakiness - `un-sdk-conformance-test-rust` - restarting.

**Pull request merged**
