### PR TITLE
Adding AcceleratXR to companies using agones

### PR DESCRIPTION
**Pull request by acceleratxr**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, press enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking
> /kind bug
> /kind cleanup
/kind documentation
> /kind feature
> /kind hotfix

**What this PR does / Why we need it**:
Adding AcceleratXR to list of companies using Agones

**Which issue(s) this PR fixes**:

> Closes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by roberthbailey** [comment]
@acceleratxr - can you please sign the CLA?

**Comment by acceleratxr** [comment]
> @acceleratxr - can you please sign the CLA?

Hi. I did sign the CLA. Had to create a google group for it too apparently. I also added the commit email to this account as well as the google group.

**Comment by roberthbailey** [comment]
Hmm... Can you read through https://github.com/googleforgames/agones/pull/2412/checks?check_run_id=4623886592 and see if you can tell why it isn't working for you? I tried re-running the scan and it's still failing. 

It still shows your email as "Need CLA" -- can you verify that you signed it with the same email that you used in your commit?

**Comment by markmandel** [comment]
On vacation at the moment, so not in front of my work computer, so can't look at the Google tools for checking CLA status.

I do know if you are signing a corporate CLA it can take a few days (I wouldn't be surprised if it was a bit longer with the holidays).

**Comment by markmandel** [comment]
CLA is through! I'd suggest we merge this once RC is locked in, since it's only a site change.

**Comment by roberthbailey** [comment]
test failure in e2e-feature-gates:

```
--- FAIL: TestAutoscalerStressCreate (319.38s)
    framework.go:284: 
        	Error Trace:	framework.go:284
        	            				fleetautoscaler_test.go:355
        	            				fleetautoscaler_test.go:363
        	Error:      	Received unexpected error:
        	            	timed out waiting for the condition
        	Test:       	TestAutoscalerStressCreate
        	Messages:   	error waiting for fleet condition on fleet: simple-fleet-5gpv6
FAIL
time="2022-01-11 23:32:42.234" level=info msg="Namespace 1641943411 is deleted"
FAIL	agones.dev/agones/test/e2e	551.551s
FAIL
```

**Comment by roberthbailey** [comment]
Error in build-sdks:

```
Err:5 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 Packages
  File has unexpected size (231554 != 231335). Mirror sync in progress? [IP: 13.93.224.173 443]
  Hashes of expected file:
   - Filesize:231335 [weak]
   - SHA512:c212b2ff2f16b200db65047369fbc65acdaab479f1402865a6efaac0a3b1f28193e1a1e85d4ed978a4d512bade3bc1fce06b7ad0788aae6b435a65093abb458c
   - SHA256:fa7098ecc192df32e49b2f8b3ee34637ebc83542d1f6d3493d6141155361403a
   - SHA1:78088581d9ea1eb5f87e3643cac233ae8bd247d5 [weak]
   - MD5Sum:bfe4877ca4779734ee4388192a90f8b3 [weak]
  Release file created at: Sun, 09 Jan 2022 07:23:21 +0000
Fetched 4002 B in 1s (3414 B/s)
Reading package lists...
E: Failed to fetch https://packages.microsoft.com/ubuntu/18.04/prod/dists/bionic/main/binary-amd64/Packages.bz2  File has unexpected size (231554 != 231335). Mirror sync in progress? [IP: 13.93.224.173 443]
   Hashes of expected file:
    - Filesize:231335 [weak]
    - SHA512:c212b2ff2f16b200db65047369fbc65acdaab479f1402865a6efaac0a3b1f28193e1a1e85d4ed978a4d512bade3bc1fce06b7ad0788aae6b435a65093abb458c
    - SHA256:fa7098ecc192df32e49b2f8b3ee34637ebc83542d1f6d3493d6141155361403a
    - SHA1:78088581d9ea1eb5f87e3643cac233ae8bd247d5 [weak]
    - MD5Sum:bfe4877ca4779734ee4388192a90f8b3 [weak]
   Release file created at: Sun, 09 Jan 2022 07:23:21 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
make[4]: Leaving directory '/workspace/build'
The command '/bin/sh -c apt-get update     && apt-get install -y dotnet-sdk-2.2' returned a non-zero code: 100
make[4]: *** [includes/sdk.mk:106: build-build-sdk-image] Error 100
make[3]: *** [includes/build-image.mk:54: ensure-image] Error 2
make[2]: *** [includes/sdk.mk:123: ensure-build-sdk-image] Error 2
```

**Comment by roberthbailey** [comment]
Continued flakiness in e2e-feature-gates:

```
--- FAIL: TestAutoscalerBasicFunctions (322.58s)
    framework.go:284: 
        	Error Trace:	framework.go:284
        	            				fleetautoscaler_test.go:89
        	Error:      	Received unexpected error:
        	            	timed out waiting for the condition
        	Test:       	TestAutoscalerBasicFunctions
        	Messages:   	error waiting for fleet condition on fleet: simple-fleet-clc5f
```

Since we are holding off on the fix for the flaky tests until after the release, I'll retry and see if we can get this merged prior to the flaky test fix.

**Comment by markmandel** [comment]
Updating branch, so we can see what it looks like 😄

**Review by markmandel — APPROVED** [review]
Looks good!

**Comment by markmandel** [comment]
That's a new one (e2e-feature-gates):

```
agones.dev/agones/test/e2e.TestCreateFullFleetAndCantGameServerAllocate.func1(0x0)
	/go/src/agones.dev/agones/test/e2e/gameserverallocation_test.go:336 +0x65
```

**Pull request merged**
