### PR TITLE
ci: enable dependabot

### PR DESCRIPTION
**Pull request by aimuz**
Signed-off-by: aimuz <mr.imuz@gmail.com>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, press enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking
> /kind bug
> /kind cleanup
> /kind documentation
> /kind feature
> /kind hotfix
> /kind release

**What this PR does / Why we need it**:

**Which issue(s) this PR fixes**:

Ref: https://github.com/googleforgames/agones/issues/2842

**Special notes for your reviewer**:

Checking for updates with dependabot

https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates

### CODE REVIEW

**Comment by aimuz** [comment]
Needs to be activated by the repository administrator at this link https://github.com/googleforgames/agones/settings/security_analysis

**Comment by markmandel** [comment]
We've had depdendabot installed and running for a while now - not sure if this gives us anything extra? (or actually makes security scanning less often than the default?)

**Comment by aimuz** [comment]
I'd like him to be able to upgrade dependencies automatically, thus avoiding the need to manually upgrade dependencies in most cases

**Comment by roberthbailey** [comment]
> I'd like him to be able to upgrade dependencies automatically, thus avoiding the need to manually upgrade dependencies in most cases

In the past when I've asked dependabot to create a patch it has often been unsuccessful in doing so. 

Also, many of the security issues it finds are in the other language SDKs (e.g. nodejs) so we would need rules for the various directories in https://github.com/googleforgames/agones/tree/main/sdks to make this fully automated. 

We don't get alerts very often, so I'm wondering how much this will help our current patching process.

**Comment by aimuz** [comment]
> Also, many of the security issues it finds are in the other language SDKs (e.g. nodejs) so we would need rules for the various directories in https://github.com/googleforgames/agones/tree/main/sdks to make this fully automated.

Currently only gomod and github action are configured, which should not affect sdk.

For sdk, it does require additional rules to work better

**Comment by markmandel** [comment]
Just coming back to this...

> I'd like him to be able to upgrade dependencies automatically, thus avoiding the need to manually upgrade dependencies in most cases

Given we don't actually want automatic updates, does this give us anything above what GitHub provides us by default?

**Comment by aimuz** [comment]
Rather than providing automatic updates for all dependencies by default, this configuration will only turn on a few of the included ones.

If there is no need for auto-updates, then this one I think will turn that off 😀

**Pull request closed without merging**
