### PR TITLE
Fix "kubectl explain" output for Agones CRDs

### LINKED ISSUE #1194: Fix "kubectl explain" output for Agones CRDs
**Is your feature request related to a problem? Please describe.**
Currently there is no option to see the description of fields using standard `kubectl` functionality:
```
kubectl explain gameservers.agones.dev
error: Couldn't find resource for "agones.dev/v1, Kind=GameServer"
```

**Describe the solution you'd like**
Output should be similar to this:
```
kubectl explain pods

KIND:     Pod
VERSION:  v1

DESCRIPTION:
     Pod is a collection of containers that can run on a host. This resource is
     created by clients and scheduled onto hosts.
```
It seems that we could update `apiserver.go` code to serve requests of this kind.
**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by jiwonaid**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, press enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking
> /kind bug
> /kind cleanup
> /kind documentation

/kind feature

> /kind hotfix

**What this PR does / Why we need it**:

To support "kubectl explain" command for Agones CRDs, some yaml values are added.

```bash
(kubernetes-admin-dev@dev) ☁  ~  kubectl explain pod
KIND:     Pod
VERSION:  v1

DESCRIPTION:
     Pod is a collection of containers that can run on a host. This resource is
     created by clients and scheduled onto hosts.
```

This is the result for the Fleet after applying this PR.

```bash
(kubernetes-admin-dev@dev) ☁  ~  kubectl version --short
Client Version: v1.22.3
Server Version: v1.19.6

(kubernetes-admin-dev@dev) ☁  ~  kubectl explain fleet
KIND:     Fleet
VERSION:  agones.dev/v1

DESCRIPTION:
     Fleet is the data structure for a Fleet resource

FIELDS:
   apiVersion	<string>
     APIVersion defines the versioned schema of this representation of an
     object. Servers should convert recognized schemas to the latest internal
     value, and may reject unrecognized values. More info:
     https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources

   kind	<string>
     Kind is a string value representing the REST resource this object
     represents. Servers may infer this from the endpoint the client submits
     requests to. Cannot be updated. In CamelCase. More info:
     https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds

   metadata	<Object>
     Standard object's metadata. More info:
     https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata

   spec	<Object>
     FleetSpec is the spec for a Fleet. More info:
     https://agones.dev/site/docs/reference/agones_crd_api_reference/#agones.dev/v1.Fleet

   status	<Object>
     FleetStatus is the status of a Fleet. More info:
     https://agones.dev/site/docs/reference/agones_crd_api_reference/#agones.dev/v1.Fleet
```

**Which issue(s) this PR fixes**:

Closes #1194

**Special notes for your reviewer**:

Hello.
For your information, I turned off my editor's auto-formatting features for the 'install/yaml/install.yaml', because I was not sure about that.

### CODE REVIEW

**Comment by roberthbailey** [comment]
Thanks for your contribution!

The automated tests failed because `install.yaml` is a generated file and sometimes when you try to hand-edit it you don't exactly match what gets generated (in your case it looks like whitespace differences):

```
diff /tmp/agones-install/install.yaml.sorted /tmp/agones-install/install.current.yaml.sorted
11751c11751
<                               type: string 
---
>                               type: string
11981c11981
<                              type: string 
---
>                              type: string
12452a12453
>                         https://agones.dev/site/docs/reference/agones_crd_api_reference/#agones.dev/v1.GameServer'
12520a12522
>                        https://agones.dev/site/docs/reference/agones_crd_api_reference/#agones.dev/v1.GameServer'
12586a12589
>                       description: 'GameServerSpec is the spec for a GameServer resource. More info:
12634a12638
>                      description: 'GameServerSpec is the spec for a GameServer resource. More info:
12688c12692
<                      type: string 
---
>                      type: string
12744a12749
>                   description: 'GameServer is the data structure for a GameServer resource.'
12810a12816
>                  description: 'GameServer is the data structure for a GameServer resource.'
```

Rather than editing it by hand, if you edit the helm files and then run [`make gen-install`](https://github.com/googleforgames/agones/tree/main/build#make-gen-install) that should clear up the test failures.

**Comment by jiwonaid** [comment]
Thanks for your code review!

The generated install.yaml file was pushed and the build is just succeeded.

Thank you.

**Comment by markmandel** [comment]
Oh that's neat!

**Review by markmandel — APPROVED** [review]
Just took this for a spin - looks good to me!

**Review by roberthbailey — APPROVED** [review]

**Pull request merged**
