### PR TITLE
Add optional playerName to playerId object

### PR DESCRIPTION
**Pull request by theminecoder**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking
> /kind bug
> /kind cleanup
> /kind documentation

/kind feature

> /kind hotfix

**What this PR does / Why we need it**:
Adding a player name to the playerId object allows for a nice place to store something that's a little bit more readable then a straight id for when you inevitably need to print out the structure of the server object.

Allows me as a developer to go "this is player x" rather then having to do a user lookup in a player database to check the id if I'm trying to debug an issue.

**Which issue(s) this PR fixes**:
None - just thought this would be a good idea to add in while the system was being made.

**Special notes for your reviewer**:
Gonna be honest, I'm very new to go & the whole makefile system that this project has going on (I'm a java dev by trade - wouldn't be against making a java sdk lib for this at some point ;)) so I had not much idea on how to update the generated protobuf sdk files for the different sdks stored in here, which is why they aren't part of the commit. Happy to do so but just need a little bit of guidance on the right commands to use to make it happen.

### CODE REVIEW

**Comment by markmandel** [comment]
Thanks for sending through through! :+1: 

I think this PR would be better served as a design ticket - outlining goals, and also the consequences therein -- because there are quite a few. To be honest, I'm hesitant to have this be added, as it feels like a slippery slope to "hey, can we also add X, Y and Z to player data", which is likely to overload etcd. Storing player meta information seems outside the scope of Agones -- but if you feel very strongly, happy to discuss this fully in a design ticket.

Please see our [contributing guidelines](https://github.com/googleforgames/agones/blob/master/CONTRIBUTING.md#submitting-code-via-pull-requests) for details on design tickets and contributing process.

**Comment by markmandel** [comment]
Gentle bump on this, see if you wanted to do a design ticket, or you think this can be closed?

**Comment by theminecoder** [comment]
Sorry its been a busy life at work this week :P Will close and make a design ticket when I have a bit more time :)

**Comment by markmandel** [comment]
> Sorry its been a busy life at work this week :P Will close and make a design ticket when I have a bit more time :)

No worries at all - just wanted to touch base, didn't want you to think I had forgotten about you :smile:

**Pull request closed without merging**
