### PR TITLE
GH Action: Size label for PRs

### PR DESCRIPTION
**Pull request by markmandel**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, press enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking
> /kind bug

/kind cleanup

> /kind documentation
> /kind feature
> /kind hotfix
> /kind release

**What this PR does / Why we need it**:

With the removal of Prow, this provides the size labeling functionality in its stead.

Enjoy!

**Which issue(s) this PR fixes**:

N/A

**Special notes for your reviewer**:

N/A

### CODE REVIEW

**Review by roberthbailey — APPROVED** [review]

**Comment by markmandel** [comment]
Flake - gke-autopilot-1.27

```
E: I1206 00:43:43.683121     305 request.go:696] Waited for 1.487870124s due to client-side throttling, not priority and fairness, request: POST:https://104.196.96.111/apis/allocation.agones.dev/v1/namespaces/1701823302/gameserverallocations
VERBOSE: time="2023-12-06 00:43:50.201" level=info msg="Finished Allocation."
VERBOSE:     gameserverallocation_test.go:1417: 
VERBOSE:         	Error Trace:	/go/src/agones.dev/agones/test/e2e/gameserverallocation_test.go:1417
VERBOSE:         	Error:      	Not equal: 
VERBOSE:         	            	expected: 100
VERBOSE:         	            	actual  : 97
VERBOSE:         	Test:       	TestGameServerAllocationDuringMultipleAllocationClients
VERBOSE: --- FAIL: TestGameServerAllocationDuringMultipleAllocationClients (127.11s)
```

**Comment by markmandel** [comment]
Flake:

```
#8 exporting to image
#8 pushing layers 0.6s done
#8 pushing manifest for us-docker.pkg.dev/agones-images/ci/agones-sdk:1.37.0-dev-768c79e-windows_amd64-ltsc2022@sha256:5e188a3f50d275f45a13690c865e762575eb0d4064b093f70bfa7cc0a61fee13
#8 pushing manifest for us-docker.pkg.dev/agones-images/ci/agones-sdk:1.37.0-dev-768c79e-windows_amd64-ltsc2022@sha256:5e188a3f50d275f45a13690c865e762575eb0d4064b093f70bfa7cc0a61fee13 0.2s done
#8 DONE 12.8s
# Ensure that the sidecar manifest is removed before creating a new one.
DOCKER_CLI_EXPERIMENTAL=enabled docker manifest rm us-docker.pkg.dev/agones-images/ci/agones-sdk:1.37.0-dev-768c79e
No such manifest: us-docker.pkg.dev/agones-images/ci/agones-sdk:1.37.0-dev-768c79e
make: [Makefile:712: push-agones-sdk-image] Error 1 (ignored)
DOCKER_CLI_EXPERIMENTAL=enabled docker manifest create us-docker.pkg.dev/agones-images/ci/agones-sdk:1.37.0-dev-768c79e us-docker.pkg.dev/agones-images/ci/agones-sdk:1.37.0-dev-768c79e-linux-amd64  us-docker.pkg.dev/agones-images/ci/agones-sdk:1.37.0-dev-768c79e-windows_amd64-ltsc2019  us-docker.pkg.dev/agones-images/ci/agones-sdk:1.37.0-dev-768c79e-windows_amd64-ltsc2022 us-docker.pkg.dev/agones-images/ci/agones-sdk:1.37.0-dev-768c79e-linux-arm64
no such manifest: us-docker.pkg.dev/agones-images/ci/agones-allocator:1.37.0-dev-768c79e-amd64
no such manifest: us-docker.pkg.dev/agones-images/ci/agones-sdk:1.37.0-dev-768c79e-linux-amd64
make: *** [Makefile:683: push-allocator-image] Error 1
make: *** Waiting for unfinished jobs....
make: *** [Makefile:713: push-agones-sdk-image] Error 1
```

I am wondering if #3520 caused this.

**Comment by markmandel** [comment]
Another flake in unit tests

```
{"message":"k8s.io/client-go/informers/factory.go:150: Failed to watch *v1.Node: unhandled watch: testing.WatchActionImpl{ActionImpl:testing.ActionImpl{Namespace:\"\", Verb:\"watch\", Resource:schema.GroupVersionResource{Group:\"\", Version:\"v1\", Resource:\"nodes\"}, Subresource:\"\"}, WatchRestrictions:testing.WatchRestrictions{Labels:labels.internalSelector(nil), Fields:fields.andTerm{}, ResourceVersion:\"\"}}","severity":"error","time":"2023-12-06T17:39:54.744543976Z"}
{"message":"agones.dev/agones/pkg/client/informers/externalversions/factory.go:134: Failed to watch *v1.GameServer: unhandled watch: testing.WatchActionImpl{ActionImpl:testing.ActionImpl{Namespace:\"\", Verb:\"watch\", Resource:schema.GroupVersionResource{Group:\"agones.dev\", Version:\"v1\", Resource:\"gameservers\"}, Subresource:\"\"}, WatchRestrictions:testing.WatchRestrictions{Labels:labels.internalSelector(nil), Fields:fields.andTerm{}, ResourceVersion:\"\"}}","severity":"error","time":"2023-12-06T17:39:54.745323573Z"}
{"message":"adding gsSet","severity":"info","time":"2023-12-06T17:39:54.798695383Z"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x25776e2]

goroutine 695 [running]:
agones.dev/agones/pkg/gameserversets.(*AllocationOverflowController).Run(0x0, {0x2dff5c8, 0xc00043ccf0})
	/go/src/agones.dev/agones/pkg/gameserversets/allocation_overflow.go:98 +0x42
agones.dev/agones/pkg/gameserversets.(*Controller).Run.func1()
	/go/src/agones.dev/agones/pkg/gameserversets/controller.go:194 +0x85
created by agones.dev/agones/pkg/gameserversets.(*Controller).Run
	/go/src/agones.dev/agones/pkg/gameserversets/controller.go:193 +0x33b
FAIL	agones.dev/agones/pkg/gameserversets	0.432s
ok  	agones.dev/agones/pkg/metrics	12.036s
```

Going to take a look at this, as panics are bad.

**Comment by markmandel** [comment]
This again, something is up in this test:

generic-1.26

```
VERBOSE: time="2023-12-06 18:48:36.731" level=info msg="Scaling fleet" fleet=preferred-kjjlw patch="[{ \"op\": \"replace\", \"path\": \"/spec/replicas\", \"value\": 130 }]" scale=130
VERBOSE: time="2023-12-06 18:48:36.928" level=info msg="Starting Allocation."
VERBOSE: I1206 18:48:39.131242    9257 request.go:696] Waited for 1.06591953s due to client-side throttling, not priority and fairness, request: POST:https://34.81.206.236/apis/allocation.agones.dev/v1/namespaces/1701888449/gameserverallocations
VERBOSE: time="2023-12-06 18:48:39.929" level=info msg="Scaling fleet" fleet=preferred-kjjlw patch="[{ \"op\": \"replace\", \"path\": \"/spec/replicas\", \"value\": 120 }]" scale=120
VERBOSE:     gameserverallocation_test.go:1397: could not completed gsa1 allocation : an error on the server ("error updating allocated gameserver: Operation cannot be fulfilled on gameservers.agones.dev \"preferred-kjjlw-2gdxz-dlv2z\": the object has been modified; please apply your changes to the latest version and try again") has prevented the request from succeeding (post gameserverallocations.allocation.agones.dev)
VERBOSE: I1206 18:48:49.132164    9257 request.go:696] Waited for 1.512599021s due to client-side throttling, not priority and fairness, request: POST:https://34.81.206.236/apis/allocation.agones.dev/v1/namespaces/1701888449/gameserverallocations
VERBOSE: time="2023-12-06 18:48:55.128" level=info msg="Finished Allocation."
VERBOSE:     gameserverallocation_test.go:1417: 
VERBOSE:         	Error Trace:	/go/src/agones.dev/agones/test/e2e/gameserverallocation_test.go:1417
VERBOSE:         	Error:      	Not equal: 
VERBOSE:         	            	expected: 100
VERBOSE:         	            	actual  : 99
VERBOSE:         	Test:       	TestGameServerAllocationDuringMultipleAllocationClients
VERBOSE: --- FAIL: TestGameServerAllocationDuringMultipleAllocationClients (85.33s)
```

**Pull request merged**
