### PR TITLE
fleet-autoscaler-validationfix

### LINKED ISSUE #1954: Fleet Autoscaler - Fleet name CRD Validation issue
**What happened**:

A fleet named `game-1.0.0.0` can be created, but the fleet auto scaler cannot reference the fleet name `game-1.0.0.0` because a validation error at the CRD level.

**What you expected to happen**:

Preferably, the auto scaler should be able to able to reference the fleet.

**How to reproduce it (as minimally and precisely as possible)**:

Create a fleet named `game-1.0.0.0` then attempt to create a simple auto scaler for that fleet.

**Anything else we need to know?**:

Section found by Daniel: https://github.com/googleforgames/agones/blob/master/install/helm/agones/templates/crds/fleetautoscaler.yaml#L54

**Environment**:
- Agones version: v1.11.0
- Kubernetes version (use `kubectl version`): 1.18
- Cloud provider or hardware configuration: Azure AKS
- Install method (yaml/helm): helm
- Troubleshooting guide log(s):

```
Error: failed to create resource: FleetAutoscaler.autoscaling.agones.dev "fleet-scaler" is invalid: spec.fleetName: Invalid value: "": spec.fleetName in body should match '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'
```

```
apiVersion: "autoscaling.agones.dev/v1"
kind: FleetAutoscaler
metadata:
  name: fleet-scaler
spec:
  fleetName: fleet-1.0.0.0
  policy:
    type: Buffer
    buffer:
      bufferSize: 2
      minReplicas: 1
      maxReplicas: 20
```

### PR DESCRIPTION
**Pull request by SaitejaTamma**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, press enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking
>
/kind bug

> /kind cleanup
> /kind documentation
> /kind feature
> /kind hotfix

**What this PR does / Why we need it**:

**Which issue(s) this PR fixes**:

Closes #1954 

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by markmandel** [comment]
Didn't you write an e2e test to check this? I thought I saw you running it?

**Comment by SaitejaTamma** [comment]
> Didn't you write an e2e test to check this? I thought I saw you running it?

I tried to run the e2e for this function TestFleetAutoscalerTLSWebhook it is executing with out any issues, what i observe is that default fleet name is satisfying the new regular expression "^[a-z0-9]([-\\.a-z0-9]*[a-z0-9])?$" .

 I have created a fleet name with unsatisfying expression as per the Reg expression, executed the same test case and it failed which is expected behavior .

**Comment by markmandel** [comment]
For this PR, can you please write/edit a e2e test that test that the new Fleet naming behavior is passing as expected (do we have a validation test already? If not, we should probably add one)

**Comment by SaitejaTamma** [comment]
> For this PR, can you please write/edit a e2e test that test that the new Fleet naming behavior is passing as expected (do we have a validation test already? If not, we should probably add one)

Sure Mark will update with e2e

**Review by markmandel — APPROVED** [review]

**Pull request merged**
