### PR TITLE
Use containerd runtime based Windows image

### LINKED ISSUE #2582: Upgrade windows node image on GKE
**Is your feature request related to a problem? Please describe.**
With Kubernetes 1.24, GKE will no longer be supporting node images with the dockershim runtime, which includes `windows_ltsc` (the image currently used in our windows instructions). 

**Describe the solution you'd like**
We should switch to a node image with the containerd runtime, such as `windows_ltsc_containerd` or `windows_sac_containerd `.

**Describe alternatives you've considered**
We could instead drop our support for windows. 

**Additional context**
I'm not sure if we need to change anything in our build scripts / instructions to support the updated node image.

### PR DESCRIPTION
**Pull request by gongmax**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, press enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking
/kind bug
> /kind cleanup
> /kind documentation
> /kind feature
> /kind hotfix

**What this PR does / Why we need it**:
With Kubernetes 1.24, GKE no longer supports node images with the dockershim runtime, which includes `windows_ltsc`

**Which issue(s) this PR fixes**:

Closes #2582

**Special notes for your reviewer**:
Tested by run `make gcloud-test-cluster` with `GCP_CLUSTER_NODEPOOL_WINDOWSINITIALNODECOUNT` greater than 0 to create the Windows node pool

### CODE REVIEW

**Comment by markmandel** [comment]
I'm assuming we're just manually testing Agones with this containerd nodes for now? If so, I assume everything worked?

**Comment by gongmax** [comment]
> I'm assuming we're just manually testing Agones with this containerd nodes for now? If so, I assume everything worked?

I only tested the windows node pool can be created with this image. Do you want me to test by running windows GameServers on these nodes? I don't think we have any e2e test covering windows GameServer.

**Comment by markmandel** [comment]
So I think there are two things to test:

1) Does the Agones sidecar images work on these nodes
2) Can you take an example, such as the Xonotic windows example, and see if that still works?

**Comment by markmandel** [comment]
Just to be extra clear - happy to approve this once we've done manual tests that work (or realise that everything is broken, and have a work stream to fix it).

**Comment by markmandel** [comment]
Just checking in, see if we have done any manual tests on this?

**Comment by gongmax** [comment]
Hey Mark, sorry for the delay! I did some manual tests but the game server failed the health check. But the same issue also happens for the older Agones version (1.25) which support the k8s version that still allows docker based windows image. I didn't get chance to look deeper into the health check failure yet.

**Comment by gongmax** [comment]
I can hold on this PR and put some effort to figure out why the example game server fails health check. Or we can merge this PR first to fix the not-working windows node pool template. Either way, I believe the example game server health check failure is a separate issue which already exists for a while.

**Comment by markmandel** [comment]
No worries on delay, just checking in!

Fun question - did the Agones sidecar fail to run? (I'm assuming not, because the health check failed?) if the sidecar ran, then I think we are good to merge this 👍🏻

**Comment by gongmax** [comment]
The container `agones-gameserver-sidecar` can actually start without any issue.

**Comment by markmandel** [comment]
Then unless anyone has objections, I concur with your earlier statement. Let's merge this, and return to the unhealthy game server issue at a later date 👍🏻  Sound good?

**Comment by gongmax** [comment]
SGTM

**Review by markmandel — APPROVED** [review]

**Comment by markmandel** [comment]
@gongmax can you please file an issue with the example windows game server failing? Since you have the most information 😄

**Comment by gongmax** [comment]
Sure, will do!

**Pull request merged**
