### PR TITLE
Use the scheduling.k8s.io/v1 API since the beta API will no longer be served by default starting with Kubernetes 1.16

### PR DESCRIPTION
**Pull request by roberthbailey**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking
> /kind bug

 /kind cleanup

> /kind documentation
> /kind feature
> /kind hotfix

**What this PR does / Why we need it**:

**Which issue(s) this PR fixes**:

Part of https://github.com/googleforgames/agones/issues/1649

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by aLekSer** [comment]
@roberthbailey could you please run `make gen-install-yaml` and add resulted HTML file to this PR.
`make test-gen-install-yaml` would succeed.
This should described in `build/README.md` I think.

**Comment by aLekSer** [comment]
Note, I have updated previous comment with a correct command `make gen-api-docs`.

**Comment by markmandel** [comment]
How you doing with this @roberthbailey - do you need someone to take it over? :smile:

**Comment by roberthbailey** [comment]
I need to get my development environment back up and running with the new computer. So it's taking a while to run a simple docker command....

**Comment by roberthbailey** [comment]
`make gen-api-docs` didn't create any new modified files. It looks like the test that failed was `test-install-yaml` so I ran `make gen-install` which I think will fix the broken tests.

**Comment by markmandel** [comment]
Yay! v1 APIS!

**Pull request merged**
