### PR TITLE
Update the images for all examples to use the 1.1 SDKs

### PR DESCRIPTION
**Pull request by roberthbailey**
I've already compiled and pushed the new image versions to gcr.io/agones-images. 

Fixes https://github.com/googleforgames/agones/issues/1126.

### CODE REVIEW

**Comment by roberthbailey** [comment]
I added a second commit to fix the vulnerabilities in the go example images (xref https://github.com/googleforgames/agones/issues/1154).

**Comment by roberthbailey** [comment]
We should re-point them... I can add it to this PR.

**Comment by roberthbailey** [comment]
I added 3 more commits to update website docs, tests, & example yamls.

**Comment by markmandel** [comment]
Weird flakiness showing up.

```
docker: Error response from daemon: error creating overlay mount to /var/lib/docker/overlay2/d88116843d87c3f152b7b24249f745787a83fae66d618434933a7bc9396b8c96-init/merged: device or resource busy.
```

**Comment by aLekSer** [comment]
@markmandel  Regarding that error 
```
docker: Error response from daemon: error creating overlay mount to /var/lib/docker/overlay2/d88116843d87c3f152b7b24249f745787a83fae66d618434933a7bc9396b8c96-init/merged: device or resource busy.
```
So this is a Cloud Build Docker version issue.
> This should be fixed in the 2019-09 monthly update (19.03.3, 18.09.10), due next week.

https://github.com/docker/for-linux/issues/711

**Pull request merged**
