### PR TITLE
Update AKS terraform install template

### PR DESCRIPTION
**Pull request by WeetA34**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, press enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking

/kind bug

> /kind cleanup
> /kind documentation
> /kind feature
> /kind hotfix

**What this PR does / Why we need it**:

* Add missing required features block in provider azurerm definition:
During previous PR cleanup, the azurerm block has been removed but it's mandatory to define features
* Replace interpolation-only expressions in outputs
* Define static network_security_group_name in network_security_group_rule
After finding in aks-engine sources how the dynamic part of node pool network security group names isdefined (based on hash of cluster dns_prefix), we can use a static group name to avoid random issue with azurerm_resources datasource which randomly returns an empty array
* Ignore resource_group_name changes (random case Azure issue) in network security group rule:
Azure randomly returns lowercased resource_group_name in network_security_group_rule resource. So, terraform plan/apply may want to re-create the network security group rule. To avoid that, an ignore_changes lifecycle block has been added.

**Which issue(s) this PR fixes**:

N/A

**Special notes for your reviewer**:

N/A

### CODE REVIEW

**Comment by WeetA34** [comment]
@dzmitry-lahoda 
It seems that provider 2.63.0 doesn't have issue when getting existing Network Security Groups.
resource_group_name still saved in lowercase in azurerm_security_group_rule resource

**Comment by WeetA34** [comment]
No issue with terraform 0.12.31 and Azurerm 2.63.0 (set in PR) from scratch (tested twice)
```
$ terraform apply

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create
 <= read (data resources)

Terraform will perform the following actions:
...
Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.aks_cluster.azurerm_resource_group.agones_rg: Creating...
module.aks_cluster.azurerm_resource_group.agones_rg: Creation complete after 3s [id=/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/agonesRG]
module.aks_cluster.azurerm_kubernetes_cluster.agones: Creating...
module.aks_cluster.azurerm_kubernetes_cluster.agones: Still creating... [10s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster.agones: Still creating... [20s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster.agones: Still creating... [30s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster.agones: Still creating... [40s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster.agones: Still creating... [50s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster.agones: Still creating... [1m0s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster.agones: Still creating... [1m10s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster.agones: Still creating... [1m20s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster.agones: Still creating... [1m30s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster.agones: Still creating... [1m40s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster.agones: Still creating... [1m50s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster.agones: Still creating... [2m0s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster.agones: Still creating... [2m10s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster.agones: Still creating... [2m20s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster.agones: Still creating... [2m30s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster.agones: Still creating... [2m40s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster.agones: Still creating... [2m50s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster.agones: Still creating... [3m0s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster.agones: Still creating... [3m10s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster.agones: Still creating... [3m20s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster.agones: Still creating... [3m30s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster.agones: Still creating... [3m40s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster.agones: Still creating... [3m50s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster.agones: Still creating... [4m0s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster.agones: Still creating... [4m10s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster.agones: Still creating... [4m20s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster.agones: Still creating... [4m30s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster.agones: Creation complete after 4m36s [id=/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourcegroups/agonesRG/providers/Microsoft.ContainerService/managedClusters/test-cluster]
module.aks_cluster.data.azurerm_resources.network_security_groups: Refreshing state...
module.aks_cluster.azurerm_kubernetes_cluster_node_pool.metrics: Creating...
module.aks_cluster.azurerm_kubernetes_cluster_node_pool.system: Creating...
module.aks_cluster.azurerm_network_security_rule.gameserver: Creating...
module.aks_cluster.azurerm_kubernetes_cluster_node_pool.metrics: Still creating... [10s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster_node_pool.system: Still creating... [10s elapsed]
module.aks_cluster.azurerm_network_security_rule.gameserver: Still creating... [10s elapsed]
module.aks_cluster.azurerm_network_security_rule.gameserver: Creation complete after 14s [id=/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/MC_agonesRG_test-cluster_eastus/providers/Microsoft.Network/networkSecurityGroups/aks-agentpool-55978144-nsg/securityRules/gameserver]
module.aks_cluster.azurerm_kubernetes_cluster_node_pool.metrics: Still creating... [20s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster_node_pool.system: Still creating... [20s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster_node_pool.metrics: Still creating... [30s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster_node_pool.system: Still creating... [30s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster_node_pool.metrics: Still creating... [40s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster_node_pool.system: Still creating... [40s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster_node_pool.metrics: Still creating... [50s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster_node_pool.system: Still creating... [50s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster_node_pool.metrics: Still creating... [1m0s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster_node_pool.system: Still creating... [1m0s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster_node_pool.metrics: Still creating... [1m10s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster_node_pool.system: Still creating... [1m10s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster_node_pool.metrics: Still creating... [1m20s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster_node_pool.system: Still creating... [1m20s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster_node_pool.metrics: Still creating... [1m30s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster_node_pool.system: Still creating... [1m30s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster_node_pool.metrics: Still creating... [1m40s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster_node_pool.system: Still creating... [1m40s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster_node_pool.metrics: Still creating... [1m50s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster_node_pool.system: Still creating... [1m50s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster_node_pool.metrics: Still creating... [2m0s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster_node_pool.system: Still creating... [2m0s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster_node_pool.system: Still creating... [2m10s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster_node_pool.metrics: Still creating... [2m10s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster_node_pool.metrics: Still creating... [2m20s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster_node_pool.system: Still creating... [2m20s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster_node_pool.metrics: Still creating... [2m30s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster_node_pool.system: Still creating... [2m30s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster_node_pool.metrics: Still creating... [2m40s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster_node_pool.system: Still creating... [2m40s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster_node_pool.system: Still creating... [2m50s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster_node_pool.metrics: Still creating... [2m50s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster_node_pool.metrics: Still creating... [3m0s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster_node_pool.system: Still creating... [3m0s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster_node_pool.metrics: Creation complete after 3m9s [id=/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourcegroups/agonesRG/providers/Microsoft.ContainerService/managedClusters/test-cluster/agentPools/metrics]
module.aks_cluster.azurerm_kubernetes_cluster_node_pool.system: Creation complete after 3m9s [id=/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourcegroups/agonesRG/providers/Microsoft.ContainerService/managedClusters/test-cluster/agentPools/system]
module.helm_agones.helm_release.agones: Creating...
module.helm_agones.helm_release.agones: Still creating... [10s elapsed]
module.helm_agones.helm_release.agones: Still creating... [20s elapsed]
module.helm_agones.helm_release.agones: Still creating... [30s elapsed]
module.helm_agones.helm_release.agones: Creation complete after 33s [id=agones]

Apply complete! Resources: 6 added, 0 changed, 0 destroyed.
```

**Comment by markmandel** [comment]
@dzmitry-lahoda let me know if this works for you and is good to merge 😄 looks like you two own the AKS experience now.

**Comment by WeetA34** [comment]
yep main branch doesn't lock to azurer provider 2.63.0
PR is locked to 2.63.0 because it seems to be less problematic.
Don't forget terraform init -upgrade (or delete .terraform) before deploying new cluster

**Comment by dzmitry-lahoda** [comment]
```
azurerm_kubernetes_cluster_node_pool.system: Still creating... [3m0s elapsed]
azurerm_kubernetes_cluster_node_pool.system: Creation complete after 3m9s [id=/subscriptions/..../resourcegroups/rglahoda/providers/Microsoft.ContainerService/managedClusters/dztestcluster/agentPools/system]
azurerm_kubernetes_cluster_node_pool.metrics: Creation complete after 3m9s [id=/subscriptions/..../resourcegroups/rglahoda/providers/Microsoft.ContainerService/managedClusters/dztestcluster/agentPools/metrics]
╷
│ Error: Invalid index
│
│   on aks.tf line 112, in resource "azurerm_network_security_rule" "gameserver":
│  112:   network_security_group_name = [for network_security_group in data.azurerm_resources.network_security_groups.resources : network_security_group.name if length(regexall("^aks-agentpool-\\d+-nsg$", network_security_group.name)) > 0][0]
│     ├────────────────
│     │ data.azurerm_resources.network_security_groups.resources is empty list of object
│
│ The given key does not identify an element in this collection value.
╵
....\agones\install\terraform\modules\aks [update-aks-tf-template ≡ +0 ~2 -0 | +0 ~1 -0 !]> git branch
  main
* update-aks-tf-template
.....\agones\install\terraform\modules\aks [update-aks-tf-template ≡ +0 ~2 -0 | +0 ~1 -0 !]> 
```

same as in master on first attempt. there is official issue for MS to allow access to background network. so in this case may be https://registry.terraform.io/providers/hashicorp/time/latest/docs/resources/sleep help

**Comment by dzmitry-lahoda** [comment]
```
Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

**Comment by dzmitry-lahoda** [comment]
> Don't forget terraform init -upgrade (or delete .terraform) before deploying new cluster

did it

**Comment by WeetA34** [comment]
weird, i deployed twice from scratch with terraform 0.12.31 and azurerm 2.63.0 without any issue

**Comment by WeetA34** [comment]
i can add a sleep resource but as it's random, i'm not sure how many seconds/minutes to wait

**Comment by dzmitry-lahoda** [comment]
> i can add a sleep resource but as it's random, i'm not sure how many seconds/minutes to wait

30 seconds in `variables`. i will experiment with increased values.

**Comment by WeetA34** [comment]
deploying a fresh new cluster with terraform 1.0.1 (instead of 0.12.31) and azurerm 2.63.0

**Comment by WeetA34** [comment]
2 tests without any issue with terraform 0.12.31 and azurerm 2.63.0
1 test failed with terraform 1.0.1 and azurerm 2.63.0
```
$ terraform state show module.aks_cluster.data.azurerm_resources.network_security_groups
# module.aks_cluster.data.azurerm_resources.network_security_groups:
data "azurerm_resources" "network_security_groups" {
    id                  = "resource-28cc1555-9fcb-42d6-acd2-4d13b416087a"
    resource_group_name = "MC_agonesRG_test-cluster_eastus"
    resources           = []
    type                = "Microsoft.Network/networkSecurityGroups"
}
```

**Comment by WeetA34** [comment]
after waiting multiple minutes, datasource is still empty

**Comment by WeetA34** [comment]
ok after more than 5 minutes

**Comment by WeetA34** [comment]
I'm curious to know how are generated xxx in aks-agentpool-xxxxxxxx-nsg security group name. It's always the same numbers on my side

**Comment by dzmitry-lahoda** [comment]
image

**Comment by WeetA34** [comment]
ok. It's also 55978144 for me

**Comment by WeetA34** [comment]
so it's not related to subscription, resource group, location and cluster name

**Comment by WeetA34** [comment]
i found how it's generated
https://github.com/Azure/aks-engine/blob/master/pkg/api/types.go#L1014-L1030

**Comment by WeetA34** [comment]
It's confirmed
```
$ cat main.go
package main

import (
        "fmt"
        "hash/fnv"
        "math/rand"
)

const dnsSuffix = "agones"

func main() {
        h := fnv.New64a()
        h.Write([]byte(dnsSuffix))
        r := rand.New(rand.NewSource(int64(h.Sum64())))
        clusterID := fmt.Sprintf("%08d", r.Uint32())[:8]
        fmt.Println(clusterID)
}

$ go run main.go
55978144
```

**Comment by WeetA34** [comment]
now let's check  if we can have a fnv hash resource :)
So we can generate nsg group name instead of relying on unreliable data source

**Comment by WeetA34** [comment]
as we know the fnv hash (55978144) of dnsprefix (agones) and as it's not a variable, i guess we can hardcode the nsg group name

**Comment by WeetA34** [comment]
I'm testing the changes

**Comment by WeetA34** [comment]
```
$ terraform version
Terraform v1.0.1
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.66.0
+ provider registry.terraform.io/hashicorp/helm v1.3.2

$ terraform apply
...
Apply complete! Resources: 6 added, 0 changed, 0 destroyed.
```

**Comment by WeetA34** [comment]
Hello again @dzmitry-lahoda , i pushed a new version with static network security group name (the one which match cluster dns_prefix agones)

**Comment by WeetA34** [comment]
Hello @dzmitry-lahoda, can you confirm (when you have time) the last commit of this pr branch is ok? thank you

**Comment by dzmitry-lahoda** [comment]
thanks, i am ok with:) hope it will be stable, may be add comment into name resource telling not to rename it:)

**Comment by WeetA34** [comment]
i already put a comment before dns_prefix
i've checked how to create hash in HCL directly in TF but i didn't find a solution (needs uint64, xor)

**Comment by WeetA34** [comment]
Hello @markmandel 
it seems you can merge :)
thank you

**Comment by WeetA34** [comment]
regarding our issue with azurerm_resources datasource updated after a while, i found this which explains it:
https://github.com/Azure/AKS/issues/1964#issuecomment-729150191

there is a regional cache. That explains why i didn't have the issue the first time because i've probably european location

**Comment by WeetA34** [comment]
i confirm that datasource works fine when using the regional location as location for the AKS cluster.
in my case, management.azure.com resolves to the germanywestcentral endpoint
```
$ dig +noall +answer management.azure.com
management.azure.com.   0       IN      CNAME   management.privatelink.azure.com.
management.privatelink.azure.com. 0 IN  CNAME   arm-frontdoor-prod.trafficmanager.net.
arm-frontdoor-prod.trafficmanager.net. 0 IN CNAME germanywestcentral.management.azure.com.
germanywestcentral.management.azure.com. 0 IN CNAME rpfd-germanywestcentral.cloudapp.net.
rpfd-germanywestcentral.cloudapp.net. 0 IN A    51.116.156.32
```
no issue during cluster creation using azurerm_resources datasource. az cli also returns the security group just after terraform has finished. It took almost 20 minutes when i used eastus
```
$ terraform apply
...
Apply complete! Resources: 6 added, 0 changed, 0 destroyed.
 
$ az network nsg list
[
  {
    "defaultSecurityRules": [
...
    "name": "aks-agentpool-55978144-nsg",
    "networkInterfaces": null,
    "provisioningState": "Succeeded",
    "resourceGroup": "mc_agonesrg_test-cluster_germanywestcentral",
...
]
```

**Comment by WeetA34** [comment]
so until to have a way to bypass the regional cache, the best option is not using datasource which this PR does

**Comment by markmandel** [comment]
👋🏻  just checking in, and scrolling past allll the comments 😄 this good to go, or we still playing with it?

**Comment by WeetA34** [comment]
Good to go. I’ve have no solution for the regional cache so i can’t put back the azurerm_resources data source.

**Comment by markmandel** [comment]
@dzmitry-lahoda you happy to? In which case, we can land this before RC next week 👍🏻

**Review by markmandel — APPROVED** [review]

**Pull request merged**
