### PR TITLE
Allocation: Drop stale GameServer on conflict

### PR DESCRIPTION
**Pull request by markmandel**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking
> /kind bug

/kind cleanup

> /kind documentation
> /kind feature
> /kind hotfix

**What this PR does / Why we need it**:

Previously, if an attempt at allocation would fail, it would get placed automatically back into the local cache.

If the failure was because of a Conflict, there is no point in putting it back into the cache, as it will never succeed until it gets updated from the Kubernetes API.

**Which issue(s) this PR fixes**:

Work on #1856

**Special notes for your reviewer**:

Running at high load (TESTRUNSCOUNT=1 ./runAllocation.sh 200 20), reduced the number of failed allocations due to contention from 298 down to 180.

### CODE REVIEW

**Review by roberthbailey — APPROVED** [review]

**Comment by roberthbailey** [comment]
There was an error in the rust conformance test:

```
error[E0658]: `match` is not allowed in a `const fn`
   --> /go/src/agones.dev/agones/test/sdk/rust/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.4.0/src/lib.rs:156:9
    |
156 | /         match address {
157 | |             SocketAddr::V4(_) => Domain::IPV4,
158 | |             SocketAddr::V6(_) => Domain::IPV6,
159 | |         }
    | |_________^
    |
    = note: see issue #49146 <https://github.com/rust-lang/rust/issues/49146> for more information

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: could not compile `socket2`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
includes/sdk.mk:88: recipe for target 'run-sdk-command' failed
make[2]: *** [run-sdk-command] Error 101
```

I'm going to try again and see if it's reproducible.

**Comment by roberthbailey** [comment]
The test failed with the same rust error, so it looks like it isn't a flake.

**Comment by roberthbailey** [comment]
I'm able to reproduce the error locally.

**Comment by markmandel** [comment]
> I'm able to reproduce the error locally.

I'm struggling to reproduce locally. Care to share your steps?

I must have a cache library version of something locally I'm sure.

**Comment by markmandel** [comment]
Ah - worked it out, I had a Cargo.lock sitting around that pointed to an older version of the library.

**Pull request merged**
