### PR TITLE
Player Tracking: Json "IDs" => "ids"

### PR DESCRIPTION
**Pull request by markmandel**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking
> /kind bug

/kind cleanup

> /kind documentation
> /kind feature
> /kind hotfix

**What this PR does / Why we need it**:
Fix on a small capitalisation issue on JSON output of the GameServer CRD
changes.

**Which issue(s) this PR fixes**:

Work on #1033

**Special notes for your reviewer**:
None

### CODE REVIEW

**Comment by markmandel** [comment]
> Can you please update the swagger file as well: https://github.com/googleforgames/agones/blob/master/sdks/swagger/sdk.swagger.json#L348

Ah, excellent catch. Will do. We should probably have a test for this.

**Comment by markmandel** [comment]
So I ran the generation grpc & swagger, and it looks like this value doesn't touch the SDK, so there are no changes to the swagger.json -- it's only a CRD storage/retrieval change.

**Comment by pooneh-m** [comment]
Should the IDs in the proto be updated as well to conform with the [naming conventions](https://developers.google.com/protocol-buffers/docs/style)?
https://github.com/googleforgames/agones/blob/master/proto/sdk/sdk.proto#L151

**Comment by markmandel** [comment]
> Should the IDs in the proto be updated as well to conform with the [naming conventions](https://developers.google.com/protocol-buffers/docs/style)?
> https://github.com/googleforgames/agones/blob/master/proto/sdk/sdk.proto#L151

Ooh! Yeah, I think they should. I'll do a separate PR with this change.

**Pull request merged**
