### PR TITLE
add copy to clipboard function to code on website

### LINKED ISSUE #2096: Add "copy to clipboard" buttons to example commands on the website
**Is your feature request related to a problem? Please describe.**
It's easy to make a mistake when copy/pasting from the agones documentation site. One example is when setting up the allocator service: https://agones.dev/site/docs/advanced/allocator-service/

**Describe the solution you'd like**
This could be solved by adding a button that allows the user to copy to clipboard, rather than relying on them selecting the command themselves. If we do this, we should look at other pages that would also benefit from having commands be easily copied (although we may need to create other bugs since the surface area is pretty large). 

**Describe alternatives you've considered**
Leave as-is, maybe simplify the service setup so that it takes fewer steps?

### PR DESCRIPTION
**Pull request by cindy52**
**What type of PR is this?**
 /kind feature

**What this PR does / Why we need it**:
Add "copy to clipboard" buttons to example commands on the website

**Which issue(s) this PR fixes**:

Closes #2096 

**Special notes for your reviewer**:
NA

### CODE REVIEW

**Comment by roberthbailey** [comment]
Thanks for the pull request! It seems like this wasn't that hard to add with the new version of docsy. :)

I'm looking at the website preview and I'm kinda disappointed in the way that prismjs renders the copy button (obviously not your fault). 

I've been looking for examples of any other sites using prism for this functionality but I'm having trouble finding any. I've found examples like https://tutsplus.github.io/clipboard/ and https://chrissainty.com/copy-to-clipboard-in-blazor/ and https://medium.com/@nrrrdcore/tiny-design-bite-transitioning-tooltip-text-with-pseudo-elements-hover-states-82fbe00e8c33 which to me look sooo much nicer. I wonder if we should check with the docsy authors to see if they have suggestions on how we might be able to style this more nicely.

**Comment by markmandel** [comment]
Oh yeah, that's uh... super ugly 😬 

image

Weirdly also, I see the copy button on "Install Agones using YAML" but not on any of the Quickstarts

image

Not quite sure why that is 🤔

**Comment by roberthbailey** [comment]
Here's another example of a "nicer" looking copy button: https://kind.sigs.k8s.io/docs/user/quick-start/#installation

**Comment by cindy52** [comment]
I think it's also related to our current code block style. I found an example here https://github.com/jenkins-x/jx-docs with different style and the copy button looks much nicer.

**Comment by cindy52** [comment]
Took a look at the kind.sigs.k8s site code, looks like they defined their own copyText function https://github.com/kubernetes-sigs/kind/blob/b6bc112522651d98c81823df56b7afa511459a3b/site/assets/js/inline.js#L67 instead of using prism.

**Comment by cindy52** [comment]
> Here's another example of a "nicer" looking copy button: https://kind.sigs.k8s.io/docs/user/quick-start/#installation
 I took a look at the kind.sigs.k8s site code, looks like they defined their own copyText function https://github.com/kubernetes-sigs/kind/blob/b6bc112522651d98c81823df56b7afa511459a3b/site/assets/js/inline.js#L67 instead of using prism.

**Comment by cindy52** [comment]
> Oh yeah, that's uh... super ugly 😬
> 
> image
> 
> Weirdly also, I see the copy button on "Install Agones using YAML" but not on any of the Quickstarts
> 
> image
> 
> Not quite sure why that is 🤔

I think the copy button only show up when the code is in the block of '''bash some_code'''. All the code in quickstart is only one line thus in a block of  '''some_code '''.

**Comment by markmandel** [comment]
> I think the copy button only show up when the code is in the block of '''bash some_code'''. All the code in quickstart is only one line thus in a block of '''some_code '''.

Aha! Sounds like we will want to review that then, so we can make sure to add copy buttons in relevant places around the site.

**Comment by cindy52** [comment]
@roberthbailey , @markmandel , please take another look. I've adjusted the copy button a little bit. It looks way better this time.

**Comment by markmandel** [comment]
That looks better! 👍🏻 Nice!

Do we want to use this PR to do a review of all the places we have commands that are copy-pastable?

**Comment by cindy52** [comment]
> That looks better! 👍🏻 Nice!
> 
> Do we want to use this PR to do a review of all the places we have commands that are copy-pastable?

Do we want to add copy button to all the commands (including just one line) or just bash scripts (multiple lines)?

**Comment by markmandel** [comment]
👋🏻 what happened with this PR? Looked like it was on a good path? 😞

**Comment by roberthbailey** [comment]
See https://github.com/googleforgames/agones/pull/2149

**Pull request closed without merging**
