### PR TITLE
add copy to clipboard function to code on website

### LINKED ISSUE #2096: Add "copy to clipboard" buttons to example commands on the website
**Is your feature request related to a problem? Please describe.**
It's easy to make a mistake when copy/pasting from the agones documentation site. One example is when setting up the allocator service: https://agones.dev/site/docs/advanced/allocator-service/

**Describe the solution you'd like**
This could be solved by adding a button that allows the user to copy to clipboard, rather than relying on them selecting the command themselves. If we do this, we should look at other pages that would also benefit from having commands be easily copied (although we may need to create other bugs since the surface area is pretty large). 

**Describe alternatives you've considered**
Leave as-is, maybe simplify the service setup so that it takes fewer steps?

### PR DESCRIPTION
**Pull request by cindy52**
**What type of PR is this?**
 /kind feature

**What this PR does / Why we need it**:
Add "copy to clipboard" buttons to example commands on the website

**Which issue(s) this PR fixes**:

Closes #2096 

**Special notes for your reviewer**:
NA

### CODE REVIEW

**Comment by cindy52** [comment]
Hi @roberthbailey , @markmandel , I accidentally delete the remote branch while I was rebasing the commits and the pr got closed automatically. I create a new pr with all desired code block style. Please take another look. Sorry about the inconvenience.  Thanks!

**Comment by roberthbailey** [comment]
Since this PR only changes the website, the test failure is definitely a flake. I've updated the branch to force a new test run.

**Review by aLekSer — APPROVED** [review]
Thanks for the PR. Now website much more easy to use.
New copy button was added successfully:
CopyButton

**Comment by roberthbailey** [comment]
This looks much better! Thanks for fixing the copy buttons :)

It bothers me a little bit that the copyable and non-copyable blocks now have different fonts/sizes:

Screen Shot

But this is so much better that's it's worth it. I'm going to file another issue to try and clean up the styling, while pushing this live.

**Comment by markmandel** [comment]
Aha! totally missed it! Thanks for the pointer.

**Pull request merged**
