### PR TITLE
docs: remove --node-ami auto for managed nodegroups

### PR DESCRIPTION
**Pull request by SpringMT**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, press enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking
> /kind bug
> /kind cleanup

/kind documentation

> /kind feature
> /kind hotfix

**What this PR does / Why we need it**:
`eksctl` doesn't need `--node-ami auto` for creating EKS cluster.

https://eksctl.io/usage/custom-ami-support/

https://github.com/weaveworks/eksctl/pull/3754

The option happens the error below.
`Error: invalid AMI "auto" (managedNodeGroups[0].ami)`

So, delete `--node-ami auto` options in this ducument.

**Which issue(s) this PR fixes**:

N/A

**Special notes for your reviewer**:
N/A

### CODE REVIEW

**Comment by roberthbailey** [comment]
Thank you for the fix. Can you confirm that this is broken _now_ and should be immediately published to the website (not waiting for our next Agones release, which is how we normally publish website changes)?

**Comment by SpringMT** [comment]
I have no problem releasing it in the next Agones release.

**Comment by roberthbailey** [comment]
In that case, you will need to use the `feature` shortcodes to gate the change. See https://agones.dev/site/docs/contribute/#within-a-page

**Comment by SpringMT** [comment]
This change is not related to agones. (affected eksctl)
So,  I think `feature` shortcodes does not work well.

**Review by roberthbailey — APPROVED** [review]

**Pull request merged**
