### PR TITLE
Add RollTable to Companies that use Agones

### PR DESCRIPTION
**Pull request by NullSoldier**
**What type of PR is this?**
/kind documentation

**What this PR does / Why we need it**:
I was recommended to add this to the company list from a comment on our companies blog article here https://medium.com/rolltableapp/scalable-game-servers-using-agones-node-and-digital-ocean-90e6fb9ee5d

> Mark Mandel 6 days ago
> This is awesome! Thanks for sharing your experience with Agones!!!
> If you are interested, we'd love to have the Rolltable logo on https://agones.dev homepage - so please file a PR if this is something you are interested in showcasing!

**Which issue(s) this PR fixes**:
None

**Special notes for your reviewer**:
Agones is awesome and we love the project at RollTable.

### CODE REVIEW

**Comment by NullSoldier** [comment]
@googlebot I signed it!

**Comment by markmandel** [comment]
Can you please put your logo at the end of the list? This is first comes first served. No cutsies. :smile:

**Comment by NullSoldier** [comment]
Will do!

**Comment by markmandel** [comment]
If you run `make site-server` from within the build directory, it will take a while to create the Docker image, but you can run the site locally.

https://agones.dev/site/docs/contribute/

**Review by markmandel — APPROVED** [review]
NOICE!

Thank you!

**Comment by NullSoldier** [comment]
Thank you too. Also we have a node implementation of the agones node RPC API but it's pretty unfinished. If we clean up the code a ton, refactor it, and get production ready (for others), would you all take contributions for that?

**Comment by markmandel** [comment]
> Thank you too. Also we have a node implementation of the agones node RPC API but it's pretty unfinished. If we clean up the code a ton, refactor it, and get production ready (for others), would you all take contributions for that?

Do you mean for the K8s CRD API? Or for the integration SDK?

**Comment by NullSoldier** [comment]
K8s CRD API

**Comment by markmandel** [comment]
Not sure if that's something we want to take on the maintenance burden for, but if you want to publish it and post it to:
https://agones.dev/site/docs/third-party-content/libraries-tools/ (maybe a new section?)

I think that would be an awesome first start!

**Pull request merged**
