### PR TITLE
NodeExternalDNS moved to beta

### LINKED ISSUE #2240: Move NodeExternalDNS to Beta
Context:
https://development.agones.dev/site/docs/guides/feature-stages/#feature-gates

The "Utilize Node ExternalDNS and additional details" feature has been in alpha since 1.12.0. We discussed during the community meeting today and decided to promote it to beta for the next release.

### PR DESCRIPTION
**Pull request by himanshu007-creator**
**What type of PR is this?**

kind documentation

**What this PR does / Why we need it**:

**Which issue(s) this PR fixes**: #2240 

Closes #2240 

**Special notes for your reviewer**:

### CODE REVIEW

**Review by roberthbailey — COMMENTED** [review]
The file you modified is just the documentation. You will need to update it, but also make code changes as well. 

See https://github.com/googleforgames/agones/pull/2033 for an example of moving a feature from alpha to beta.

**Comment by roberthbailey** [comment]
We have about a week left before the next release candidate. Do you think you will be able to work on this before the 1.18 release?

**Comment by roberthbailey** [comment]
@himanshu007-creator - this PR now needs a rebase due to the 1.18 release. Do you plan to keep working on it?

**Comment by markmandel** [comment]
This has been open 26 days, shall we close this?

Let's open a PR when it comes around again?

**Comment by markmandel** [comment]
Marked this as stale 7 days ago. Seems like no objections to closing in that time, so I'll close for now 👍🏻 Please reopen a new PR if you decide to revisit.

**Pull request closed without merging**
