### PR TITLE
added tolerations to gameserver-allocator

### PR DESCRIPTION
**Pull request by daplho**

### CODE REVIEW

**Comment by daplho** [comment]
I signed it!

**Comment by markmandel** [comment]
Just testing this out, unfortunately this doesn't look like it 100% worked :cry: 

```
root@5d5f0e8354d9:/go/src/agones.dev/agones# kubectl get pods --namespace=agones-system -o wide
NAME                                   READY   STATUS    RESTARTS   AGE     IP           NODE                                           NOMINATED NODE
agones-controller-6d649d4447-z9qtc     1/1     Running   0          6m5s    10.56.2.10   gke-test-cluster-agones-system-7901999e-p5kx   <none>
agones-ping-5fb659769c-7k665           1/1     Running   0          6m12s   10.56.2.7    gke-test-cluster-agones-system-7901999e-p5kx   <none>
agones-ping-5fb659769c-k4nwr           1/1     Running   0          6m9s    10.56.2.9    gke-test-cluster-agones-system-7901999e-p5kx   <none>
gameserver-allocator-8bfd97cdc-6z56w   1/1     Running   0          6m8s    10.56.3.6    gke-test-cluster-default-4ad29908-6fjh         <none>
gameserver-allocator-8bfd97cdc-fs4z5   1/1     Running   0          6m5s    10.56.5.3    gke-test-cluster-default-4ad29908-j2kf         <none>
gameserver-allocator-8bfd97cdc-shnjt   1/1     Running   0          6m12s   10.56.2.8    gke-test-cluster-agones-system-7901999e-p5kx   <none>
```

I've not played with toleration much, but looking at the [controller example](https://github.com/googleforgames/agones/blob/master/install/helm/agones/templates/controller.yaml#L60-L62), there is more to add?

**Comment by daplho** [comment]
What do you see that's not working with the pods you `kubectl got` above?

**Comment by markmandel** [comment]
If you look at the allocator, you can see they are on different nodes - if the default toleration is set correctly, none of them would be on the default nodepool - but as you can see from the above output, two pods are.

Also - to make the tests pass, you'll need to run `make gen-install` once the helm setup is working correctly to regenerate the install.tank 👍

**Pull request closed without merging**
