### PR TITLE
Adding initial README for new Unreal SDK

### PR DESCRIPTION
**Pull request by comerford**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:

/kind documentation

**What this PR does / Why we need it**:

Porting over the README for the Unreal SDK from Netspeak Games with a few tweaks, intent is to add to this once I actually migrate to this SDK with notes on usage. This preserves the documentation from the original repo and adds some notes about the migration and the fact that the SDK is new in 1.8.0

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by domgreen** [comment]
Thanks @comerford we actually moved the `README.md` under the docs that are generated for the site at the request of @markmandel 

I personally am a fan of having a readme in the plugin but would mean that the docs and the readme need to be kept in sync.

See https://github.com/googleforgames/agones/blob/master/site/content/en/docs/Guides/Client%20SDKs/unreal.md as this is where it was ported to.

**Comment by comerford** [comment]
ah, no worries then - I will close this out :)

**Comment by domgreen** [comment]
> ah, no worries then - I will close this out :)

I would be interested in seeing any updates you made :D always good to get a second pair of eyes

**Comment by comerford** [comment]
I am currently installing the plugin, if I hit any speed bumps I will circle back to the main docs and update for sure - thanks for this, love that it is more feature complete and the game devs are super happy that it looks more Unreal-native

**Pull request closed without merging**
