### PR TITLE
Upgrade Docker to 24.0.6

### PR DESCRIPTION
**Pull request by Kalaiselvi84**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, press enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking
> /kind bug

/kind cleanup
> /kind documentation
> /kind feature
> /kind hotfix
> /kind release

**What this PR does / Why we need it**:

**Which issue(s) this PR fixes**:

Work on #3530 

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by gongmax** [comment]
`push-images` failed: https://pantheon.corp.google.com/cloud-build/builds/2c03840c-f90f-4edf-be16-7af5c56f7c30;step=17?mods=logs_tg_prod&project=agones-images

**Review by markmandel — COMMENTED** [review]
This looks good! Lemme just take it for a spin on a machine that has Docker 24.x on it and make sure everything works

**Comment by markmandel** [comment]
...and confirmed it works on Docker 24.x!

**Review by markmandel — APPROVED** [review]
Let's upgrade!

**Pull request merged**
