### PR TITLE
Adding Fleet Active GameServerSet Percentage Metrics

### LINKED ISSUE #3663: Adding GameServerSet Metric
**Is your feature request related to a problem? Please describe.**
- When I update fleet, the fleet update gameserver using rolling update strategy. I'd like to see the flow of change in gameserverset.
- `agones_fleets_replicas_count` metric only has `fleet_name` 

**Describe the solution you'd like**
- Add metric `agones_gameserverset_replicas_count` for gameserverset.
  - This will be useful for checking the progress of the update

**Additional context**
- https://agones.dev/site/docs/guides/metrics/

### PR DESCRIPTION
**Pull request by 0xaravindh**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, press enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking
> /kind bug

 /kind cleanup
 
> /kind documentation
> /kind feature
> /kind hotfix
> /kind release

**What this PR does / Why we need it**:

**Which issue(s) this PR fixes**: #3663

Closes #3663

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by peterzhongyi** [comment]
How should I verify that the newly added metric is working as intended? Is there some test that covers it, or I can perform some series of actions to verify the metric is working in the dashboard? If so, can you add to the description of the pr?

**Comment by 0xaravindh** [comment]
@peterzhongyi For additional guidance, refer to [PR #3663](https://github.com/googleforgames/agones/issues/3663), where Mark provided helpful suggestions that I have followed closely.

**Comment by gongmax** [comment]
@0xaravindh would you like to test your change by following https://agones.dev/site/docs/guides/metrics/#installation to install prometheus and grafana locally and see whether the new added metrics shows up?

**Comment by 0xaravindh** [comment]
> @0xaravindh would you like to test your change by following https://agones.dev/site/docs/guides/metrics/#installation to install prometheus and grafana locally and see whether the new added metrics shows up?

@gongmax I’ve tested it by following the guide to install Prometheus and Grafana locally, and the new metrics are showing up correctly in gs dashboard. do you think stats are looking enough? or should I include any additional data in that field?

6QXdAiLVoSYKXL2

**Comment by vicentefb** [comment]
lgtm

**Review by vicentefb — APPROVED** [review]

**Pull request merged**
