### PR TITLE
Upgrade dev tooling kubectl to 1.18

### PR DESCRIPTION
**Pull request by markmandel**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>

/kind breaking

> /kind bug
> /kind cleanup
> /kind documentation
> /kind feature
> /kind hotfix

**What this PR does / Why we need it**:

For both the build image and the e2e image.

**Which issue(s) this PR fixes**:

Work on #1971

**Special notes for your reviewer**:

N/A

### CODE REVIEW

**Comment by markmandel** [comment]
Some e2e tests failed:

```
--- FAIL: TestGameServerAllocationMetaDataPatch (167.70s)
    gameserverallocation_test.go:283: 
        	Error Trace:	gameserverallocation_test.go:283
        	Error:      	timed out waiting for the condition
        	Test:       	TestGameServerAllocationMetaDataPatch

--- FAIL: TestSDKSetLabel (181.58s)
    gameserver_test.go:94: 
        	Error Trace:	gameserver_test.go:94
        	Error:      	Received unexpected error:
        	            	timed out waiting for the condition
        	Test:       	TestSDKSetLabel

--- FAIL: TestGameServerShutdown (318.05s)
    gameserver_test.go:658: 
        	Error Trace:	gameserver_test.go:658
        	Error:      	Received unexpected error:
        	            	timed out waiting for the condition
        	Test:       	TestGameServerShutdown

```

Will rerun and see if it's flaky, or a real issue.

**Comment by markmandel** [comment]
Failed again. Will need to investigate.

```
--- FAIL: TestGameServerTcpUdpProtocol (181.19s)
    gameserver_test.go:748: Could not ping TCP GameServer: dial tcp 34.82.222.150:7675: connect: connection timed out
```

Will try one more time just for giggles.

**Comment by markmandel** [comment]
At least this seems consistent:

```
--- FAIL: TestGameServerTcpUdpProtocol (163.87s)
    gameserver_test.go:748: Could not ping TCP GameServer: dial tcp 35.247.81.255:7537: connect: connection timed out
time="2021-02-10 05:10:24.435" level=info msg="fleet simple-fleet-grlfq has 10/10 ready replicas"
```

**Comment by markmandel** [comment]
:facepalm: I know why it's failing. The tcp firewall rule is gone. Hmnn, that's odd.

**Review by roberthbailey — APPROVED** [review]

**Pull request merged**
