### PR TITLE
CI: Wait for tests step before sdk-conformance

### PR DESCRIPTION
**Pull request by aLekSer**
Both these steps would trigger building with `go run` or `npm run` in
parallel on the same directories.

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking

/kind bug

**What this PR does / Why we need it**:
CI is fluctuating and fails too frequently.

**Which issue(s) this PR fixes**:

Work on #1779

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by aLekSer** [comment]
Too many simultaneous E2E tests:

```
Setting up lock at path: LockE2E/.lock
Attempting lock acquisition
Handling connection for 8500
Lock acquisition failed: failed to acquire lock: Unexpected response code: 500 (invalid session "a700b588-431a-01e4-b6f1-99e7d9461afb")
```

**Comment by markmandel** [comment]
This is looking like it's solving the issue? Although it does look like it pushes the CI time to completion from around 18 minutes to around 30 - which is a big jump (that being said, we're probably at that already with retries, so :shrug:)

Run it a few more times, and if it keeps passing, I say let's merge it. WDYT?

**Comment by aLekSer** [comment]
Well, yes, longest running time is bad, we can fix this side effect somehow with caching. We can see SDK conformance would not come up at a later time, if it would be as frequent as now, we can remove this `"wait_for": "tests"` or might move tests which could not run together in a separate cloud build step, or add File Lock before running the same test twice, say NodeJS SDK test would wait for release of file lock in NodeJS SDK conformance test?

**Review by markmandel — APPROVED** [review]
Hasn't failed yet!

**Pull request merged**
