### PR TITLE
Adding AccelByte in Companies using Agones list

### PR DESCRIPTION
**Pull request by accelbyte-raymond**
Adding in AccelByte logo to Agones static site

### CODE REVIEW

**Comment by accelbyte-raymond** [comment]
@googlebot I signed it!

**Comment by markmandel** [comment]
Ray, I'm not sure your commit email, and your account email line up.

(looks like your github account doesn't have an email associated that I can see???)

**Comment by accelbyte-raymond** [comment]
It's a mystery :)
Alright, I changed my email to raymond@accelbyte.net and have the .io one
as alternate email :)

**Comment by markmandel** [comment]
Looks like we don't have a CLA for the raymond@accelbyte.net email yet.

**Comment by accelbyte-raymond** [comment]
I signed a CLA for AccelByte Inc, and provided the
google-contributors@accelbyte.net as contributors from AccelByte side.
Hopefully that would work?

**Comment by markmandel** [comment]
Ah, corporate CLA's can take a few days:
https://opensource.google/docs/cla/#cla-accepted

Will wait!

**Pull request merged**
