### PR TITLE
Cleanup load tests

### LINKED ISSUE #2744: Shows missing "/usr/local/bin/locust" after building container
**What happened**:
After building container, when I run this command "docker run --rm --network="host" -e "LOCUST_FILE=gameserver_allocation.py"  -e "TARGET_HOST=http://127.0.0.1:8001" -p 8089:8089 locust-files:latest", it is showing "missing /usr/local/bin/locust"

**What you expected to happen**:
I expect locust tests running on game server allocation.

**How to reproduce it (as minimally and precisely as possible)**:
These is the output of all commands I run on Windows:
`PS D:\Projects\<PROJECT>\git\test-load-agones\agones\test\load> docker build -t locust-files .
[+] Building 2.4s (12/12) FINISHED
 => [internal] load build definition from Dockerfile                                                                   0.0s
 => => transferring dockerfile: 32B                                                                                    0.0s
 => [internal] load .dockerignore                                                                                      0.0s
 => => transferring context: 2B                                                                                        0.0s
 => [internal] load metadata for docker.io/hopsoft/graphite-statsd:latest                                              2.2s
 => [auth] hopsoft/graphite-statsd:pull token for registry-1.docker.io                                                 0.0s
 => [internal] load build context                                                                                      0.0s
 => => transferring context: 170B                                                                                      0.0s
 => [1/6] FROM docker.io/hopsoft/graphite-statsd@sha256:40d36394594e4d0a6d0497e6609c48b652b0a3e230b735dcd5b140fe76daa  0.0s
 => CACHED [2/6] RUN pip install locust                                                                                0.0s
 => CACHED [3/6] RUN mkdir /etc/service/locust                                                                         0.0s
 => CACHED [4/6] COPY /locust-files ./                                                                                 0.0s
 => CACHED [5/6] COPY /run.sh /etc/service/locust/run                                                                  0.0s
 => CACHED [6/6] RUN chmod +x /etc/service/locust/run                                                                  0.0s
 => exporting to image                                                                                                 0.1s
 => => exporting layers                                                                                                0.0s
 => => writing image sha256:b788dd11d570472ecdbc8be25c61e11454790e0c4c2ca642412b9f263000e477                           0.0s
 => => naming to docker.io/library/locust-files                                                                        0.0s
PS D:\Projects\PROJECT\git\test-load-agones\agones\test\load> docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
PS D:\Projects\PROJECT\git\test-load-agones\agones\test\load> docker ps --all
CONTAINER ID   IMAGE                    COMMAND                  CREATED      STATUS                   PORTS     NAMES
41df2a23f4da   docker/getting-started   "/docker-entrypoint.…"   7 days ago   Exited (0) 6 hours ago             compassionate_greider
PS D:\Projects\PROJECT\git\test-load-agones\agones\test\load> docker build -t locust-files .
[+] Building 1.2s (11/11) FINISHED
 => [internal] load build definition from Dockerfile                                                                   0.0s
 => => transferring dockerfile: 32B                                                                                    0.0s
 => [internal] load .dockerignore                                                                                      0.0s
 => => transferring context: 2B                                                                                        0.0s
 => [internal] load metadata for docker.io/hopsoft/graphite-statsd:latest                                              1.1s
 => [1/6] FROM docker.io/hopsoft/graphite-statsd@sha256:40d36394594e4d0a6d0497e6609c48b652b0a3e230b735dcd5b140fe76daa  0.0s
 => [internal] load build context                                                                                      0.0s
 => => transferring context: 170B                                                                                      0.0s
 => CACHED [2/6] RUN pip install locust                                                                                0.0s
 => CACHED [3/6] RUN mkdir /etc/service/locust                                                                         0.0s
 => CACHED [4/6] COPY /locust-files ./                                                                                 0.0s
 => CACHED [5/6] COPY /run.sh /etc/service/locust/run                                                                  0.0s
 => CACHED [6/6] RUN chmod +x /etc/service/locust/run                                                                  0.0s
 => exporting to image                                                                                                 0.1s
 => => exporting layers                                                                                                0.0s
 => => writing image sha256:b788dd11d570472ecdbc8be25c61e11454790e0c4c2ca642412b9f263000e477                           0.0s
 => => naming to docker.io/library/locust-files                                                                        0.0s
PS D:\Projects\PROJECT\git\test-load-agones\agones\test\load> docker ps --all
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
PS D:\Projects\PROJECT\git\test-load-agones\agones\test\load> docker images
REPOSITORY               TAG       IMAGE ID       CREATED        SIZE
locust-files             latest    b788dd11d570   6 hours ago    1.26GB
docker/getting-started   latest    cb90f98fd791   5 months ago   28.8MB
PS D:\Projects\PROJECT\git\test-load-agones\agones\test\load> docker run --rm --network="host" -e "LOCUST_FILE=gameserver_allocation.py"  -e "TARGET_HOST=http://127.0.0.1:8001" -p 8089:8089 locust-files:latest
WARNING: Published ports are discarded when using host network mode
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/my_init.d/01_conf_init.sh...
*** Running /etc/rc.local...
*** Booting runit daemon...
*** Runit started as PID 15
/usr/local/bin/locust -f gameserver_allocation.py --host=http://127.0.0.1:8001
./run: line 17: /usr/local/bin/locust: No such file or directory
Sep 21 10:46:10 docker-desktop syslog-ng[20]: syslog-ng starting up; version='3.5.6'
2022/09/21 10:46:10 [I] Starting Grafana
2022/09/21 10:46:10 [I] Version: master, Commit: NA, Build date: 1970-01-01 00:00:00 +0000 UTC
2022/09/21 10:46:10 [I] Configuration Info
Config files:
  [0]: /usr/share/grafana/conf/defaults.ini
  [1]: /etc/grafana/grafana.ini
Paths:
  home: /usr/share/grafana
  data: /usr/share/grafana/data
  logs: /var/log/grafana

2022/09/21 10:46:10 [I] Database: sqlite3
2022/09/21 10:46:10 [I] Migrator: Starting DB migration
2022/09/21 10:46:10 [I] Migrator: exec migration id: create migration_log table
2022/09/21 10:46:10 [I] Migrator: exec migration id: create user table
2022/09/21 10:46:10 [I] Migrator: exec migration id: add unique index user.login
2022/09/21 10:46:10 [I] Migrator: exec migration id: add unique index user.email
2022/09/21 10:46:10 [I] Migrator: exec migration id: drop index UQE_user_login - v1
2022/09/21 10:46:10 [I] Migrator: exec migration id: drop index UQE_user_email - v1
2022/09/21 10:46:10 [I] Migrator: exec migration id: Rename table user to user_v1 - v1
2022/09/21 10:46:10 [I] Migrator: exec migration id: create user table v2
2022/09/21 10:46:10 [I] Migrator: exec migration id: create index UQE_user_login - v2
2022/09/21 10:46:10 [I] Migrator: exec migration id: create index UQE_user_email - v2
2022/09/21 10:46:10 [I] Migrator: exec migration id: copy data_source v1 to v2
2022/09/21 10:46:10 [I] Migrator: exec migration id: Drop old table user_v1
2022/09/21 10:46:10 [I] Migrator: exec migration id: create temp user table v1-7
2022/09/21 10:46:10 [I] Migrator: exec migration id: create index IDX_temp_user_email - v1-7
2022/09/21 10:46:10 [I] Migrator: exec migration id: create index IDX_temp_user_org_id - v1-7
2022/09/21 10:46:10 [I] Migrator: exec migration id: create index IDX_temp_user_code - v1-7
2022/09/21 10:46:10 [I] Migrator: exec migration id: create index IDX_temp_user_status - v1-7
2022/09/21 10:46:10 [I] Migrator: exec migration id: create star table
2022/09/21 10:46:10 [I] Migrator: exec migration id: add unique index star.user_id_dashboard_id
2022/09/21 10:46:10 [I] Migrator: exec migration id: create org table v1
2022/09/21 10:46:10 [I] Migrator: exec migration id: create index UQE_org_name - v1
2022/09/21 10:46:10 [I] Migrator: exec migration id: create org_user table v1
2022/09/21 10:46:10 [I] Migrator: exec migration id: create index IDX_org_user_org_id - v1
2022/09/21 10:46:10 [I] Migrator: exec migration id: create index UQE_org_user_org_id_user_id - v1
2022/09/21 10:46:10 [I] Migrator: exec migration id: copy data account to org
2022/09/21 10:46:10 [I] Migrator: skipping migration id: copy data account to org, condition not fulfilled
2022/09/21 10:46:10 [I] Migrator: exec migration id: copy data account_user to org_user
2022/09/21 10:46:10 [I] Migrator: skipping migration id: copy data account_user to org_user, condition not fulfilled
2022/09/21 10:46:10 [I] Migrator: exec migration id: Drop old table account
2022/09/21 10:46:10 [I] Migrator: exec migration id: Drop old table account_user
2022/09/21 10:46:10 [I] Migrator: exec migration id: create dashboard table
2022/09/21 10:46:11 [I] Migrator: exec migration id: add index dashboard.account_id
2022/09/21 10:46:11 [I] Migrator: exec migration id: add unique index dashboard_account_id_slug
2022/09/21 10:46:11 [I] Migrator: exec migration id: create dashboard_tag table
2022/09/21 10:46:11 [I] Migrator: exec migration id: add unique index dashboard_tag.dasboard_id_term
2022/09/21 10:46:11 [I] Migrator: exec migration id: drop index UQE_dashboard_tag_dashboard_id_term - v1
2022/09/21 10:46:11 [I] Migrator: exec migration id: Rename table dashboard to dashboard_v1 - v1
2022/09/21 10:46:11 [I] Migrator: exec migration id: create dashboard v2
2022/09/21 10:46:11 [I] Migrator: exec migration id: create index IDX_dashboard_org_id - v2
2022/09/21 10:46:11 [I] Migrator: exec migration id: create index UQE_dashboard_org_id_slug - v2
2022/09/21 10:46:11 [I] Migrator: exec migration id: copy dashboard v1 to v2
2022/09/21 10:46:11 [I] Migrator: exec migration id: drop table dashboard_v1
2022/09/21 10:46:11 [I] Migrator: exec migration id: alter dashboard.data to mediumtext v1
2022/09/21 10:46:11 [I] Migrator: exec migration id: create data_source table
2022/09/21 10:46:11 [I] Migrator: exec migration id: add index data_source.account_id
2022/09/21 10:46:11 [I] Migrator: exec migration id: add unique index data_source.account_id_name
2022/09/21 10:46:11 [I] Migrator: exec migration id: drop index IDX_data_source_account_id - v1
2022/09/21 10:46:11 [I] Migrator: exec migration id: drop index UQE_data_source_account_id_name - v1
2022/09/21 10:46:11 [I] Migrator: exec migration id: Rename table data_source to data_source_v1 - v1
2022/09/21 10:46:11 [I] Migrator: exec migration id: create data_source table v2
2022/09/21 10:46:11 [I] Migrator: exec migration id: create index IDX_data_source_org_id - v2
2022/09/21 10:46:11 [I] Migrator: exec migration id: create index UQE_data_source_org_id_name - v2
2022/09/21 10:46:11 [I] Migrator: exec migration id: copy data_source v1 to v2
2022/09/21 10:46:11 [I] Migrator: exec migration id: Drop old table data_source_v1 #2
2022/09/21 10:46:11 [I] Migrator: exec migration id: Add column with_credentials
2022/09/21 10:46:11 [I] Migrator: exec migration id: create api_key table
2022/09/21 10:46:11 [I] Migrator: exec migration id: add index api_key.account_id
2022/09/21 10:46:11 [I] Migrator: exec migration id: add index api_key.key
2022/09/21 10:46:11 [I] Migrator: exec migration id: add index api_key.account_id_name
2022/09/21 10:46:11 [I] Migrator: exec migration id: drop index IDX_api_key_account_id - v1
2022/09/21 10:46:11 [I] Migrator: exec migration id: drop index UQE_api_key_key - v1
2022/09/21 10:46:11 [I] Migrator: exec migration id: drop index UQE_api_key_account_id_name - v1
2022/09/21 10:46:11 [I] Migrator: exec migration id: Rename table api_key to api_key_v1 - v1
2022/09/21 10:46:11 [I] Migrator: exec migration id: create api_key table v2
2022/09/21 10:46:11 [I] Migrator: exec migration id: create index IDX_api_key_org_id - v2
2022/09/21 10:46:11 [I] Migrator: exec migration id: create index UQE_api_key_key - v2
2022/09/21 10:46:11 [I] Migrator: exec migration id: create index UQE_api_key_org_id_name - v2
2022/09/21 10:46:11 [I] Migrator: exec migration id: copy api_key v1 to v2
2022/09/21 10:46:11 [I] Migrator: exec migration id: Drop old table api_key_v1
2022/09/21 10:46:11 [I] Migrator: exec migration id: create dashboard_snapshot table v4
2022/09/21 10:46:11 [I] Migrator: exec migration id: drop table dashboard_snapshot_v4 #1
2022/09/21 10:46:11 [I] Migrator: exec migration id: create dashboard_snapshot table v5 #2
2022/09/21 10:46:11 [I] Migrator: exec migration id: create index UQE_dashboard_snapshot_key - v5
2022/09/21 10:46:11 [I] Migrator: exec migration id: create index UQE_dashboard_snapshot_delete_key - v5
2022/09/21 10:46:11 [I] Migrator: exec migration id: create index IDX_dashboard_snapshot_user_id - v5
2022/09/21 10:46:11 [I] Migrator: exec migration id: alter dashboard_snapshot to mediumtext v2
2022/09/21 10:46:11 [I] Migrator: exec migration id: create quota table v1
2022/09/21 10:46:11 [I] Migrator: exec migration id: create index UQE_quota_org_id_user_id_target - v1
2022/09/21 10:46:11 [I] Created default admin user: admin
2022/09/21 10:46:11 [I] Listen: http://0.0.0.0:3000
/usr/local/bin/locust -f gameserver_allocation.py --host=http://127.0.0.1:8001
./run: line 17: /usr/local/bin/locust: No such file or directory
/usr/local/bin/locust -f gameserver_allocation.py --host=http://127.0.0.1:8001
./run: line 17: /usr/local/bin/locust: No such file or directory
/usr/local/bin/locust -f gameserver_allocation.py --host=http://127.0.0.1:8001
./run: line 17: /usr/local/bin/locust: No such file or directory`

**Anything else we need to know?**:

**Environment**: WINDOWS
- Agones version: 
- Kubernetes version (use `kubectl version`):{
  "clientVersion": {
    "major": "1",
    "minor": "25",
    "gitVersion": "v1.25.0",
    "gitCommit": "a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2",
    "gitTreeState": "clean",
    "buildDate": "2022-08-23T17:44:59Z",
    "goVersion": "go1.19",
    "compiler": "gc",
    "platform": "windows/amd64"
  },
  "kustomizeVersion": "v4.5.7",
  "serverVersion": {
    "major": "1",
    "minor": "22+",
    "gitVersion": "v1.22.11-eks-18ef993",
    "gitCommit": "b9628d6d3867ffd84c704af0befd31c7451cdc37",
    "gitTreeState": "clean",
    "buildDate": "2022-07-06T18:06:23Z",
    "goVersion": "go1.16.15",
    "compiler": "gc",
    "platform": "linux/amd64"
  }
}
- Cloud provider or hardware configuration: AWS
- Install method (yaml/helm): yaml
- Troubleshooting guide log(s):
- Others:

### PR DESCRIPTION
**Pull request by mangalpalli**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, press enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking
>/kind bug

/kind cleanup
> /kind documentation
> /kind feature
> /kind hotfix

**What this PR does / Why we need it**:

After building container and running this command "docker run --rm --network="host" -e "LOCUST_FILE=gameserver_allocation.py" -e "TARGET_HOST=http://127.0.0.1:8001" -p 8089:8089 locust-files:latest", it is showing "missing /usr/local/bin/locust".

LOCUST files are no longer updated, and had to be removed.

Removed all the content related to LOCUST files.

**Which issue(s) this PR fixes**:

Closes #2744

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by gongmax** [comment]
Do we want to remove those four files under the allocation folder? Looks like this test is not using LOCUST?

**Comment by markmandel** [comment]
My original thought was to move all the contents of https://github.com/mangalpalli/agones/tree/issue-2744/test/load/allocation/grpc up to https://github.com/mangalpalli/agones/tree/issue-2744/test/load - but now I'm not sure. 

Maybe it should all be moved to https://github.com/mangalpalli/agones/tree/issue-2744/test/load/allocation (remove the `grpc` part). Do we think we'll have more types of load tests?

What do we think? @roberthbailey ?

**Comment by markmandel** [comment]
That's a new flake:

```
{"message":"Wait for cache sync","severity":"info","time":"2022-10-28T17:36:00.749700994Z"}
{"message":"unable to calculate 'Creating' state duration of 'd9rnhlh7tx' GameServer","severity":"warning","source":"*metrics.Controller","time":"2022-10-28T17:36:00.852651182Z"}
{"message":"unable to calculate 'Ready' state duration of 'd9rnhlh7tx' GameServer","severity":"warning","source":"*metrics.Controller","time":"2022-10-28T17:36:01.853235532Z"}
--- FAIL: TestControllerGameServerCount (2.11s)
    controller_test.go:76: 
        	Error Trace:	controller_test.go:76
        	            				controller_test.go:146
        	Error:      	Not equal: 
        	            	expected: 3
        	            	actual  : 4
        	Test:       	TestControllerGameServerCount
        	Messages:   	number of timeseries does not match under metric: gameservers_count
```

**Comment by roberthbailey** [comment]
> My original thought was to move all the contents of https://github.com/mangalpalli/agones/tree/issue-2744/test/load/allocation/grpc up to https://github.com/mangalpalli/agones/tree/issue-2744/test/load - but now I'm not sure.

I think we all agree that we should remove the files under https://github.com/googleforgames/agones/tree/main/test/load/locust-files as well as `run.sh` and `Dockerfile` under https://github.com/googleforgames/agones/tree/main/test/load. I think we should leave a `README.md` in `test/load` though. The first sentence from https://github.com/googleforgames/agones/blob/main/test/load/README.md is really good and seems like it should remain, but the rest of the file describes Locust configuration and can be removed. 

> Maybe it should all be moved to https://github.com/mangalpalli/agones/tree/issue-2744/test/load/allocation (remove the `grpc` part). Do we think we'll have more types of load tests?
> 
> What do we think? @roberthbailey ?


The only real difference between https://github.com/googleforgames/agones/blob/main/test/load/allocation/allocationload.go and https://github.com/googleforgames/agones/blob/main/test/load/allocation/grpc/allocationload.go is the type of request that they create and how they connect. Otherwise, the logic is basically the same. It wouldn't be too difficult to combine them into a single file that could connect either way (depending on command line args). 

That being said, we have only really run the grpc version in recent memory. I don't know if anyone else is using the non-grpc version. But I would be ok removing it and only running load tests using the grpc client for now and if we want to extend it to also connect via the k8s api then we can extend that client rather than forking it. In that scenario we would remove the 4 files in https://github.com/googleforgames/agones/tree/main/test/load/allocation and promote the 11 files in https://github.com/googleforgames/agones/tree/main/test/load/allocation/grpc up the directory tree. 

Given that the other load test directories are mostly a distraction, I agree with your original suggestion of moving the contents of the gprc allocation load test into `test/load` which will clean things up significantly. If we change our mind later, we can always recover the old files from git.

**Comment by markmandel** [comment]
> Given that the other load test directories are mostly a distraction, I agree with your original suggestion of moving the contents of the gprc allocation load test into test/load which will clean things up significantly. If we change our mind later, we can always recover the old files from git.

That sounds good to me too. I agree with everything above 👍🏻 

@mangalpalli does that make sense?

**Comment by mangalpalli** [comment]
@markmandel aligned with the discussion. Just one thing, do we still keep directory structure  as 
**test/load/allocation/grpc/files** or we move all the files under grpc as **test/load/files**?

**Comment by markmandel** [comment]
The directory structure should be `test/load/allocation/` once complete.

With a README in `test/load` and the rest of the files in `test/load/allocation/`

**Comment by mangalpalli** [comment]
Hi, Just created a new PR- https://github.com/googleforgames/agones/pull/2784 as the file directory structure had to be changed.

**Comment by mangalpalli** [comment]
I though it would be easier as I had to revert the directory structure on existing branch.

**Pull request closed without merging**
