### PR TITLE
adding linux and darwin arm build steps

### PR DESCRIPTION
**Pull request by johnpekcan**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, press enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking
> /kind bug
> /kind cleanup
> /kind documentation

/kind feature

> /kind hotfix

**What this PR does / Why we need it**:
attempting to add makefile targets for darwin and linux arm64 binaries and containers

**Which issue(s) this PR fixes**:
https://github.com/googleforgames/agones/issues/2216

Closes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by markmandel** [comment]
erp... :(

```
# Windows image builds must be directed to a specific buildx context.
# The default context does not support building cross platform images.
DOCKER_CLI_EXPERIMENTAL=enabled docker buildx create --name=windows-builder --use
/usr/bin/make ensure-image IMAGE_TAG=agones-build:87b1c4da6d BUILD_TARGET=build-build-image
make[1]: Entering directory '/workspace/build'
"--platform" is only supported on a Docker daemon with experimental features enabled
"--platform" is only supported on a Docker daemon with experimental features enabled
make: *** [Makefile:374: build-required-src-dist] Error 1
make: *** Waiting for unfinished jobs....
make: *** [Makefile:370: build-licenses] Error 1
"--platform" is only supported on a Docker daemon with experimental features enabled
make[1]: Leaving directory '/workspace/build'
windows-builder
```

Is there an easy way to ensure those are turned on?

**Comment by johnpekcan** [comment]
works on my machine 🤣 
i see the windows containers builds use `DOCKER_CLI_EXPERIMENTAL=enabled` so I sprinkled some of that in there.

**Comment by markmandel** [comment]
> are the windows containers (prior to this pr) being built successfully? 

Yep, they've been building for a while now (AFAIK)

**Comment by markmandel** [comment]
Oh fun thought I had - what version of Docker are you running? I can likely go check to see what we are running on Cloud Build, and that might also give us some answers.

**Comment by johnpekcan** [comment]
Looks like I'm running `Docker version 20.10.11, build dea9396`

**Comment by johnpekcan** [comment]
happy to close this if https://github.com/googleforgames/agones/pull/2490/files is the preferred route 😇

**Comment by Ludea** [comment]
> happy to close this if #2490 is the preferred route 😇

I do my PR following yours 😅
I need arm images, not only binaries 

But seems CI also fail 😒

**Comment by markmandel** [comment]
Restarting the builds with updated up to main. @Ludea , @johnpekcan which is the best PR that we should move forward with?

**Comment by markmandel** [comment]
I'm going to focus on #2490 , since it seems like it's further along, but please feel free to correct me if I'm wrong.

**Comment by johnpekcan** [comment]
No problem @markmandel , happy to close mine out. Thanks for getting this going @Ludea !

**Pull request closed without merging**
