### PR TITLE
Docsy

### PR DESCRIPTION
**Pull request by Kalaiselvi84**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, press enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking
> /kind bug
> /kind cleanup
> /kind documentation
> /kind feature
> /kind hotfix
> /kind release

**What this PR does / Why we need it**:

**Which issue(s) this PR fixes**:

Closes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by Kalaiselvi84** [comment]
@markmandel 
I am trying with Bootstrap because Docsy uses it for layout work.

**Steps followed to `Migrate to Hugo Module`**

```
cp go.mod go.mod.backup
cp go.sum go.sum.backup
rm go.mod go.sum
hugo mod init github.com/agones/agones/site
hugo mod get github.com/google/docsy@v0.7.1
sed -i '/theme = \["docsy"\]/d' config.toml
cat >> config.toml <<EOL
[module]
proxy = "direct"
[[module.imports]]
path = "github.com/google/docsy"
[[module.imports]]
path = "github.com/google/docsy/dependencies"
EOL
hugo server
```
All the above commands were successful and there were no issues.

**Installed the latest version of Bootstrap and followed the steps below:**
```
npm init -y
npm install bootstrap@5.3.2
site/themes/docsy/layouts/partials/head-css.html:  <link rel="stylesheet" href="node_modules/bootstrap/dist/css/bootstrap.min.css">
site/themes/docsy/layouts/partials/head.html:  <script src="node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
```

`hugo, site-server, site-static, hugo server, and hugo-test` targets are passing. Haven't had success with the alignment of the website. Am I adding the links for CSS and JS to the correct file?

**Comment by markmandel** [comment]
I'm fairly sure that Docsy already has bootstrap embedded. Have you found that to not be the case?

**Comment by Kalaiselvi84** [comment]
> I'm fairly sure that Docsy already has bootstrap embedded. Have you found that to not be the case?

Since we are facing issues with the layouts and styles, I tried adding it separately, but with no luck. I'm not sure what else to try. Will close this PR.

**Comment by markmandel** [comment]
> Since we are facing issues with the layouts and styles, I tried adding it separately, but with no luck. I'm not sure what else to try. Will close this PR.

Don't close the PR, I'll take a look.

**Comment by Kalaiselvi84** [comment]
Closing this PR, since the task has been completed in another PR: https://github.com/googleforgames/agones/pull/3417

**Pull request closed without merging**
