### PR TITLE
Support for Unity Alpha SDK

### PR DESCRIPTION
**Pull request by MaxHayman**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, press enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking
> /kind bug
> /kind cleanup
> /kind documentation

/kind feature
> /kind hotfix

**What this PR does / Why we need it**:

Currently the Unity SDK does not support the player tracking features

https://github.com/googleforgames/agones/issues/1905
https://github.com/googleforgames/agones/issues/1677

**Which issue(s) this PR fixes**:

Closes #

**Special notes for your reviewer**:

Using AgonesAlphaSdk instead of AgonesSdk will give you access to the new alpha features. Made some methods protected to I could avoid disrupting as much of the existing code as possible.

### CODE REVIEW

**Comment by MaxHayman** [comment]
/assign @markmandel

Hope you don't me assigning you. You seem to have reviewed the last few unity sdk changes.

**Comment by markmandel** [comment]
Thanks for this - dragging in a few people who know Unity better from Slack.

Quick review though - we will need some docs please 😄 

Have a look at:
https://agones.dev/site/docs/guides/client-sdks/unity/

And also https://agones.dev/site/docs/contribute/ for details on how to edit the docs, and make sure new features only show up on release.

**Comment by roberthbailey** [comment]
@MaxHayman - The next release is in a week. Do you think you'll have time to add some docs so we can get this merged for the release?

**Comment by MaxHayman** [comment]
Sorry had been quite busy. Is this okay?

**Comment by markmandel** [comment]
> Sorry had been quite busy. Is this okay? I wasn't sure what to put for the release gate of the content as I wasn't sure if it would make it in to the next release.
> 

All good! We all hit busy times 👍🏻 

Yeah, we might need to skip this for this release, since the above isn't in your PR, but the overall structure looks good.

Only thing I can think of without it getting built - often you'll need to duplicate the entire table between `feature` publish and expiry shortcodes, since doing it in the middle messes up the markdown parsing.

But give it go on the PR, and we can preview and adjust as needed.

**Comment by MaxHayman** [comment]
> > Sorry had been quite busy. Is this okay? I wasn't sure what to put for the release gate of the content as I wasn't sure if it would make it in to the next release.
> 
> All good! We all hit busy times 👍🏻
> 
> Yeah, we might need to skip this for this release, since the above isn't in your PR, but the overall structure looks good.
> 
> Only thing I can think of without it getting built - often you'll need to duplicate the entire table between `feature` publish and expiry shortcodes, since doing it in the middle messes up the markdown parsing.
> 
> But give it go on the PR, and we can preview and adjust as needed.

Applied and wrapped it around the whole table!

**Comment by markmandel** [comment]
Took me a minute to work out what the issue was the with the shortcode formatting - so I sent you a PR to your PR 😄 it's a bit of a hacky, fix, but it works.

https://github.com/FreejamGames/agones/pull/1

Also noted moving everything to 1.25.0.

I can't update your branch to main (because you are on a org repo, it's a weird github rule - unless you can find a way to give me rights to add commits to your branch) - if you could merge my PR, rebase against main, I'm happy to approve and merge.

image

(I thought about adding the rebase to the PR, but I figured that would end up quite confusing).

Thanks for your patience on this one!

**Review by markmandel — APPROVED** [review]

**Comment by markmandel** [comment]
Looks perfect - if you can rebase against `main` please, I can merge this in 👍🏻 

Context: https://github.com/orgs/github-community/discussions/5634

**Pull request merged**
