### PR TITLE
Update examples/autoscaler-webook dependencies

### PR DESCRIPTION
**Pull request by markmandel**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, press enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking
> /kind bug

/kind cleanup

> /kind documentation
> /kind feature
> /kind hotfix
> /kind release

**What this PR does / Why we need it**:

This resolve the dependabot issue (#3421) with dependencies, and also updates the example image version.

**Which issue(s) this PR fixes**:

Resolving issue with #3421 

**Special notes for your reviewer**:

This will fail on first run, since I haven't updated the prod image. If we see no issues with the PR, then I'll push the image up and rerun.

Also this was the example that IntelliJ was always updating, so it'll stop me having to work around not committing the change 😃

### CODE REVIEW

**Review by gongmax — APPROVED** [review]
LGTM

**Comment by markmandel** [comment]
Also a weird flake

```
Already have image: e2e-runner
PlayerAllocationFilter=true&PlayerTracking=true&ResetMetricsOnDelete=false&PodHostname=false&SplitControllerAndExtensions=false&FleetAllocationOverflow=true&CountsAndLists=true&Example=true
Fetching cluster endpoint and auth data.
ERROR: (gcloud.container.clusters.get-credentials) ResponseError: code=404, message=Not found: projects/agones-images/locations/us-central1/clusters/standard-e2e-test-cluster-1-25.
No cluster named 'standard-e2e-test-cluster-1-25' in agones-images.
```

**Comment by gongmax** [comment]
> Also a weird flake
> 
> ```
> Already have image: e2e-runner
> PlayerAllocationFilter=true&PlayerTracking=true&ResetMetricsOnDelete=false&PodHostname=false&SplitControllerAndExtensions=false&FleetAllocationOverflow=true&CountsAndLists=true&Example=true
> Fetching cluster endpoint and auth data.
> ERROR: (gcloud.container.clusters.get-credentials) ResponseError: code=404, message=Not found: projects/agones-images/locations/us-central1/clusters/standard-e2e-test-cluster-1-25.
> No cluster named 'standard-e2e-test-cluster-1-25' in agones-images.
> ```

Kalai was recreating the test clusters last Friday that introduced this flake

**Comment by markmandel** [comment]
Aha, I wondered.

**Pull request merged**
