### PR TITLE
Run all SDK conformance tests in parallel

### PR DESCRIPTION
**Pull request by aLekSer**
Run SDK conformance tests for different languages on different ports.
Cloud Build updated to decrease overall execution time.

### CODE REVIEW

**Comment by aLekSer** [comment]
Previous duration of Cloud Build is about 27 minutes, let's compare if this give us an improvement in timings.

**Comment by roberthbailey** [comment]
The most recent cloudbuild run for this PR seems to have taken 29 minutes... so I'm not sure that this actually speeds things up. Can you tell if the SDK conformance tests are actually running in parallel?

**Comment by aLekSer** [comment]
> The most recent cloudbuild run for this PR seems to have taken 29 minutes... so I'm not sure that this actually speeds things up. Can you tell if the SDK conformance tests are actually running in parallel?

Good question. Tests run in parallel, according to logs, but resulting times per conformance test step become bigger. As from logs they start at the same time:
```
/usr/bin/make run-sdk-conformance-test SDK_FOLDER=node GRPC_PORT=9002 HTTP_PORT=9102
/usr/bin/make run-sdk-conformance-test SDK_FOLDER=go GRPC_PORT=9001 HTTP_PORT=9101
/usr/bin/make run-sdk-conformance-test SDK_FOLDER=rust
make[1]: Entering directory '/workspace/build'
make[1]: Entering directory '/workspace/build'
make[1]: Entering directory '/workspace/build'
/usr/bin/make ensure-image IMAGE_TAG=agones-build-sdk-node:0db2a4ad54 BUILD_TARGET=build-build-sdk-image SDK_FOLDER=node
/usr/bin/make ensure-image IMAGE_TAG=agones-build-sdk-rust:ba39bb8569 BUILD_TARGET=build-build-sdk-image SDK_FOLDER=rust
/usr/bin/make ensure-image IMAGE_TAG=agones-build-sdk-go:4861e7b00a BUILD_TARGET=build-build-sdk-image SDK_FOLDER=go
```

Today I was investigating why total time was not improved. Found only one difference by comparing the logs. We have new error from Node JS test:
```
/go/src/agones.dev/agones/sdks/nodejs/src/agonesSDK.js:139
throw error;
^

Error: 2 UNKNOWN: Stream removed
at Object.exports.createStatusError (/go/src/agones.dev/agones/sdks/nodejs/node_modules/grpc/src/common.js:91:15)
at ClientReadableStream._emitStatusIfDone (/go/src/agones.dev/agones/sdks/nodejs/node_modules/grpc/src/client.js:233:26)
at ClientReadableStream._receiveStatus (/go/src/agones.dev/agones/sdks/nodejs/node_modules/grpc/src/client.js:211:8)
at Object.onReceiveStatus 
...
npm ERR! code ELIFECYCLE
npm ERR! A complete log of this run can be found in:
npm ERR! /root/.npm/_logs/2019-10-14T20_43_35_494Z-debug.log
```
So I think it would be helpful to gather all timings per each test, to find which test cause that.

Note that adding `gsutil -m cp` step was reduced by this PR twice from ~ 6 to 3 minutes.

**Comment by roberthbailey** [comment]
This may be a silly question, but if the nodejs test is throwing an error, shouldn't that be causing the conformance test to fail?

**Comment by aLekSer** [comment]
@roberthbailey I had the same question, but the error was caused by closed connection from SDK server. I think we could enhance the test and close the test before local SDK server.

**Comment by aLekSer** [comment]
Some issue with E2E test:
```
Step #20: time="2019-10-16 16:29:39.887" level=info msg="load balancer" svc="&Service{ObjectMeta:k8s_io_apimachinery_pkg_apis_meta_v1.ObjectMeta{Name:agones-ping-http-service,GenerateName:,Namespace:agones-system,SelfLink:/api/v1/namespaces/agones-system/services/agones-ping-http-service,UID:1c585168-e4bc-11e9-8d1d-42010a8a0067,ResourceVersion:38657447,Generation:0,CreationTimestamp:2019-10-02 02:26:59 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{app: agones,chart: agones-1.1.0,component: ping,heritage: Tiller,release: agones,},Annotations:map[string]string{},OwnerReferences:[],Finalizers:[],ClusterName:,Initializers:nil,},Spec:ServiceSpec{Ports:[{http TCP 80 {0 8080 } 30406}],Selector:map[string]string{agones.dev/role: ping,},ClusterIP:10.43.254.122,Type:LoadBalancer,ExternalIPs:[],SessionAffinity:None,LoadBalancerIP:,LoadBalancerSourceRanges:[],ExternalName:,ExternalTrafficPolicy:Cluster,HealthCheckNodePort:0,PublishNotReadyAddresses:false,SessionAffinityConfig:nil,},Status:ServiceStatus{LoadBalancer:LoadBalancerStatus{Ingress:[{34.83.160.73 }],},},}"
Step #20: time="2019-10-16 16:29:39.803" level=info msg="starting scale up/down test" deadline="2019-10-16 16:30:39.720991639 +0000 UTC m=+191.778219734" fleetCount=2 fleetSize=10 repeatCount=3
Step #20: panic.go:406: Namespace allocator-a-0b35203a-f032-11e9-81ec-0242c0a80a04 is deleted
Step #20: panic.go:406: Namespace allocator-b-0b630685-f032-11e9-81ec-0242c0a80a04 is deleted
Step #20: error:invalid character 'a' looking for beginning of value
Step #20:
Step #20: allocator_test.go:219: failed to unmarshall response body: an error on the server ("Post https://35.247.11.105/v1alpha1/gameserverallocation: dial tcp 35.247.11.105:443: connect: no route to host") has prevented the request from succeeding (post gameserverallocations.allocation.agones.dev)
Step #20: Test: TestAllocatorCrossNamespace
Step #20: Error: Expected nil, but got: &json.SyntaxError{msg:"invalid character 'a' looking for beginning of value", Offset:1}
Step #20: Error Trace: allocator_test.go:218
Step #20: allocator_test.go:218:
Step #20: Test: TestAllocatorCrossNamespace
Step #20: actual : 500
Step #20: expected: 200
Step #20: Error: Not equal:
Step #20: allocator_test.go:189
Step #20: wait.go:241
Step #20: wait.go:245
Step #20: Error Trace: allocator_test.go:203
```

**Pull request merged**
