### PR TITLE
Upgrade `terraform-aws-eks` to `v17.22.0`

### PR DESCRIPTION
**Pull request by mvlabat**
**What type of PR is this?**
/kind bug

**What this PR does / Why we need it**:

Without this change, validation of [the EKS example](https://github.com/googleforgames/agones/blob/fc6e7872e58ffbf7bf700d8e76e085ce4ce74e03/examples/terraform-submodules/eks/module.tf) fails on Terraform v1.0.9 with the following error:
```
╷
│ Error: Error in function call
│
│   on .terraform/modules/eks_cluster.eks/outputs.tf line 3, in output "cluster_id":
│    3:   value       = element(concat(aws_eks_cluster.this.*.id, list("")), 0)
│
│ Call to function "list" failed: the "list" function was deprecated in Terraform v0.12 and is no longer available; use tolist([ ... ]) syntax to write a literal list.
╵
```
(there are 4 more instances of it)

I hope this upgrade doesn't introduce any breaking changes. So far, I've simply got the example to validate successfully.

### CODE REVIEW

**Comment by mvlabat** [comment]
@roberthbailey do you believe these fails are caused by my changes? Is there anything I can help with?

**Comment by markmandel** [comment]
> @roberthbailey do you believe these fails are caused by my changes? Is there anything I can help with?

Not your fault. We recently upgraded everything to kubernetes 1.21 and for some reason it's causing all kinds of flakes in our tests. We're digging through it to find the root cause.

**Comment by roberthbailey** [comment]
```
--- FAIL: TestGameServerReadyAllocateReady (17.79s)
    gameserver_test.go:510: 
        	Error Trace:	gameserver_test.go:510
        	Error:      	Received unexpected error:
        	            	read udp 192.168.10.6:33624->35.227.187.145:7069: read: connection refused
        	            	could not read response from the GameServer
        	            	agones.dev/agones/test/e2e/framework.SendUDP
        	            		/go/src/agones.dev/agones/test/e2e/framework/framework.go:530
        	            	agones.dev/agones/test/e2e/framework.SendGameServerUDPToPort
        	            		/go/src/agones.dev/agones/test/e2e/framework/framework.go:496
        	            	agones.dev/agones/test/e2e/framework.SendGameServerUDP
        	            		/go/src/agones.dev/agones/test/e2e/framework/framework.go:477
        	            	agones.dev/agones/test/e2e.TestGameServerReadyAllocateReady
        	            		/go/src/agones.dev/agones/test/e2e/gameserver_test.go:509
        	            	testing.tRunner
        	            		/usr/local/go/src/testing/testing.go:1259
        	            	runtime.goexit
        	            		/usr/local/go/src/runtime/asm_amd64.s:1581
        	Test:       	TestGameServerReadyAllocateReady
        	Messages:   	Could not message GameServer
```

**Comment by roberthbailey** [comment]
```
--- FAIL: TestGameServerReserve (47.60s)
    gameserver_test.go:626: 
        	Error Trace:	gameserver_test.go:626
        	Error:      	Could not message GameServer
        	Test:       	TestGameServerReserve
        	Messages:   	could not read response from the GameServer: read udp 192.168.10.7:41539->35.227.187.145:7924: i/o timeout
```

**Pull request merged**
