### PR TITLE
Configure kubernetes provider for eks module

### PR DESCRIPTION
**Pull request by mvlabat**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, press enter to put that in a new line, and remove leading whitespace from that line:

/kind bug

**What this PR does / Why we need it**:
I was going through https://agones.dev/site/docs/installation/terraform/eks/ documentation. After doing `terraform apply`, I've got the following error:
```
module.eks_cluster.module.eks.kubernetes_config_map.aws_auth[0]: Creating...
╷
│ Error: Post "http://localhost/api/v1/namespaces/kube-system/configmaps": dial tcp [::1]:80: connect: connection refused
│
│   with module.eks_cluster.module.eks.kubernetes_config_map.aws_auth[0],
│   on .terraform/modules/eks_cluster.eks/aws_auth.tf line 63, in resource "kubernetes_config_map" "aws_auth":
│   63: resource "kubernetes_config_map" "aws_auth" {
│
╵
```

After some googling, I stumbled upon `terraform-aws-eks` [usage example](https://github.com/terraform-aws-modules/terraform-aws-eks#usage-example), which suggested using the following config:

```
data "aws_eks_cluster" "eks" {
  name = module.eks.cluster_id
}

data "aws_eks_cluster_auth" "eks" {
  name = module.eks.cluster_id
}

provider "kubernetes" {
  host                   = data.aws_eks_cluster.eks.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.eks.certificate_authority[0].data)
  token                  = data.aws_eks_cluster_auth.eks.token
}
```

After patching the `eks` module, `terraform apply` command worked.

### CODE REVIEW

**Comment by roberthbailey** [comment]
Interesting. Did you run `terraform apply` in the `install/terraform/modules/eks/` directory or in the `examples/terraform-submodules/eks/` directory? The terraform configs in the examples directory looks like it already sets up the cluster auth: https://github.com/googleforgames/agones/blob/main/examples/terraform-submodules/eks/module.tf#L96-L101

**Comment by mvlabat** [comment]
@roberthbailey in neither. I just copied `examples/terraform-submodules/eks/module.tf` file to my project directory (the documentation suggest copying it into a separate directory), and there was nothing else Terraform related there.

**Comment by mvlabat** [comment]
@roberthbailey who should be a consumer of the `eks` example module?

I started learning terraform quite recently so my knowledge might be inaccurate, but as far as I understand, it's impossible to pass configuration to called modules via outputs (`install/terraform/modules/eks/eks.tf` is a called module in the example), but it's rather to allow a calling module to read exported variables of a module it calls.

If I haven't missed anything, the documentation assumes that https://github.com/googleforgames/agones/blob/release-1.18.0/examples/terraform-submodules/eks/module.tf will be used as a root module. So I don't see quite understand what role the outputs play exactly.

**Comment by roberthbailey** [comment]
I'm not sure I fully understand why this works for you, but I don't see any downside and I don't have an easy way to test terraform on EKS myself so I'm going to merge this.

**Review by roberthbailey — APPROVED** [review]

**Pull request merged**
