### PR TITLE
Upgrade from Debian Bullseye to Bookworm for cpp-simple-server

### PR DESCRIPTION
**Pull request by Kalaiselvi84**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, press enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking
> /kind bug

/kind cleanup
> /kind documentation
> /kind feature
> /kind hotfix
> /kind release

**What this PR does / Why we need it**:

**Which issue(s) this PR fixes**:

Work on #3570 

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by Kalaiselvi84** [comment]
Failed log to push `cpp-simple-server` image - [https://console.cloud.google.com/cloud-build/builds/daf15787-603a-451f-b7f5-24e445bc8c61?project=258182270954](https://pantheon.corp.google.com/cloud-build/builds;region=global/daf15787-603a-451f-b7f5-24e445bc8c61?mods=logs_tg_prod&project=agones-mangalpalli)

I'm unable to share the log through paste or gist, but you can view it directly as you have owner access to my project. Could you please take a look at the log and advise on the next steps?

**Review by gongmax — APPROVED** [review]

**Comment by markmandel** [comment]
I can replicate this issue - seems related to: https://github.com/protocolbuffers/protobuf/issues/12439 -- not quite sure how to resolve.

**Comment by markmandel** [comment]
Okay, to make things more fun -- this is no longer working in any capacity. I can't build on `bullseye` either.. I don't think this is related to which debian version we are using.

**Comment by markmandel** [comment]
Just a heads up - I found a bunch of C++/CMake improvements while messing with this, so I might end up just taking this over (I think I can totally modernise the CMake script while I'm at it, which should hopefully also solve future issues as well).

**Comment by Kalaiselvi84** [comment]
I copy that. To resolve `Could NOT find utf8_range (missing: utf8_range_DIR) ` error, I attempted to install  `librust-utf8-ranges-dev` in the Dockerfile and explicitly set the  `utf8_range_DIR` variable explicitly but had no luck. Is it necessary to have the source code of [utf8_range](https://github.com/protocolbuffers/utf8_range)?

This link shows how to avoid the need for setting [utf8_range_DIR]
(https://chromium.googlesource.com/external/github.com/grpc/grpc/+/HEAD/test/distrib/cpp/run_distrib_test_cmake_pkgconfig.sh#76)

**Comment by markmandel** [comment]
I'm currently heading down this path - https://grpc.io/blog/cmake-improvements/

And it let's me delete a tonne of CMake code, and no longer have to be explicit about dependencies.

**Comment by markmandel** [comment]
....almost there, so I'll take this over. Going to close this one for now. Can ignore this for #3570 and I'll wrap this into the larger work of refactoring CMake integration.

**Pull request closed without merging**
