### PR TITLE
Allow fleet with empty Replicas

### LINKED ISSUE #1156: RollingUpdate shuts down all servers at once
**What happened**: I adjusted RollingUpdate settings to replace each Ready GameServer pod one by one using following configuration
```
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
```
But every time I deployed Fleet configuration with this setting it would instantly shut down all Ready servers and replace them with new version.

1) Deployed my yaml and ran `kubectl get gs` got following 
```
NAME                             STATE       ADDRESS      PORT   NODE                       AGE
lobby-server-odd-2vmld-2m6h9        Shutdown    34.89.86.    7442   gke-qa-default-pool-3943   39s
lobby-server-odd-2vmld-6mlms        Shutdown    35.246.21.   7812   gke-qa-default-pool-rkw7   39s
lobby-server-odd-2vmld-9n8z9        Shutdown    35.235.55.   7382   gke-qa-default-pool-hjgr   1m
lobby-server-odd-2vmld-c6wzw        Shutdown    35.235.55.   7104   gke-qa-default-pool-hjgr   39s
lobby-server-odd-2vmld-pjttg        Shutdown    35.235.55.   7294   gke-qa-default-pool-hjgr   39s
lobby-server-odd-2vmld-pxqqs        Shutdown    35.235.53.   7139   gke-qa-default-pool-1wwf   39s
lobby-server-odd-2vmld-rb755        Shutdown    34.89.86.    7912   gke-qa-default-pool-3943   39s
lobby-server-odd-2vmld-xqbdl        Shutdown    35.242.175   7098   gke-qa-default-pool-bhwl   39s
lobby-server-odd-2vmld-zrl4n        Shutdown    35.246.21.   7367   gke-qa-default-pool-rkw7   39s
lobby-server-odd-2vmld-zw448        Ready       35.246.21.   7027   gke-qa-default-pool-rkw7   39s
```

2) Refreshing
```
NAME                             STATE       ADDRESS      PORT   NODE                       AGE
lobby-server-odd-2vmld-zw448        Ready       35.246.21.   7027   gke-qa-default-pool-rkw7   57s
```

3) Refreshing
```
NAME                             STATE       ADDRESS      PORT   NODE                       AGE
lobby-server-odd-2vmld-666zz        Scheduled   34.89.86.    7053   gke-qa-default-pool-3943   4s
lobby-server-odd-2vmld-8fjvp        Scheduled   35.235.53.   7114   gke-qa-default-pool-1wwf   4s
lobby-server-odd-2vmld-chks8        Scheduled   35.242.175   7037   gke-qa-default-pool-bhwl   4s
lobby-server-odd-2vmld-mbqtd        Scheduled   35.235.55.   7255   gke-qa-default-pool-hjgr   4s
lobby-server-odd-2vmld-r9g4p        Scheduled   35.246.21.   7302   gke-qa-default-pool-rkw7   4s
lobby-server-odd-2vmld-t99p2        Scheduled   34.89.86.    7072   gke-qa-default-pool-3943   4s
lobby-server-odd-2vmld-vb9q5        Scheduled   35.235.55.   7561   gke-qa-default-pool-hjgr   4s
lobby-server-odd-2vmld-vkcz6        Scheduled   35.246.21.   7063   gke-qa-default-pool-rkw7   4s
lobby-server-odd-2vmld-x58sb        Scheduled   35.235.55.   7057   gke-qa-default-pool-hjgr   4s
lobby-server-odd-2vmld-zw448        Ready       35.246.21.   7027   gke-qa-default-pool-rkw7   1m
```

4) Refreshing
```
NAME                             STATE       ADDRESS      PORT   NODE                       AGE
lobby-server-odd-2vmld-666zz        Ready       34.89.86.    7053   gke-qa-default-pool-3943   11s
lobby-server-odd-2vmld-8fjvp        Ready       35.235.53.   7114   gke-qa-default-pool-1wwf   11s
lobby-server-odd-2vmld-chks8        Ready       35.242.175   7037   gke-qa-default-pool-bhwl   11s
lobby-server-odd-2vmld-mbqtd        Ready       35.235.55.   7255   gke-qa-default-pool-hjgr   11s
lobby-server-odd-2vmld-r9g4p        Ready       35.246.21.   7302   gke-qa-default-pool-rkw7   11s
lobby-server-odd-2vmld-t99p2        Ready       34.89.86.    7072   gke-qa-default-pool-3943   11s
lobby-server-odd-2vmld-vb9q5        Ready       35.235.55.   7561   gke-qa-default-pool-hjgr   11s
lobby-server-odd-2vmld-vkcz6        Ready       35.246.21.   7063   gke-qa-default-pool-rkw7   11s
lobby-server-odd-2vmld-x58sb        Ready       35.235.55.   7057   gke-qa-default-pool-hjgr   11s
lobby-server-odd-2vmld-zw448        Ready       35.246.21.   7027   gke-qa-default-pool-rkw7   1m
```

**What you expected to happen**: I expected them to be shut down and replaced one by one instead of all at once

**How to reproduce it (as minimally and precisely as possible)**:
1) Set RollingUpdate configuration to your fleet
```
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
```
And deploy it a few times, I could reproduce it using fleet-example.

**Environment**:
- Agones version: 1.0.0
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.11-dispatcher", GitCommit:"2e298c7e992f83f47af60cf4830b11c7370f6668", GitTreeState:"clean", BuildDate:"2019-09-19T22:20:12Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.10-gke.5", GitCommit:"e327dc5fe0418e41fa9f7c153ec14da34b61fe85", GitTreeState:"clean", BuildDate:"2019-08-23T23:09:28Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: GCP
- Install method (yaml/helm): helm

### PR DESCRIPTION
**Pull request by aLekSer**
Need this to allow FleetAutoScaler with Fleet RollingUpdate strategy.
Verified on GKE cluster.

E2E test added which is reproducing #1156 ticket.

Closes #1156 .

### CODE REVIEW

**Comment by markmandel** [comment]
Curious - what happens if you create a new fleet with no replicas count? Does it default to something that makes sense?

I'm wondering if we want to use the ValidationWebhook to make sure we have an initial replicas count on creation?  Might be overkill if the default makes sense.

**Comment by aLekSer** [comment]
>Curious - what happens if you create a new fleet with no replicas count? Does it default to something that makes sense?
It will contain no gameservers in that case. (was curious about this also)

>I'm wondering if we want to use the ValidationWebhook to make sure we have an initial replicas count on creation? Might be overkill if the default makes sense.
Current situation on Update the fleet we don't trigger fleet rescaling, which is good and RollingUpdate do its job. I will check if adding default values does not change fleet size on update and rescaling.

**Comment by aLekSer** [comment]
For replicaset, it defaults to 1:
`If you do not specify .spec.replicas, then it defaults to 1.`
https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/

**Comment by aLekSer** [comment]
The version pushed recently lacks `agones_crd_api_reference.html` will fix in a moment.

**Comment by aLekSer** [comment]
Strange enough, but first run of Cloud build with this `applyDefaults`:
```
	if f.Spec.Replicas == 0 {
		f.Spec.Replicas = 1
	}
```
Succeeded, I assume that it was fast enough that 0 gameservers was caught just before they was fired.

**Comment by aLekSer** [comment]
Same E2E error:
```
Step #21: time="2019-11-05 19:40:43.176" level=info msg="sending message" fields.msg=READY gs=udp-serverfj5q5 state=Unhealthy test=TestGameServerRestartBeforeReadyCrash
Step #21: --- FAIL: TestGameServerRestartBeforeReadyCrash (267.65s)
Step #21: gameserver_test.go:304:
```

**Comment by aLekSer** [comment]
The most recent test fail is covered by #1173 .

**Comment by aLekSer** [comment]
Strange E2E test failure:
```
Step #21: time="2019-11-15 09:23:55.338" level=info msg="fleet simple-fleet-ktsvh has 0/3 ready replicas"
Step #21: time="2019-11-15 09:23:55.938" level=info msg="fleet simple-fleet-5ct2w has 0/3 ready replicas"
Step #21: --- FAIL: TestGameServerRestartBeforeReadyCrash (90.30s)
Step #21: gameserver_test.go:233:
Step #21: Error Trace: gameserver_test.go:233
Step #21: Error: Received unexpected error:
Step #21: timed out waiting for the condition
Step #21: waiting for GameServer to be Scheduled default/udp-server8zhp9
Step #21: agones.dev/agones/test/e2e/framework.(*Framework).WaitForGameServerState
Step #21: /go/src/agones.dev/agones/test/e2e/framework/framework.go:131
Step #21: agones.dev/agones/test/e2e.TestGameServerRestartBeforeReadyCrash
Step #21: /go/src/agones.dev/agones/test/e2e/gameserver_test.go:232
Step #21: testing.tRunner
Step #21: /usr/local/go/src/testing/testing.go:865
Step #21: runtime.goexit
Step #21: /usr/local/go/src/runtime/asm_amd64.s:1337
Step #21: Test: TestGameServerRestartBeforeReadyCrash
Step #21: panic: runtime error: index out of range [recovered]
Step #21: panic: runtime error: index out of range
Step #21:
Step #21: goroutine 389 [running]:
Step #21: testing.tRunner.func1(0xc000373f00)
Step #21: /usr/local/go/src/testing/testing.go:830 +0x68a
Step #21: panic(0x196db20, 0x2974a20)
Step #21: /usr/local/go/src/runtime/panic.go:522 +0x1b5
Step #21: agones.dev/agones/test/e2e.TestGameServerRestartBeforeReadyCrash(0xc000373f00)
Step #21: /go/src/agones.dev/agones/test/e2e/gameserver_test.go:237 +0x1519
Step #21: testing.tRunner(0xc000373f00, 0x1b5e420)
Step #21: /usr/local/go/src/testing/testing.go:865 +0x164
Step #21: created by testing.(*T).Run
Step #21: /usr/local/go/src/testing/testing.go:916 +0x69a
Step #21: FAIL agones.dev/agones/test/e2e 513.174s
Step #21: Makefile:241: recipe for target 'test-e2e' failed
```

**Pull request merged**
