### PR TITLE
Upgrading grpc client and server on same version

### PR DESCRIPTION
**Pull request by SaitejaTamma**
Upgrading client and server on same version

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, press enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking
> /kind bug
> /kind cleanup
> /kind documentation
> /kind feature
> /kind hotfix

**What this PR does / Why we need it**:

**Which issue(s) this PR fixes**:

Closes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by markmandel** [comment]
`Could not message GameServer: read udp 192.168.10.6:53865->35.247.116.52:7706: i/o timeout`

Not sure what this flake is caused by.

**Comment by markmandel** [comment]
Question - we will need to recreate the base [build image](https://github.dev/googleforgames/agones/blob/bcecbdcb650888f12b907c2de9107dec330a0283/build/build-sdk-images/tool/base/Dockerfile) (to do that, change the text in the Dockerfile, increment the 'Bump' value). (as noted in #2362).

Was the plan to do this in this PR, or did you want to do it later?

**Comment by roberthbailey** [comment]
> Was the plan to do this in this PR, or did you want to do it later?

I'm going to cast my vote for doing it in this PR (so that we don't forget).

**Comment by SaitejaTamma** [comment]
will do that in this PR

**Comment by markmandel** [comment]
Making sure I'm extra clear: The Docker image will get recreated when our build tooling sees there is a change in the Dockerfile (it uses a SHA of the file as part of the tag), so to force recreating of the Dockerfile, make a change to the Dockerfile contents. As a convention we have that "Bump" value that we can increment as the change.

Does that make sense?

**Comment by roberthbailey** [comment]
This looks good to merge; @markmandel - anything else you are looking for?

**Comment by markmandel** [comment]
> This looks good to merge; @markmandel - anything else you are looking for?

Looking at my own issue (#1797) to see what I wrote 😄 

Looks good! This will tick off a few items in the list! Still a few items to go, but a good chunk of work moving us towards getting this wrapped up. (Also looks like it's not breaking anything either).

**Review by markmandel — APPROVED** [review]

**Pull request merged**
