### PR TITLE
Add port flag to example allocator-client

### PR DESCRIPTION
**Pull request by robbieheywood**
**What type of PR is this?**
/kind feature

**What this PR does / Why we need it**:
It adds the ability to specify `--port <port>` when using the allocator-client in examples/allocator-client. Without this, you can only use this allocator-client to hit allocators exposed on port 443. We expose our allocator through istio on a non-443 port, so this change is required to use the client to test our allocator.

**Which issue(s) this PR fixes**:

n/a - haven't raised a corresponding issue (but I'm happy to if required).

**Special notes for your reviewer**:
I've tested this by running `go run examples/allocator-client/main.go --ip <allocator-ip> --namespace game-scavengers --key tls.key --cert tls.crt --cacert ca.crt --port <port>` against a v1.6 allocator running in GKE, exposed on a non-443 port, and it succeeded. Let me know if you feel this needs any more testing.

### CODE REVIEW

**Comment by robbieheywood** [comment]
@googlebot I signed it!

**Comment by pooneh-m** [comment]
Thanks for the change @robbieheywood. Please also include the flag in the example here: https://github.com/googleforgames/agones/blob/master/site/content/en/docs/Advanced/allocator-service.md

**Comment by robbieheywood** [comment]
Thanks for the review @pooneh-m - hopefully this is now good to go 👍

**Comment by markmandel** [comment]
That's a new flaky one I haven't seen before:

```
time="2020-06-07 22:29:37.009" level=info msg="sent UDP packet" address="34.82.230.193:7320" test=TestGameServerUnhealthyAfterReadyCrash
time="2020-06-07 22:29:37.225" level=info msg="Waiting for states to match" awaitingState=Ready currentState=Unhealthy gs=udp-servernpl27
time="2020-06-07 22:29:38.221" level=info msg="Waiting for states to match" awaitingState=Ready currentState=Unhealthy gs=udp-servernpl27
time="2020-06-07 22:29:39.222" level=info msg="Waiting for states to match" awaitingState=Ready currentState=Unhealthy gs=udp-servernpl27
time="2020-06-07 22:29:40.222" level=info msg="Waiting for states to match" awaitingState=Ready currentState=Unhealthy gs=udp-servernpl2
```

Never gets to Ready and times out.

**Comment by pooneh-m** [comment]
Thanks @robbieheywood!

**Pull request merged**
