### PR TITLE
fleet-autoscaler validation fix

### LINKED ISSUE #1954: Fleet Autoscaler - Fleet name CRD Validation issue
**What happened**:

A fleet named `game-1.0.0.0` can be created, but the fleet auto scaler cannot reference the fleet name `game-1.0.0.0` because a validation error at the CRD level.

**What you expected to happen**:

Preferably, the auto scaler should be able to able to reference the fleet.

**How to reproduce it (as minimally and precisely as possible)**:

Create a fleet named `game-1.0.0.0` then attempt to create a simple auto scaler for that fleet.

**Anything else we need to know?**:

Section found by Daniel: https://github.com/googleforgames/agones/blob/master/install/helm/agones/templates/crds/fleetautoscaler.yaml#L54

**Environment**:
- Agones version: v1.11.0
- Kubernetes version (use `kubectl version`): 1.18
- Cloud provider or hardware configuration: Azure AKS
- Install method (yaml/helm): helm
- Troubleshooting guide log(s):

```
Error: failed to create resource: FleetAutoscaler.autoscaling.agones.dev "fleet-scaler" is invalid: spec.fleetName: Invalid value: "": spec.fleetName in body should match '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'
```

```
apiVersion: "autoscaling.agones.dev/v1"
kind: FleetAutoscaler
metadata:
  name: fleet-scaler
spec:
  fleetName: fleet-1.0.0.0
  policy:
    type: Buffer
    buffer:
      bufferSize: 2
      minReplicas: 1
      maxReplicas: 20
```

### PR DESCRIPTION
**Pull request by SaitejaTamma**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, press enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking

 /kind bug

> /kind cleanup
> /kind documentation
> /kind feature
> /kind hotfix

**What this PR does / Why we need it**:

**Which issue(s) this PR fixes**:

Closes #1954

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by markmandel** [comment]
Looks like the tests for `make gen-install`  (make test-install-yaml`) failed for some reason 🤔 

I'm seeing diffs here, and I'm not sure what they are, and they look like they are the same?

Curious - did you run `make gen-install` on your mac or on your linux machine?

**Comment by SaitejaTamma** [comment]
> Looks like the tests for `make gen-install` (`make test-install-yaml`) failed for some reason 🤔
> 
> I'm seeing diffs here, and I'm not sure what they are, and they look like they are the same?
> 
> Curious - did you run `make gen-install` on your mac or on your linux machine?

In cloud top

**Comment by SaitejaTamma** [comment]
> Huh. I have no idea 🤔 this doesn't happen when you run `make gen-install` for releases, right?

No never! while doing release

**Comment by markmandel** [comment]
Weeeeeird.

When in doubt, run it again? 🤷🏻

**Comment by SaitejaTamma** [comment]
closing this PR as we have new PR #2674

**Pull request closed without merging**
