### PR TITLE
Regenerate Kubernetes resource includes (ObjectMeta, PodTemplateSpec) for Kubernetes 1.20

### LINKED ISSUE #2186: Upgrade to Kubernetes 1.20
List of items to do for upgrading to 1.20:

- [x] Update terraform submodules
  - [x] GKE
  - [x] Azure
  - [x] EKS
- [x] Update prow cluster to use 1.20 (even though we aren't using it yet, we should keep it in sync)
  - [x] Recreate cluster with new scripts: `cd build/terraform/prow; terraform apply -var project=agones-images`
- [x] Update e2e cluster to run against 1.20
  - [x] Recreate cluster with new scripts: `cd build/terraform/e2e; terraform apply -var project=agones-images`
- [x] Update kubectl in dev tooling
  - [x] Update kubectl in `build/build-image/Dockerfile`
  - [x] Update kubectl in `build/e2e-image/Dockerfile`
- [x] Update documentation for creating clusters to 1.20
  - [x] Config.toml `supported_k8s` and related (do `dev_` before main)
- [x] Update the dev tooling to create 1.20 clusters
  - [x] Minikube
  - [x] Kind
- [x] Update client-go
- [x] Update CRD API reference 
  - [x] Update links to k8s documentation in site/assets/templates/crd-doc-config.json
  - [x] Regenerate crd api reference docs - `make gen-api-docs`
- [ ] Regenerate Kubernetes resource includes (e.g. ObjectMeta, PodTemplateSpec)
  - [ ] Start a cluster with `make gcloud-test-cluster`, uninstall agones using `helm uninstall`, and then run  `make gen-embedded-openapi` and `make gen-install`

### PR DESCRIPTION
**Pull request by roberthbailey**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, press enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking
> /kind bug
> /kind cleanup

/kind documentation

> /kind feature
> /kind hotfix

**What this PR does / Why we need it**: Updated output for `PodTemplateSpec`.

**Which issue(s) this PR fixes**:

Closes #2186

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by markmandel** [comment]
Yay. At least the script didn't fail this time 😁

**Comment by markmandel** [comment]
Need to gen index.yaml

```
sort /workspace/install/yaml/install.yaml > /tmp/agones-install/install.current.yaml.sorted
diff /tmp/agones-install/install.yaml.sorted /tmp/agones-install/install.current.yaml.sorted
1285c1285
<                                                     description: 'This field can be used to specify either: * An existing VolumeSnapshot object (snapshot.storage.k8s.io/VolumeSnapshot - Beta) * An existing PVC (PersistentVolumeClaim) * An existing custom resource/object that implements data population (Alpha) In order to use VolumeSnapshot object types, the appropriate feature gate must be enabled (VolumeSnapshotDataSource or AnyVolumeDataSource) If the provisioner or an external controller can support the specified data source, it will create a new volume based on the contents of the specified data source. If the specified data source is not supported, the volume will not be created and the failure will be reported as an event. In the future, we plan to support more data source types and the behavior of the provisioner may change.'
---
>                                                     description: 'This field can be used to specify either: * An existing VolumeSnapshot object (snapshot.storage.k8s.io/VolumeSnapshot) * An existing PVC (PersistentVolumeClaim) * An existing custom resource that implements data population (Alpha) In order to use custom resource types that implement data population, the AnyVolumeDataSource feature gate must be enabled. If the provisioner or an external controller can support the specified data source, it will create a new volume based on the contents of the specified data source.'
1547a1548,1550
>                                                     x-kubernetes-map-type: atomic
>                                                     x-kubernetes-map-type: atomic
>                                                     x-kubernetes-map-type: atomic
```

😄

**Comment by roberthbailey** [comment]
Weird error:
```
Step #17 - "tests": Html Test: Attempt 1
Step #17 - "tests": htmltest started at 09:17:36 on /tmp/website
Step #17 - "tests": ========================================================================
Step #17 - "tests": ✔✔✔ passed in 284.737688ms
Step #17 - "tests": tested 135 documents
Step #17 - "tests": make[1]: Leaving directory '/workspace/build'
Finished Step #17 - "tests"
ERROR
ERROR: build step 17 "make-docker" failed: step exited with non-zero status: 2
```

It looks like the tests passed but then that step exited with a non-zero code.

**Comment by roberthbailey** [comment]
> Need to gen index.yaml

Thanks. I was just running `make test` locally to try and track down the issue.

**Comment by roberthbailey** [comment]
That failed build was just a rebase, before adding the second commit.

**Comment by roberthbailey** [comment]
And that one is another actual failure...

**Comment by roberthbailey** [comment]
The latest error:

```
	helm upgrade --install --atomic --namespace=agones-system \
	--create-namespace \
	--set agones.image.tag=1.17.0-a5a3205,agones.image.registry=gcr.io/agones-images \
	--set agones.image.controller.pullPolicy="Always",agones.image.sdk.alwaysPull=true \
	--set agones.image.controller.pullSecret= \
	--set agones.ping.http.serviceType="LoadBalancer",agones.ping.udp.serviceType="LoadBalancer" \
	--set agones.allocator.http.serviceType="LoadBalancer" \
	--set agones.controller.logLevel="debug" \
	--set agones.crds.cleanupOnDelete=true \
	--set agones.featureGates="PlayerTracking=true&SDKWatchSendOnExecute=false&RollingUpdateOnReady=false&NodeExternalDNS=true&StateAllocationFilter=true&PlayerAllocationFilter=true" \
	--set agones.allocator.http.loadBalancerIP=34.105.5.159 \
	 \
	agones /go/src/agones.dev/agones/install/helm/agones/
Error: UPGRADE FAILED: another operation (install/upgrade/rollback) is in progress
```

**Comment by roberthbailey** [comment]
```
$ helm rollback -n agones-system agones
Rollback was a success! Happy Helming!
```

**Review by markmandel — APPROVED** [review]

**Pull request merged**
