### PR TITLE
documentation - add godot-sdk to third-party libraries-tools page

### PR DESCRIPTION
**Pull request by AndreMicheletti**
**What type of PR is this?**

/kind documentation

**What this PR does / Why we need it**:

Adds a new third-party sdk option for [Godot Engine](https://github.com/godotengine/godot)

### CODE REVIEW

**Comment by markmandel** [comment]
You can ignore this failure. (it's because of another build, don't worry). I'll kick it off again in a bit.

**Review by markmandel — COMMENTED** [review]
LGTM!

@roberthbailey any concerns with merging this during feature freeze?

Also, I assume that this should close #2062 ?

**Comment by thisisnotapril** [comment]
@AndreMicheletti we'd love to have you talk about the SDK in a future project meeting!

**Comment by AndreMicheletti** [comment]
> @AndreMicheletti we'd love to have you talk about the SDK in a future project meeting!

Sure thing! Thank you for the invitation.

**Comment by roberthbailey** [comment]
> @roberthbailey any concerns with merging this during feature freeze?

Nope. This doesn't affect our release.

**Review by roberthbailey — APPROVED** [review]

**Pull request merged**
