### PR TITLE
fixed Agones.Build.cs for #1303

### PR DESCRIPTION
**Pull request by dotcom**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking

/kind bug

> /kind cleanup
> /kind documentation
> /kind feature
> /kind hotfix

**What this PR does / Why we need it**:

Fixed a dependency on `HttpRetrySystem.h` in `AngonesHook.h`.
I tested it with UnrealEngine 4.25.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by dotcom** [comment]
@googlebot I signed it!

**Comment by markmandel** [comment]
Thanks for your submission!

Unfortunately @dotcom, it looks like you did this commit with your github email, not whichever email you used to sign the CLA.

You'll need to rebase your PR with the correct email address, and push force over the top.

**Comment by markmandel** [comment]
@drichardson , @WVerlaek who are our resident Unreal experts - this good for you? If so, happy to approve.

**Comment by markmandel** [comment]
Add @domgreen to that list too :smile:

**Comment by domgreen** [comment]
I would double check that it still works with `4.24` ... not sure why it was initially okay. The public is more permissive so wouldn't break anything as far as I know of.

```
If you're using the same source code layout as we use internally (Source/Public and Source/Private), then PublicDependencyModuleNames will be available in the Public and Private folders, but PrivateDependencyModuleNames will only be available in the Private folder.
```

Take it that `#include "HttpRetrySystem.h"` was the issue in `AgonesHook.h`.

**Comment by domgreen** [comment]
Would check backwards comparability with someone on `4.24` and merge 👍

**Comment by drichardson** [comment]
> 
> 
> @drichardson , @WVerlaek who are our resident Unreal experts - this good for you? If so, happy to approve.

LGTM. I didn't try to build it but *Http* shouldn't be in the public dependency list unless it's required to use the API, so the change makes sense to me.

**Pull request merged**
