### PR TITLE
Bump lodash from 4.17.15 to 4.17.19 to fix a security vulnerability.

### PR DESCRIPTION
**Pull request by roberthbailey**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking
> /kind bug

 /kind cleanup

> /kind documentation
> /kind feature
> /kind hotfix

**What this PR does / Why we need it**: This is a manually created version of https://github.com/googleforgames/agones/pull/1706 without the version change to the agones sdk. 

/assign @steven-supersolid

### CODE REVIEW

**Comment by roberthbailey** [comment]
It failed on the html test. Trying again.

**Comment by roberthbailey** [comment]
Another flake, this time in `site-static` (in the hugo tests): `fatal error: concurrent map read and map write`

**Comment by aLekSer** [comment]
Error with lodash@4.17.19 exctracting:
```
npm ERR! code EINTEGRITY
npm ERR! Verification failed while extracting lodash@4.17.19:
npm ERR! Verification failed while extracting lodash@4.17.19:
npm ERR! sha512-JNvd8XER9GQX0v2qJgsaN/mzFCNA5BRe/j8JN9d+tWyGLSodKQHKFicdwNYzWwI3wjRnaKPsGj1XkBjx/F96DQ== integrity checksum failed when using sha512: wanted sha512-JNvd8XER9GQX0v2qJgsaN/mzFCNA5BRe/j8JN9d+tWyGLSodKQHKFicdwNYzWwI3wjRnaKPsGj1XkBjx/F96DQ== but got sha512-8xOcRHvCjnocdS5cpwXQXVzmmh5e5+saE2QGoeQmbKmRS6J3VQppPOIt0MnmE+4xlZoumy0GPG0D0MVIQbNA1A==. (314170 bytes)
=== RUN   TestAlphaGetAndSetPlayerCapacity
```

**Comment by roberthbailey** [comment]
Interesting. That was the sha that was set by dependabot...

**Comment by roberthbailey** [comment]
The `sha512-8xOcRHvCjnoc...` hash is from 4.17.15.

**Comment by roberthbailey** [comment]
Looks like I made a typo, which is why it was still pulling the old tar.gz file. Should be fixed now. Thanks for catching this @aLekSer.

**Pull request merged**
