### PR TITLE
Update Kubernetes to 1.24 #2867

### PR DESCRIPTION
**Pull request by 1804devs**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, press enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking
> /kind bug
> /kind cleanup
> /kind documentation
> /kind feature
> /kind hotfix

**What this PR does / Why we need it**:  Kubernetes updates 

**Which issue(s) this PR fixes**: 

Closes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by markmandel** [comment]
Thanks for this!

Looks like you might be basing this work off a rather older version of the code - so you have a bunch of conflicts in there.

The CI failure looks like a flake, but we can't go forward with the conflicts unfortunately.

**Comment by zmerlynn** [comment]
Is this obviated by #2888?

**Comment by gongmax** [comment]
Thanks for your interest to contribute to Agones!

As Robert said in #2867, this might not be the suitable ticket for you to start contribution. I took a step further and created a complete PR (#2888) for this issue and as you can see there, a huge amount of changes were introduced which might be annoying for a first time contributor to the project.

Feel free to close this one and try to pick up a ticket with the ["good first issue" label](https://github.com/googleforgames/agones/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) to make your first contribution. Thanks again!

**Comment by markmandel** [comment]
Just wanted to say thanks for your efforts, but this work has been completed in #2895, so I'm going to close this PR.

If you want some guidance on what to work on, feel free to drop into Slack's #develop channel, and would love to chat to you about what could be a good fit 👍🏻

**Pull request closed without merging**
