### PR TITLE
Docs: Fix rest `GetPlayerCount` description

### LINKED ISSUE #1810: Wrong `Alpha: GetPlayerCount` description in the REST docs
**What happened**: REST Docs `Alpha: GetPlayerCount` has a duplicate description of `Alpha: IsPlayerConnected`

**How to reproduce it (as minimally and precisely as possible)**: 
Go to https://agones.dev/site/docs/guides/client-sdks/rest

image

### PR DESCRIPTION
**Pull request by Reousa**
**What type of PR is this?**

/kind documentation

**What this PR does / Why we need it**:

Fixes the REST docs

**Which issue(s) this PR fixes**:
Closes #1810 

**Special notes for your reviewer**:

I assumed that this behavior is also true for this entry:

> This is always accurate from what has been set through this SDK, even if the value has yet to be updated on the GameServer status resource.

### CODE REVIEW

**Comment by aLekSer** [comment]
It could be the case that we need to clean up E2E test cluster which could have dangling Fleets, as I saw it from my recent PRs updates and CI results.

**Review by aLekSer — APPROVED** [review]
Thanks for noticing this missing section.

**Comment by aLekSer** [comment]
I expect that CI would be fixed after #1808 .

**Comment by Reousa** [comment]
Do tag me if a rebase is needed 👍

**Review by markmandel — APPROVED** [review]
Good catch!

**Pull request merged**
