### PR TITLE
Add load balancer configuration for Helm options

### PR DESCRIPTION
**Pull request by yoshd**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking
> /kind bug
> /kind cleanup
> /kind documentation

/kind feature

> /kind hotfix

**What this PR does / Why we need it**:

Added the following Helm configuration options:

* `agones.allocator.http.loadBalancerSourceRanges`
* `agones.ping.http.loadBalancerIP`
* `agones.ping.http.loadBalancerSourceRanges`
* `agones.ping.udp.loadBalancerIP`
* `agones.ping.udp.loadBalancerSourceRanges`

This allows the Helm installation to configure the LoadBalancer loadBalancerIP and loadBalancerSourceRanges.

### CODE REVIEW

**Review by EricFortin — APPROVED** [review]

**Comment by pooneh-m** [comment]
@yoshd is loadBalancerSourceRanges manually tested?

**Review by pooneh-m — APPROVED** [review]
Thanks for the change.

**Comment by yoshd** [comment]
@pooneh-m 
Thank you for checking.
I built a cluster with GKE and set each value when installing with helm.
I've confirmed that setting *.loadBalancerSourceRanges creates a firewall.
I also reserved a static IP address, set it to *.loadBalancerIP, and confirmed that the IP address is being used.

**Pull request merged**
