### PR TITLE
Regenerate package-lock.json for the two node.js projects

### PR DESCRIPTION
**Pull request by steven-supersolid**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, press enter to put that in a new line, and remove leading whitespace from that line:
>
/kind cleanup

**What this PR does / Why we need it**:
Package versions in the sdk package-lock.json are not consistent and are causing problems with the same packages in the examples package-lock.json.
This PR removes both the previous lock files and regenerates so they should stay in sync

**Which issue(s) this PR fixes**:

Closes #

**Special notes for your reviewer**:
We should also consider updating to Node.js 16  / npm 7 as this will simplify the contents of package-lock.json in examples to just reference the contents of the package-lock.json for the sdk instead of duplicating parts of it

### CODE REVIEW

**Review by roberthbailey — APPROVED** [review]

**Comment by roberthbailey** [comment]
@steven-supersolid - can you please rebase so that we can merge this?

**Comment by steven-supersolid** [comment]
Unrelated test failing?

```
--- FAIL: TestFleetRecreateGameServers (0.00s)
    --- FAIL: TestFleetRecreateGameServers/gameserver_unhealthy (103.99s)
        fleet_test.go:1172: Could not message GameServer: timed out attempting to send UDP packet to address: timed out waiting for the condition
```

**Comment by roberthbailey** [comment]
e2e-stable:
```
--- FAIL: TestFleetRecreateGameServers (0.00s)
    --- FAIL: TestFleetRecreateGameServers/gameserver_unhealthy (103.99s)
        fleet_test.go:1172: Could not message GameServer: timed out attempting to send UDP packet to address: timed out waiting for the condition
FAIL
```

**Pull request merged**
