### PR TITLE
Update the node-forge dependency to address GHSA-5rrq-pxf6-6jx5

### PR DESCRIPTION
**Pull request by roberthbailey**
See https://github.com/advisories/GHSA-5rrq-pxf6-6jx5

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, press enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking
> /kind bug

/kind cleanup

> /kind documentation
> /kind feature
> /kind hotfix

**What this PR does / Why we need it**: Fix a security vulnerability found by dependabot. 

**Which issue(s) this PR fixes**:

Closes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by steven-supersolid — APPROVED** [review]

**Comment by roberthbailey** [comment]
Failed in e2e-feature-gates:

```
--- FAIL: TestAutoscalerBasicFunctions (318.10s)
    framework.go:284: 
        	Error Trace:	framework.go:284
        	            				fleetautoscaler_test.go:89
        	Error:      	Received unexpected error:
        	            	timed out waiting for the condition
        	Test:       	TestAutoscalerBasicFunctions
        	Messages:   	error waiting for fleet condition on fleet: simple-fleet-gpnms
FAIL
```

**Comment by roberthbailey** [comment]
e2e-feature-gates:

```
--- FAIL: TestUpdateFleetReplicaAndSpec (87.60s)
    fleet_test.go:384: 
        	Error Trace:	fleet_test.go:384
        	Error:      	Condition never satisfied
        	Test:       	TestUpdateFleetReplicaAndSpec
        	Messages:   	Wrong number of GameServerSets
```

**Comment by roberthbailey** [comment]
This time sdk-conformance failed.

```
make[2]: *** [includes/sdk.mk:145: run-sdk-conformance-no-build] Error 1
make[1]: *** [includes/sdk.mk:153: run-sdk-conformance-test] Error 2
make: *** [includes/sdk.mk:163: run-sdk-conformance-test-go] Error 2
make: *** Waiting for unfinished jobs....
```

**Review by markmandel — APPROVED** [review]

**Pull request merged**
