### PR TITLE
Upgrade from Debian Bullseye to Bookworm for /build

### PR DESCRIPTION
**Pull request by Kalaiselvi84**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, press enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking
> /kind bug

/kind cleanup
> /kind documentation
> /kind feature
> /kind hotfix
> /kind release

**What this PR does / Why we need it**:

**Which issue(s) this PR fixes**:

Work on #3570 

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by markmandel** [comment]
Looks like it's complaining that `python` doesn't exist as a package here:

https://github.com/googleforgames/agones/pull/3574/files#diff-686b06cb4b89c224b0df5f76fa2bbc7b5757477074e6917a21b8040a9e6857a4R20

```
...
3.470 Reading state information...
3.476 Package python is not available, but is referred to by another package.
3.476 This may mean that the package is missing, has been obsoleted, or
3.476 is only available from another source
3.476 However the following packages replace it:
3.476   python-is-python3 2to3
...
```

I actually don't think we need it explicitly defined in the `apt-get install` command, so my suggestion would be to drop it entirely, so make that line instead

```
apt-get install -y build-essential gnupg curl git wget psmisc rsync make bash-completion
```

And see if that solves the issue.

**Comment by Kalaiselvi84** [comment]
Log of `make build-images && make push && make install` - https://gist.github.com/Kalaiselvi84/98b1c859563e817f1c58ce2d7bcdff2c

I am not fully convinced about this PR. I think I may have made some mistakes while creating it. Will submit another PR for this.

**Comment by markmandel** [comment]
I see the same in the CI build

```
google-cloud-cli-app-engine-python : Depends: python2.7 but it is not installable
```

I don't think you did anything wrong, but I have a good idea on how to fix this - I think we're tryng to install the old version of the gcloud command line client, and didn't update the apt repositories.

**Comment by markmandel** [comment]
I had assumed that `gcloud` would install the dependency.

Let's try one more thing:

```
apt-get install -y build-essential gnupg curl git wget psmisc python2.7 rsync make bash-completion
```

See how that goes if we install python2.7 directly.

**Comment by markmandel** [comment]
Huh, this is interesting - seeing the same issue over here: https://github.com/GoogleCloudPlatform/cloud-sdk-docker/issues/345

**Comment by markmandel** [comment]
Yep - looks like this is a legitimate bug with the gcloud sdk and Debian Bookworm!

https://issuetracker.google.com/issues/265528492

So we should pause this PR until I do some hunting internally, see what I can find when it's going to get fixed.

**Comment by Kalaiselvi84** [comment]
Log suggested - `python-is-python3 2to3` - https://gist.github.com/Kalaiselvi84/f120f58d2f79f1c024bf2659367623b9

Tried replacing `python` to `python3` - Log- https://gist.github.com/Kalaiselvi84/fd5d6e62992d805b19401e476b8c9ba9. New error - `6.200  google-cloud-cli-app-engine-python : Depends: python2.7 but it is not installable`

We have python3 in `/build-image` dir - https://github.com/googleforgames/agones/blob/e7b24d2406e2cd2967351a7157389ae6795fb7dd/build/build-image/cache/Dockerfile-base#L18

https://github.com/googleforgames/agones/blob/e7b24d2406e2cd2967351a7157389ae6795fb7dd/build/build-image/Dockerfile#L74

**Comment by Kalaiselvi84** [comment]
Including `python3` and excluding  `google-cloud-cli-app-engine-go` seems resolves the `google-cloud-cli-app-engine-python : Depends: python2.7 but it is not installable`.However, I'm not sure if this is the right approach, and we are now facing a different error:

```
9.426 error: externally-managed-environment
9.426 
9.426 × This environment is externally managed
9.426 ╰─> To install Python packages system-wide, try apt install
9.426     python3-xyz, where xyz is the package you are trying to
9.426     install.
```

Log - https://gist.github.com/Kalaiselvi84/bcfa4659bcf02334a688b776ef4018cf

**Comment by markmandel** [comment]
Unfortunately we need `google-cloud-cli-app-engine-go` - it's how we deploy the Agones website. So looks like we'll need to wait on https://issuetracker.google.com/issues/265528492 to be resolved.

**Comment by Kalaiselvi84** [comment]
Log for `make build-images` with `python3`, without `google-cloud-cli-app-engine-go`, and install yamllint using `apt-get install` - https://gist.github.com/Kalaiselvi84/56844929164d8f981e208028eafa5b0d

**Comment by markmandel** [comment]
New issue (these would all need to get fixed anyway)!

```
#10 1.178 E: Package 'openjdk-11-jre' has no installation candidate
```

Let's replace `openjdk-11-jre` with openjdk-23-jre` which is in this version of Debian.

**Comment by markmandel** [comment]
> New issue (these would all need to get fixed anyway)!
> 
> ```
> #10 1.178 E: Package 'openjdk-11-jre' has no installation candidate
> ```
> 
> Let's replace `openjdk-11-jre` with openjdk-23-jre` which is in this version of Debian.

Whops, my bad. My local machine is one debian version ahead of `bookwork`.

Let's do `openjdk-17-jre`, since that actually exists on Bookworm:

https://packages.debian.org/search?suite=bookworm&section=all&arch=any&searchon=names&keywords=openjdk

**Comment by Kalaiselvi84** [comment]
@markmandel, we are waiting for the completion of this [ticket](https://b.corp.google.com/issues/265528492) to resolve our issue. Please correct me if i am wrong.

**Comment by markmandel** [comment]
> @markmandel, we are waiting for the completion of this [ticket](https://issuetracker.google.com/issues/265528492) to resolve our build issue. Please correct me if i am wrong.

Yeah, that's a blocker at the moment.

**Comment by Kalaiselvi84** [comment]
The command `make build-images && make gcloud-auth-docker && make push && make install` has successfully passed locally with the workaround mentioned in [this ticket](https://b.corp.google.com/issues/265528492)

**Comment by markmandel** [comment]
Any objection to closing this now? I'm pretty sure https://github.com/googleforgames/agones/pull/3621 covers all of this now.

**Comment by Kalaiselvi84** [comment]
> Any objection to closing this now? I'm pretty sure #3621 covers all of this now.

No objection from me!

**Pull request closed without merging**
