### PR TITLE
Workaround for bullseye release CI blockage

### PR DESCRIPTION
**Pull request by markmandel**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, press enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking

/kind bug

> /kind cleanup
> /kind documentation
> /kind feature
> /kind hotfix

**What this PR does / Why we need it**:

Switch out `apt-get update` commands that are run in CI to being `apt-get --allow-releaseinfo-change update` to ignore the error on new release change.

**Which issue(s) this PR fixes**:

Workaround for #2224 until we can upgrade everything to bullseye.

**Special notes for your reviewer**:

🤞🏻

### CODE REVIEW

**Comment by markmandel** [comment]
Looks like the workaround worked, but got caught here instead:

```
✘✘✘ failed in 394.534443ms
1 errors in 135 documents
Html Test: Attempt 20
htmltest started at 10:23:54 on /tmp/website
========================================================================
site/index.html
  Non-OK status: 403 --- site/index.html --> https://vela.games/
========================================================================
```

Which is weird, since I can open the url from here just fine. Will retry.

**Comment by markmandel** [comment]
Ah, Vela is giving us a CloudFlare 403. I'll add a `data-proofer-ignore` for now.

**Comment by cindy52** [comment]
> Ah, Vela is giving us a CloudFlare 403. I'll add a `data-proofer-ignore` for now. I can replicate with curl.

Thank you Mark! I kept getting the hugo-test error before locally. I will merger your fix to my branch!

**Review by roberthbailey — APPROVED** [review]

**Comment by roberthbailey** [comment]
Looks like a flake:

``
time="2021-08-17 23:41:16.105" level=info msg="error waiting for fleet condition" error="timed out waiting for the condition" fleet=simple-fleet-qjmd5
--- FAIL: TestAutoscalerBasicFunctions (331.46s)
    fleetautoscaler_test.go:81: error waiting for fleet condition on fleet simple-fleet-qjmd5
```

**Comment by markmandel** [comment]
I can't see why the last build failed 🤔 looks like everything passed on the test step, as far as I can see

**Comment by markmandel** [comment]
Aha found it!

```
+ apt-get update
Get:1 http://deb.debian.org/debian buster InRelease [122 kB]
Get:2 http://deb.debian.org/debian buster-updates InRelease [51.9 kB]
Get:3 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]
Reading package lists...
E: Repository 'http://deb.debian.org/debian buster InRelease' changed its 'Suite' value from 'stable' to 'oldstable'
E: Repository 'http://deb.debian.org/debian buster-updates InRelease' changed its 'Suite' value from 'stable-updates' to 'oldstable-updates'
E: Repository 'http://security.debian.org/debian-security buster/updates InRelease' changed its 'Suite' value from 'stable' to 'oldstable'
Error executing command, exiting
includes/sdk.mk:106: recipe for target 'build-build-sdk-image' failed
```

**Comment by markmandel** [comment]
Think I got it this time. The nodejs installation script was calling `apt-get update`.

**Pull request merged**
