### PR TITLE
Build issue with cpp-simple image

### PR DESCRIPTION
**Pull request by Kalaiselvi84**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, press enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking

/kind bug

> /kind cleanup
> /kind documentation
> /kind feature
> /kind hotfix
> /kind release

**What this PR does / Why we need it**:

**Which issue(s) this PR fixes**:

Closes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by Kalaiselvi84** [comment]
make build - https://paste.googleplex.com/6502913542193152

**Comment by markmandel** [comment]
May want to bring this PR up to date with `main` - there should be a fix for that specific flaky test.

**Comment by markmandel** [comment]
Wait nope, #3306 hasn't been merge yet! So the fix isn't in `main`.

**Comment by markmandel** [comment]
Just curious if this change actually fixed things?

**Comment by Kalaiselvi84** [comment]
> Just curious if this change actually fixed things?

The changes made did not address the underlying problem. make build [log](https://gist.github.com/Kalaiselvi84/728047e69d6f1d7248f74a7063a235dc)

**Comment by markmandel** [comment]
Try the same new `find_package` approach, but add it before this line:

https://github.com/googleforgames/agones/blob/613cbc3a115c909a622becf970b52dfbb0cd4497/examples/cpp-simple/CMakeLists.txt#L29

See if that works.

**Comment by Kalaiselvi84** [comment]
> Try the same new `find_package` approach, but add it before this line:
> 
> https://github.com/googleforgames/agones/blob/613cbc3a115c909a622becf970b52dfbb0cd4497/examples/cpp-simple/CMakeLists.txt#L29
> 
> See if that works.

I haven't had any luck finding success yet with the new change- https://gist.github.com/Kalaiselvi84/1ec7f5b398ea5fd6679124c1d94309eb

**Comment by markmandel** [comment]
> I haven't had any luck finding success yet with the new change , and the build takes more than two hours to complete

Can I see the change in the PR?

The C++ one does take a long time. I've no idea why.

**Comment by Kalaiselvi84** [comment]
> > I haven't had any luck finding success yet with the new change , and the build takes more than two hours to complete
> 
> Can I see the change in the PR?
> 
> The C++ one does take a long time. I've no idea why.

committed the change

**Comment by markmandel** [comment]
Testing a different approach locally, I'll let you know how it goes!

**Comment by markmandel** [comment]
This is a tricky one to lock down! Something got updated in gRPC that I can't put my finger on.

Working on it in the background of other tasks - as as you said, it takes a while to compile. I got it down to 45m on one machine, but that's still only so many iterations per day.

**Comment by Kalaiselvi84** [comment]
Closing this PR as the issue is addressed in the PR https://github.com/googleforgames/agones/pull/3318

**Pull request closed without merging**
