### PR TITLE
Fixed: Multi namespace support for client secrets in helm template service/allocation.yaml

### PR DESCRIPTION
**Pull request by nagodon**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking

/kind bug

> /kind cleanup
> /kind documentation
> /kind feature
> /kind hotfix

**What this PR does / Why we need it**:

This is because the client secret is not set correctly when multiple namespaces are set in gameservers.namespaces in helm values.yaml.

following command.

```
$ helm template agones-manual \
      --namespace agones-system \
      --set gameservers.namespaces="{n1,n2}" \
      agones/install/helm/agones
```

expected:

```
---
# Source: agones/templates/service/allocation.yaml
# Default allocation client secret
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: allocator-client.default
  namespace: n1
  labels:
    app: agones-manual
    chart: "agones-1.11.0"
    release: "agones-manual"
    heritage: "Helm"
data:
  tls.crt: ...
  tls.key: ....
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: allocator-client.default
  namespace: n2
  labels:
    app: agones-manual
    chart: "agones-1.11.0"
    release: "agones-manual"
    heritage: "Helm"
data:
  tls.crt: ...
  tls.key: ...
```

actual:

```
---
# Source: agones/templates/service/allocation.yaml
# Default allocation client secret
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: allocator-client.default
  namespace: n1
  labels:
    app: agones-manual
    chart: "agones-1.11.0"
    release: "agones-manual"
    heritage: "Helm"
data:
  tls.crt: ...
  tls.key: ....
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: allocator-client.default
  namespace: n2
  labels:
    app: agones-manual
    chart: "agones-1.11.0"
    release: "agones-manual"
    heritage: "Helm"
data:
  tls.crt: ...
  tls.key: ...
```

**Which issue(s) this PR fixes**:

none

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by markmandel** [comment]
```
make[1]: Entering directory '/workspace/build'
docker run --rm -v /workspace/build//.config/gcloud:/root/.config/gcloud -v ~/.kube/:/root/.kube -v ~/.config/helm:/root/.config/helm -v ~/.cache/helm:/root/.cache/helm -v /workspace:/go/src/agones.dev/agones -v /workspace/build//.gomod:/go/pkg/mod -v /workspace/build//.gocache:/root/.cache/go-build  agones-build:7b23a47624 bash -c \
	'helm template agones-manual --namespace agones-system /go/src/agones.dev/agones/install/helm/agones \
	--set agones.controller.generateTLS=false \
	--set agones.allocator.generateTLS=false \
	--set agones.allocator.generateClientTLS=false \
	--set agones.crds.cleanupOnDelete=false \
	> /go/src/agones.dev/agones/install/yaml/install.yaml'
make[1]: Leaving directory '/workspace/build'
sort /workspace/install/yaml/install.yaml > /tmp/agones-install/install.current.yaml.sorted
diff /tmp/agones-install/install.yaml.sorted /tmp/agones-install/install.current.yaml.sorted
7a8
> 
12416d12416
< # Source: agones/templates/service/allocation.yaml
12519d12518```

If you run `make gen-install` this CI failure will go away :+1: , as it generates the install.yaml for the repo.

**Comment by nagodon** [comment]
@markmandel 
Thank you.
I'll try

**Review by pooneh-m — APPROVED** [review]
Thanks for the fix.

**Comment by nagodon** [comment]
Merge thanks.

**Pull request merged**
