### PR TITLE
Upgrade Kubectl to 1.16.15

### PR DESCRIPTION
**Pull request by markmandel**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>

/kind breaking

> /kind bug
> /kind cleanup
> /kind documentation
> /kind feature
> /kind hotfix

**What this PR does / Why we need it**:
Updated both the build and the e2e image to Kubectl 1.16.15 (same as client-go etc)

**Which issue(s) this PR fixes**:

Work on #1649

**Special notes for your reviewer**:

N/A

### CODE REVIEW

**Comment by aLekSer** [comment]
I wonder if a new version of Kubernetes code-generator would produce something new? I mean this line of Dockerfile was also impacted:
```
RUN mkdir -p /go/src/k8s.io && cd /go/src/k8s.io && \
    git clone -b kubernetes-${KUBERNETES_VER} --depth=3 https://github.com/kubernetes/code-generator.git
```

**Comment by aLekSer** [comment]
I wonder if a new version of Kubernetes `code-generator` would produce something different? I mean this line of Dockerfile was also impacted:
```
RUN mkdir -p /go/src/k8s.io && cd /go/src/k8s.io && \
    git clone -b kubernetes-${KUBERNETES_VER} --depth=3 https://github.com/kubernetes/code-generator.git
```

**Comment by markmandel** [comment]
> I wonder if a new version of Kubernetes code-generator would produce something new? I mean this line of Dockerfile was also impacted:
> 
> ```
> RUN mkdir -p /go/src/k8s.io && cd /go/src/k8s.io && \
>     git clone -b kubernetes-${KUBERNETES_VER} --depth=3 https://github.com/kubernetes/code-generator.git
> ```

Ooh, that's a good question. Lemme hop on that too.

**Comment by markmandel** [comment]
So I ran it - one small change in clientset.go -- I'll submit a PR once this is done (unless you want it in here?)

**Review by aLekSer — APPROVED** [review]
I think changes to generated crd-client can go into a separate PR. Just so all devs would have no surprising diff after running `make gen-crd-client`.

**Comment by aLekSer** [comment]
Looking at SDK conformance tests this days. This fail is the same - attempting to connect when SDK server is stopped.
```
make[2]: *** [run-sdk-conformance-no-build] Error 1
includes/sdk.mk:145: recipe for target 'run-sdk-conformance-no-build' failed
includes/sdk.mk:152: recipe for target 'run-sdk-conformance-test' failed
make[1]: *** [run-sdk-conformance-test] Error 2
includes/sdk.mk:159: recipe for target 'run-sdk-conformance-test-node' failed
make: *** [run-sdk-conformance-test-node] Error 2
make: *** Waiting for unfinished jobs....
# run with feature flags enabled
/usr/bin/make run-sdk-conformance-no-build SDK_FOLDER=go GRPC_PORT=9001 HTTP_PORT=9101 FEATURE_GATES=PlayerTracking=true TESTS=ready,allocate,setlabel,setannotation,gameserver,health,shutdown,watch,reserve,getplayercapacity,setplayercapacity,playerconnect,playerdisconnect,getplayercount,isplayerconnected,getconnectedplayers
+ /root/sdktest.sh
+ cd /go/src/agones.dev/agones/test/sdk/nodejs
+ npm run testSDK

> @ testSDK /go/src/agones.dev/agones/test/sdk/nodejs
> node ./testSDKClient.js

attempting to connect
```

**Pull request merged**
