### PR TITLE
Stackdriver - fix getMonitoredResource

### PR DESCRIPTION
**Pull request by aLekSer**
Labels were changed for k8s_container monitored resource. Fix error message, update docs.
Tested on Stackdriver dashboard. Old dashboard's charts are not available and should be readded with `Kubernetes Container` resource instead of `Global`

Part of #1330.

### CODE REVIEW

**Comment by aLekSer** [comment]
Finally CI passes flaky `make test` step and TestGameServerReserve. Will make additional test of Stackdriver dashboard.

**Comment by aLekSer** [comment]
Tested on `agones/gameserver_count` metric, chart below:
GS_Count_by_State
ChartSettings

**Comment by markmandel** [comment]
/assign @bbf 

Can you take a look? I'm totally not into metrics, but if you say this is good to go, happy to approve and push through.

**Comment by cyriltovena** [comment]
Come here to say where is the doc of this ? I had hard time trying to find what should go inside this map and I used the doc IIRC.

**Comment by aLekSer** [comment]
@cyriltovena There is a definition of these 2 types of Monitored Resource:
[Kubernetes Container - k8s_container](https://cloud.google.com/monitoring/api/resources#tag_k8s_container) and  [GKE Container](https://cloud.google.com/monitoring/api/resources#tag_gke_container) later is not working now in GKE cluster I am creating with `make gcloud-test-cluster`.

**Comment by aLekSer** [comment]
I would add `metadata.system_labels.node_name` instead of `instance_id` here and test one more time

**Comment by cyriltovena** [comment]
@aLekSer thanks for the clarification!

**Comment by aLekSer** [comment]
This version with switching from `instance_id` key to a new one did not work:
```
2020/02/15 08:50:47 Failed to export to Stackdriver: rpc error: code = InvalidArgument desc = One or more TimeSeries could not be written: Field timeSeries[0].resource.labels had an invalid value of "metadata.system_labels.node_name": Label key contains invalid characters.: timeSeries[0];
```
I think we can skip this label.

**Comment by bbf** [comment]
In the past I had not deeply inspected Agones' monitoring code, and now that I did, I fear that the Stackdriver integration will only work on very simple scenarios. Stackdriver has a different set of limitations to achieve its level of scalability, that Prometheus doesn't have. So I'm not sure if we should merge this fix, which probably will allow users to temporarily use Stackdriver, considering that we might have to introduce several breaking changes to really fix the integration. And because we are leveraging OpenCensus, the required breaking changes might impact both integrations.

@markmandel WTDY? I should be able to spend some time in early March to propose and implement the changes, or we can just commit this and break everything again soon.

**Comment by markmandel** [comment]
What does "break everything again" actually mean? What actually breaks?

**Comment by markmandel** [comment]
I'll bring up another point -- we have a RC coming out next week.

I'd hate for Stackdriver integration to just not work on the next release. That seems like the ultimate worst scenario.

What do you all think?

**Comment by bbf** [comment]
> What does "break everything again" actually mean? What actually breaks?

Most likely changing the monitored resource being changed, as well as many of the metric definitions.

> I'll bring up another point -- we have a RC coming out next week.
> 
> I'd hate for Stackdriver integration to just not work on the next release. That seems like the ultimate worst scenario.

Given that the breakage will be unavoidable, and this is an incremental improvement towards a working solution, I think we can merge this.

LGTM

**Pull request merged**
