### PR TITLE
Add error callback to testSDKClient

### LINKED ISSUE #2954: Node.js SDK test is flaky
Example failure from [build](https://ffff4421ba943d99476503385c2dbe11b2f508d4a3d7ea4495fa1e3-apidata.googleusercontent.com/download/storage/v1/b/agones-build-logs/o/log-c35b1f87-28d4-4382-931e-4055d3b9349f.txt?jk=AahUMlv6enaHI1HJjKw2w7cp7v3xIFuoTL72yiBizp-p1fD71kaxW4nbJ7gbUyKO9LojnwtaHiPdcCO-9PmI7UpkH0v6WBwHHwluSVn2p6I8LRXLGDbbEuoeldKOjCu8tkKB5qYXPrzXFgW2tLFYFJfqsBjN5yiHXtMljnE2lp9fmvBw0MmUKH80JdCz7zF5jtswk5Yyxbi111XZEDIV4VJVJhqc2Xs9B_Nb1S_tse_I2NdELxHPN9_5vMVNNUQqDBYJ3ZufvKz6oKxEf1JcZLgAA2sAJgLNj5ateItJxni_1JP84blKb25OcqSlqVzwJKxlrr-R1B8sJWDz4R70XoBzNBBoKlCuVVJA1d9DsSCZ7oDfJLwIuK2scEpZK3mL9IoS83Yyu_5_dZT3MdJvfNkUvTCVudnzvguaP1J8Bx8rZwNDU6b4nQYnajWmG3KBiAEzCugFt1rcHCFQbA2-X7DmmfKLGsUUTbnQX2M_gzVTSjU7Cb7sCnEaHyw52EF3T6Sz0-wkJvrQBxbmVU7KDDJXLTx5N9Q62DcnBSQGs4VshhosEVTms9_aHRDhp3uOi-CGcpolgcDqw1_hdXCYEvHuOQw8SXEnaKwVJZm8w36OVbedwz_Ldv8ssbrv9RTO7_nTBrFO2qlyS_uOJptEJSPgw0PeRWgorekyMDNL3keJGmnuwwyrMndFr3yKafpY2Dqbj9Ue-SBpITZPPgEJu9IMHy5br7MjeY3JRDpzm1tPIz_bo-YJjHNpQprIs5vEM45p0fhqYqs6P5qiQca3a52jBbBPJ0szgq5IRLUbDeUQMdi77zx8XfoCW1mGb7tpDlz522VBj1bLJC_KLK7X88U5K5cc_wuK3qdyN4BqWTZUhR_aEzhv30ut57JNvKIhrSfK1gCB6U2WqBVzmtRX5yg33jaiN1C5PsRyooSEAWrhHGlZIB7rF30lddZfuPy_Dz0orBCJLeU6-18UoxN4LdfxXCv2rCc_sNP0WnqVqwzM77ZZNM5oJK0FzuTewkPs-57k8OPIX3W6lb2R_qb08nMhdJJui_lPEMuw75Qnk5ala8pYqb3VP1gXnf-bEMB-2WppyktX5T4PnD4vrVin9EMG2pGzi815gpdE-ewGN_85nSNYAzAD9LnAJJz77eGIK2m5tPIzMiQBzDwSr1nj3BiYIHONRuJ_y-zGMuIYfUFfvfo1a803AMg-XvWU80yzPMfnQ8E&isca=1):

```
sdk-client-test.go:40: Client is starting
sdk-client-test.go:41: Feature Flags: CustomFasSyncInterval=true&Example=false&PlayerAllocationFilter=false&PlayerTracking=true&PodHostname=false&ResetMetricsOnDelete=false&SDKGracefulTermination=true&SafeToEvict=false&SplitControllerAndExtensions=false&StateAllocationFilter=true
{"message":"shutting down sdk server","severity":"info","source":"main","time":"2023-02-07T00:07:46.473184391Z"}
{"message":"Could not find a request which was expected","request":"allocate","sdkName":"node","severity":"error","source":"*sdkserver.LocalSDKServer","time":"2023-02-07T00:07:46.473661342Z"}
{"expected":["ready","allocate","setlabel","setannotation","gameserver","health","shutdown","watch","reserve"],"message":"Testing Failed","received":["ready","watch","gameserver","setannotation"],"sdkName":"node","severity":"info","source":"*sdkserver.LocalSDKServer","time":"2023-02-07T00:07:46.473709277Z"}
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: 14 UNAVAILABLE: Connection dropped
    at Object.callErrorFromStatus (/go/src/agones.dev/agones/test/sdk/nodejs/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
    at Object.onReceiveStatus (/go/src/agones.dev/agones/test/sdk/nodejs/node_modules/@grpc/grpc-js/build/src/client.js:360:49)
    at Object.onReceiveStatus (/go/src/agones.dev/agones/test/sdk/nodejs/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)
    at /go/src/agones.dev/agones/test/sdk/nodejs/node_modules/@grpc/grpc-js/build/src/call-stream.js:188:78
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
for call at
    at ServiceClientImpl.makeServerStreamRequest (/go/src/agones.dev/agones/test/sdk/nodejs/node_modules/@grpc/grpc-js/build/src/client.js:343:34)
    at ServiceClientImpl.watchGameServer (/go/src/agones.dev/agones/test/sdk/nodejs/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
    at AgonesSDK.watchGameServer (/go/src/agones.dev/agones/test/sdk/nodejs/node_modules/@google-cloud/agones-sdk/src/agonesSDK.js:132:30)
    at connect (/go/src/agones.dev/agones/test/sdk/nodejs/testSDKClient.js:25:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Emitted 'error' event on ClientReadableStreamImpl instance at:
    at Object.onReceiveStatus (/go/src/agones.dev/agones/test/sdk/nodejs/node_modules/@grpc/grpc-js/build/src/client.js:360:28)
    at Object.onReceiveStatus (/go/src/agones.dev/agones/test/sdk/nodejs/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)
    at /go/src/agones.dev/agones/test/sdk/nodejs/node_modules/@grpc/grpc-js/build/src/call-stream.js:188:78
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  code: 14,
  details: 'Connection dropped',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} }
}

Node.js v18.14.0
```

Some other past flakes:
* [1a560f9b-9dc2-4517-bc96-e7b90f6ea774](https://ffb0e23c06dfd1f8e412ab3b4bcff06fba79a3222dcb5cda91d73e4-apidata.googleusercontent.com/download/storage/v1/b/agones-build-logs/o/log-1a560f9b-9dc2-4517-bc96-e7b90f6ea774.txt?jk=AahUMlvf3I0MjJdeDF-zWHtIMPUBSeu7Lou31Iip_fI7CytRRkHxv7eAsoj0I4b6u6xkbEKVjNI1as08TNEx7e5xxxnSS1Qj_5FK_Cb5W9vTVEAl4KKhvXWbVSWRVwMRnj7WajtJMntX8LoaJ21LQMa4E8F2Wr0jhp8guLpe-C6UPpDXKtN7Xdgp820ovZEQWZnSrK2_POVYvZhOotqsPcPofb-JzkmZID7cBsiLl9iik1q82fwyI013_LwsuBpejVjuhUs2oXqaVZ86ge_RQXaMZhqjb-lLs7SPGsqJ8Qrsss2qPxsnrnpscFBzwt-wK7KWaD_GZy3oTqn2CJvEwMkXIp-PKhRHnmlbb0N_gm5aoXyaAPQyTY48eqRLZWQlKdgY-Mqj8N8BXkiDOEPImNlE7uMusERmRbi4fXQVcDe7IJLV-c2-qd-SseF-U6ucb-4qbGyAD2GjiaYzz3HajK2jHCCXQix2trlNWznr7h20bPo4oORVabr0S74tjOZemathrZMbpOKRwNSKN1tjDt0XHNDBQw_6g1oeEypaOzdDWcI0XAbefjjrWPX9IZvxZd5QlaIsm3HEptQ17e9CiZcJWT2Fwlp6lpM8TEnrKYmWgl5pQNNnN1DGstgznXaA_NzGGw_KmYY27vD25YRMOroTinVvJfFnvdhpFHkTvL7EY6Uqfbt9uuEE6CM7EivFGHnrQFcsd-7-icW6TCVub_kKtK_5WUax3hNW9zFevTyZ33-RYeCBEtaJZVTPUgFYWMWmgF_x9MkLW36WkWFhrxcIwTOXlCTIRwEdDL4GQSj6Rl_USBTTFrJqM-1y7HrTBfyiuo8gc8S0u-d1dstQvTA-QR43SYE27G6JyulYMeCdFEhb9Ed3vTXdAgMYKhNamyN_dM2LSByCA5bKu3JsqvdM5s8eZ7J5Eo5VsBCCV5xvJWU3dLGV5idMagWnKPWOLmFV5eEBIOgDD-4XuGe8ssaBIsHuDKfFUJSFq8yAHeRtPy_8Pmqo_DvL8toVCVindHCEZW538iknftVqH-3O-20XT1q_1FSiUG-6l2vpHZnv-CXof1WUi7pzYLx8K_HvXK812BlhAEaxiIo4hJH8c8DTUnkvfsEFmq0wSzihxWO87-bKvODzlnHwY6A6Y1dcr8gq973pNooZeAHQxtiuvQfzHus14T-sc3kJ8Mg3JYNe7wYpFpAfU9fP170j-1fHGRKVW04&isca=1)
* [94cfaefc-6921-457f-8530-251b8f683782](https://ff66cec918498ace02f1091e4abae457db3b193ef70da190807161c-apidata.googleusercontent.com/download/storage/v1/b/agones-build-logs/o/log-94cfaefc-6921-457f-8530-251b8f683782.txt?jk=AahUMlvpDJeZ1JsW3WCbmW4xkn1tctjS2b95IJJnXo--ojFL90B4Q7ieYUTIGGGEzV65bXBArF7TCpCGdldIL-jm9HzNj4_j-CraQFeFWWWEXFpBmvaGU6NmnqoU7Wtj7USDmfR2DwAiRc0GtvaTbXdIDKzZjwS7zAOqRA-BW56lGtH4fcee5cPnDxSXns9H7nTD-ZrxlMzTOuXZE0MuJLYS_CHGVIGA_TWPhClRXiUllOvuXRdj75AzaJv4XQFCmT63uMlH_l6nNSyxml6eFuurxJvU9wmAraTo5DcMElxnVzHxgZty3SoKD0N8sE1hiKT-2Frl6Egd5_uHJIe9ZaF36J5NFH4gQdTj-r9yLyVut8C6wQsQpsMbTjVZORPDYHzxYJbK3QYRCP4ufYMJQcV1BcecxxVGR7upDRI2XnQGxZ__6xhgpU6pxYau5s8t2Kl3-eXCXbbckTDBQ1-zBcPH0qjgpfp-bh2tNkYk0vCEU3g--YrRU5dXYGnzS1mBpT2PGud-i5MmHvJxKmeh0ZsAFnG1z9XcQiVnv_1J65r8QToGGdixAA9MrObGn3meKYNMN99mpxHC-BGLp7CiESNR7AucR7wh2C7Qcn6YyoYaffaCp092xwKLwPJF985joIQzlgvzSOSR2fD2cpLfgr5y3fj4bR-oIoU10q1uduPnQ-mUijD5G9hua-ZjT_O7crctYkQ8bBAw00x9kMiwjBJoMl0mmKc8QqwIbhRBQ1CyCnuejhiKOMatkjIIrjeis7l-lZkF4hcLu5yXLd1qmola4akCUxmOQ09mwhTDn2-HP6eZOBFJ778ehePG_aUJPDN7CXyLkgImuzF3R-O0CXSr5D1aguJq_9gYxCJzcTnctWpwTDIPOAQQP5qFDZ9euV3KnWsyTAIZxWLL1SEOXUvXOr5hw_4PrUWl86L5BhxfTm21Q_Bcy0V_Wffm5GT5--VHtERCnwahnZWNsImC5xM2FNx96xF9tPc0MtoJrtnzlC4MQeu4AtwOuxXgBhFSjTH0aqbIrezn8xX37gHSag7fSNNd5sTD9LHbOsfvYb9GA-EOKEEbA4xfeXl9m0ToagkK3LDZkfavZYSVKZyMgLvRsZaMI6oP7g75m_0pJAF97e9n4QkbKpoCLQ375dHceUfekAiEbCQK8AXetQBXxwD0MQNamVEU6SJNS0NW6BPSSGCsK5NgRUpqDdRQi64B3RYFeCo&isca=1)
* [6a852fd7-074f-459e-90c7-28ac1ed583b6](https://ff993e8054fd5e73b43b097de0ded5047de29a10b22bda4e5ee8d47-apidata.googleusercontent.com/download/storage/v1/b/agones-build-logs/o/log-6a852fd7-074f-459e-90c7-28ac1ed583b6.txt?jk=AahUMlsK_SySHPRQOex5X7GrNjZs-m666GyMZC8uIw5KAf0WTG2jjDsKuTQsqoE9U7at5_nLpH4nj2C11jljC1eTjlJPXnVM1BzcxRfrmENoIu4bYllYRW6M96_S3eFLxd47RWAY6tsogjASf8mDucJNVHgrE_kXTIS7bzQhr80byw2taj3tPkbAhx9lMxqxsFg2BxXvIEdxZVJ5-Oeiu8sI2Qx1NTCIYE0RaOBYtOLnEmMc8cwLRKRgjH6muZ6mRfAYN0EFRgOI0bwgriF-2jUHXI7TBBloLnddwXR6H58Ks7l9euFVyFfg1gDXiJwALmDxifvvDs0tgoCUKZk6cy0H_1hRQYQGMZXo1rajJtfgEhgcJ3KXGWr9TVradPVHJDaqIntvCT1NYg3ZtZxY51MNcuorjJnOnlXoiquWcnWFgH4wPklAgwk8ukwVyBkNwtpodLf-tIJiRcUK2OF37V7OvVV-BLjvCZLobWnqo1v-bhj2GSna3o8Rq3cd82ern4tvWvmoDvXTui-Bkyb9giWzTBxE0KdKYPiMPTWGmfW2EE5mH3_lCQzbUBJPMzg0G436S3UczOaeOMTHHZCJDfsJOBXSB8Ir_EoXEfIYTiUVdX6oXW294KZdl49gyqBvzk8wpq_taxRN7Zh85Vvdjs77fe87TdrRPNbg7fepWCQfmH2w7PhUQO_Os5mapLK4n0RQxaDUBcuaKGCCSUl0FqlzqtGd5CbP_gewnLkWwNMTiXRyTSdHgR1e0kCInksX1qoTuJN-PAX1GxxVdLkJvplFS9pjmMkwWWISGWN1CaXf-ZeSi8RsXxjLTgP1ydt3h-50NJ0qb51332qM23fuJhUuX3h63CQd1pUWnIzLJOGm8W3TomdtBDxSXKRsU1LKTKn6U5cUrbqckeTgZUbPY0ZcrElQYbe-sgdq40WGOm5FQORLHBXQW68pHkeIgu1eQhconpR7wHp8K6MEkvVAVZbWaRjEue9IxahDaFeH0fDLwuozK56pkGxOfvpP11L4m-zR-Kkaqe2ZoEQWCouupTjRKMHKNedzSgtnKP-gjpco0bLHaBsLmYXFZVPzg_e9ejbgBcolVc0X7gIpY-x5Tg-ejQmNbrZWhIQStDz6vVz04c3q6lfa4HUI1vJIyIX2vRJMgZ5i9p7ZJ4x2ZGxuYpdEoc_-wRZZy2FrVZyj0-XYkJRJHaB0i0d6GGd8GTKUXoYtEgE&isca=1)

I am going to throw a PR at this to retry in a loop, but we should look into it.

cc @steven-supersolid

### PR DESCRIPTION
**Pull request by steven-supersolid**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, press enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking

/kind bug

> /kind cleanup
> /kind documentation
> /kind feature
> /kind hotfix

**What this PR does / Why we need it**:
Adds an error callback to `watchGameServer` so that errors can be caught during watching

**Which issue(s) this PR fixes**:

Closes #2954

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by gongmax** [comment]
I was recreating the test clusters which made the CI fail. I will retry this build after the test clusters are created.

**Comment by steven-supersolid** [comment]
I greatly appreciate any help reproducing this @gongmax. I don't how to reproduce the error and as on Windows I'm not sure if possible to reproduce the error e.g. not all the Make scripts work for me 100% of the time

**Review by roberthbailey — APPROVED** [review]

**Comment by markmandel** [comment]
@steven-supersolid can you rebase against main and push please? Because you are on an org fork, we can't update on our end. (automerge is enabled, so you should only have to do this once).

**Review by aimuz — APPROVED** [review]

**Pull request merged**
