### PR TITLE
Documentation updates to apply just prior to cutting the 0.12.0 release.

### PR DESCRIPTION
**Pull request by roberthbailey**

### CODE REVIEW

**Comment by roberthbailey** [comment]
Marking as ready for review so that this can be merged when appropriate (not sure if that is with the release candidate or the actual release).

**Comment by markmandel** [comment]
I was thinking to merge it before the stable release goes through - since it matches the experience and documentation that will exist once once stable has landed. WDYT?

**Comment by roberthbailey** [comment]
sgtm.

**Comment by markmandel** [comment]
Updating, so we can merge and release this :+1:

**Pull request merged**
