### PR TITLE
Update prerequisites.cmake

### LINKED ISSUE #2486: Failed to build CPP SDK
**What happened**:
When I tried building the CPP SDK, I got an error:
```
  /opt/agones-1.21.0/sdks/cpp/build/gRPC/src/src/core/lib/gpr/log_linux.cc:43:13:
  error: ambiguating new declaration of 'long int gettid()'
     43 | static long gettid(void) { return syscall(__NR_gettid); }
        |             ^~~~~~
  In file included from /usr/include/unistd.h:1170,
                   from /opt/agones-1.21.0/sdks/cpp/build/gRPC/src/src/core/lib/gpr/log_linux.cc:41:
  /usr/include/x86_64-linux-gnu/bits/unistd_ext.h:34:16: note: old
  declaration '__pid_t gettid()'
     34 | extern __pid_t gettid (void) __THROW;
        |                ^~~~~~
  make[2]: *** [CMakeFiles/gpr.dir/build.make:232:
```

**What you expected to happen**:
Successfully build.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Agones version: 
- v1.21.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install method (yaml/helm):
- Troubleshooting guide log(s):
- Others:

### PR DESCRIPTION
**Pull request by junekhan**
**What type of PR is this?**
/kind bug

**What this PR does / Why we need it**:
install grpc of the consistent version with ../CMakeLists.txt in CPP SDK

**Which issue(s) this PR fixes**:

Closes #2486 

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by roberthbailey** [comment]
Does this build locally for you? In CI, this PR failed on the `build-sdks` step with:

```
-- Configuring done
CMake Error at CMakeLists.txt:129 (add_library):
  Target "agones" links to target "Threads::Threads" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at CMakeLists.txt:129 (add_library):
  Target "agones" links to target "Threads::Threads" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


-- Generating done
-- Build files have been written to: /go/src/agones.dev/agones/sdks/cpp/.build
make: *** [Makefile:29: build] Error 1
make[1]: *** [includes/sdk.mk:88: run-sdk-command] Error 2
make: *** [includes/sdk.mk:72: run-sdk-command-cpp] Error 2
```

**Comment by markmandel** [comment]
Going to attempt to reproduce this locally with the tooling we have.

Would be good to know what your environment is - what are you compiling with, cmake version, OS, etc.

**Comment by markmandel** [comment]
Reproduced the build error locally, I think I've got a fix in here:
https://github.com/googleforgames/agones/compare/main...markmandel:fix_cpp_sdk_building_issue?expand=1

Had to add the `Threads` dependency to Cmake (Thank you Google Search), and also regen the grpc code.

It's late in my evening, but I'll finish testing tomorrow and likely upload a replacement PR. If you have time, @junekhan , it would be good to get your review of it, to make sure I didn't miss anything.

**Comment by markmandel** [comment]
I'm going to close this, since #2500 was merged. Please open a new issue or PR if there are other issues.

**Pull request closed without merging**
