### PR TITLE
Fix Installation Docs and example GS configuration

### PR DESCRIPTION
**Pull request by aLekSer**
Now we have 6 pods in agones-system namespace, not one as per docs.
There was an issue in PortPolicy and image tag.

### CODE REVIEW

**Comment by roberthbailey** [comment]
According to https://agones.dev/site/docs/examples/ these aren't supposed to be working examples:

"These examples are for reference only. They are not backed by working images."

I'd be happy to make them workable, but if we do we should update the docs too (and make them all work).

**Comment by aLekSer** [comment]
@roberthbailey 
Regarding the configuration, someone as I did could think they are working.
The most problem is that in comments section we read that Dynamic and HostPort could not defined at the same time. And then we define them both - which is mutually exclusive lines and bad configuration.
Note that I added fix of documentation here. PTAL again.

**Comment by aLekSer** [comment]
By the way I can leave not working image and correct only PortPolicy.

**Comment by roberthbailey** [comment]
> Regarding the configuration, someone as I did could think they are working.

I agree. I found it confusing as well.

**Comment by markmandel** [comment]
I've no strong opinions on leaving them as broken images - if you both feel strongly they should be working images, then lets make them all working configurations :+1: not just gameservers, but fleet.yaml, etc.

Sound good?

**Comment by roberthbailey** [comment]
I think it'd be nice to have them all working. It should be relatively easy to do so, and to update the docs to remove the note about them being non-functional.

**Comment by markmandel** [comment]
Sounds good to me. Do we want to include it in this PR, or make a new one?

**Comment by roberthbailey** [comment]
There isn't a good reason not to split it among multiple PRs so we can get this one in. I've created https://github.com/googleforgames/agones/issues/969 with a checklist for the files in question (I think some of them are already ok, so we can just verify those and fix the others).

**Comment by roberthbailey** [comment]
Part of https://github.com/googleforgames/agones/issues/969.

**Pull request merged**
