### PR TITLE
Refactor Dockerfile with multi-stage builds, security enhancements, a…

### PR DESCRIPTION
**Pull request by YoussefBayouli**
Improvements made:

Multi-stage builds: We split the Dockerfile into two stages to ensure the final image contains only the necessary dependencies for runtime.

Layer reduction: Combined multiple RUN commands to reduce the number of layers.

Security best practices: Removed unnecessary packages in the final stage and cleaned up APT cache after each package installation.

Minimal base image: Used debian:bookworm-slim for the runtime to reduce image size.

Commented paths and environment settings for clarity.

This approach makes the image more secure, smaller, and efficient for production use.

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, press enter to put that in a new line, and remove leading whitespace from that line:
>
>Refactor
>Enhancement
>Chore 

**What this PR does / Why we need it**:
Refactors the Dockerfile with multi-stage builds, reducing image size and layers.
Applies security best practices, including package minimization and using a non-root user.
Improves build efficiency and readability.
Reduces image size and deployment time.
Enhances security and performance.
Makes the Dockerfile easier to maintain and update.

**Which issue(s) this PR fixes**:

Closes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by YoussefBayouli** [comment]
I think the build is failing from time-out

**Comment by markmandel** [comment]
Been watching you punch away on this 😁 

I see where it's currently failing:

```
+ go mod edit --replace=agones.dev/agones@latest=../../../agones.dev/agones/
/go/src/agones.dev/agones/site/gen-api-docs.sh: line 32: go: command not found
make[1]: *** [includes/website.mk:110: test-gen-api-docs] Error 127
```

I have to ask one question though:

> Makes the Dockerfile easier to maintain and update.

Given the pain you are having - do you think this is still true? This is a build image only used in dev -- is all this pain worth it? 🤔 seems like a lot of yak shaving, and I'm not quite sure the final benefit is going to be.

Don't let me stop you, I'm curious where you finally end up, but figured how long you've been working on this, I figured I would ask the question 😄

**Comment by YoussefBayouli** [comment]
Hi Mark , Thanks for your comment . 
I've been motivated to contribute to this project because of its importance in the democratization of Games infrastructure, and I believe I can help improve it with a better solution. This is one of my first experiences in the world of open source contribution, and I love a good challenge. 

When I start something, I like to see it through to the end—it's a valuable learning opportunity for me, especially as I continue searching for a job.

Regarding the Dockerfile, multi-stage builds are something I recently learned, and I thought this project could benefit from them.

**Comment by markmandel** [comment]
> Regarding the Dockerfile, multi-stage builds are something I recently learned, and I thought this project could benefit from them.

I definitely appreciate the effort, and love the commitment - but I'll ask the question: Can you articulate a concrete benefit here, or is this dev to scratch a technology itch (we've all been there ☺️).

What do you think?

**Comment by YoussefBayouli** [comment]
Hi Mark, 
While I was motivated to exercise my recent learning of multi-stage builds, the changes provide tangible benefits. They reduce the image size by excluding unnecessary build tools, improve security by minimizing the attack surface, and speed up builds with better caching. So, it’s a blend of practicing new skills while delivering real advantages to the project.

I hope I have answered your question.

**Comment by markmandel** [comment]
> They reduce the image size by excluding unnecessary build tools

That's a plus for sure. But it does also add extra complexity for adding new tools - so that's a minus. How much of an issue is size for a dev-builder image? 

>  improve security by minimizing the attack surface

This is a dev builder image, so how much is attack surface an issue. It's not really serving anything except in CI.

> speed up builds with better caching

Is this just on initial build? or subsequent builds? By how much does it speed things up?

**Pull request closed without merging**
