### PR TITLE
Upgrade Hugo and Docsy

### PR DESCRIPTION
**Pull request by Kalaiselvi84**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, press enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking
> /kind bug

/kind cleanup

> /kind documentation
> /kind feature
> /kind hotfix
> /kind release

**What this PR does / Why we need it**:

**Which issue(s) this PR fixes**:

Closes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by Kalaiselvi84** [comment]
@markmandel, 

I have followed the below steps for upgrading Hugo and Docsy versions,

1. Upgraded the hugo version and addressed the errors pointed out by the site-server
2. I removed the Docsy folder. I'm aware of your advice to copy-paste it, but the build was consistently failing. Upon consultation with the Docsy community, they recommended a different approach as detailed [here](https://www.docsy.dev/docs/updating/convert-site-to-module/)
3. Did mkdir docsy.
4. Ran `go mod tidy/vendor` after `hugo mod init` and `hugo mod get` as outlined in the Docsy documentation.
5. While I've resolved most of the issues, I'm still facing the following error with the site-server and hugo server:

```
Error: command error: failed to load modules: failed to list modules: failed to execute 'go [list -m -json all]': failed to execute binary "go" with args [list -m -json all]: go: can't compute 'all' using the vendor directory
	(Use -mod=mod or -mod=readonly to bypass.)
 *errors.errorString
```

Could you review this and suggest any fixes?

**Comment by markmandel** [comment]
Looks like Hugo has changed since last I looked at it!

Two questions:

1. What if we just update Hugo first, then do Docsy second? Does anything break / need fixing? Wondering if doing this in two steps is easier than doing it all one go?
2. Out of curiosity any reason we're using Hugo [v0.118.2](https://github.com/gohugoio/hugo/releases/tag/v0.118.2) ?

**Comment by Kalaiselvi84** [comment]
> * What if we just update Hugo first, then do Docsy second? Does anything break / need fixing? Wondering if doing this in two steps is easier than doing it all one go?

I'll create separate PRs for the Hugo and Docsy upgrades.

> * Out of curiosity any reason we're using Hugo [v0.118.2](https://github.com/gohugoio/hugo/releases/tag/v0.118.2) ?

I chose to use Hugo v0.117.0 when I began the upgrade process because it was the latest version available at that time. However,  v0.118.2 was released last week. Will update it with 0.118.2. Please let me know your preference?

**Comment by deining** [comment]
>     5. While I've resolved most of the issues, I'm still facing the following error with the site-server and hugo server:
> ```
> Error: command error: failed to load modules: failed to list modules: failed to execute 'go [list -m -json all]': failed to execute binary "go" with args [list -m -json all]: go: can't compute 'all' using the vendor directory
> 	(Use -mod=mod or -mod=readonly to bypass.)
>  *errors.errorString
> ```
> 
> Could you please review this and suggest any fixes?

What you are experiencing is neither a hugo nor a docsy issue. You don't have `go` language  installed in your docker environment, that's why you are in trouble here. Install `go` in your docker environment and you will be fine.

**Explanation**: This is due to the fact that docsy theme is now installed as hugo module. When installing theme components as hugo module, `go` language is needed.

**Comment by Kalaiselvi84** [comment]
> What you are experiencing is neither a hugo nor a docsy issue. You don't have `go` language installed in your docker environment, that's why you are in trouble here. Install `go` in your docker environment and you will be fine.
> 
> **Explanation**: This is due to the fact that docsy theme is now installed as hugo module. When installing theme components as hugo module, `go` language is needed.

We already have installed `go` in our [Dockerfile](https://github.com/googleforgames/agones/pull/3363/files#diff-686b06cb4b89c224b0df5f76fa2bbc7b5757477074e6917a21b8040a9e6857a4R24-R30)🤔

**Pull request closed without merging**
