### PR TITLE
Update the instructions for installing a GKE cluster with terraform to disable automatic node upgrades

### PR DESCRIPTION
**Pull request by roberthbailey**
This is the second part of #1137.

/assign @markmandel

### CODE REVIEW

**Comment by markmandel** [comment]
This looks good to me - @aLekSer can you check the terraform bits real quick, just because you know TF way better than I do.

**Comment by aLekSer** [comment]
Now terraform config looks much better.
Approving these changes also.

**Comment by markmandel** [comment]
@roberthbailey I'm leaning towards merging this after 1.1.0 stable, just because it changes actual code -- but what do you think? I could also be persuaded to merge this now?

**Comment by roberthbailey** [comment]
> what do you think?

I'd lean towards doing it now, before the release cut. 

The terraform example always pulls the cluster.tf file from the master branch (`source = "git::https://github.com/googleforgames/agones.git//build/?ref=master"`) so even if you merge later, running the example will pick up the changes to disable node auto updates. 

Then what's missing is the documentation updates and the updates to the example. The documentation updates could be guarded behind the 1.2 release and the example changes would be visible in the master branch but not on the release branch.

**Pull request merged**
