### PR TITLE
Label for Edited PRs

### PR DESCRIPTION
**Pull request by Kalaiselvi84**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, press enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking
> /kind bug
/kind cleanup
> /kind documentation
> /kind feature
> /kind hotfix
> /kind release

**What this PR does / Why we need it**:

**Which issue(s) this PR fixes**:

Closes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by gongmax — COMMENTED** [review]
What's the context of the change? 
So before the change, the action will be triggered on three different types of activities: opened, synchronize, and reopened, by default. With this change, synchronize and reopened will be dropped. Is this expected?

**Comment by Kalaiselvi84** [comment]
> What's the context of the change? So before the change, the action [will be triggered on three different types of activities: opened, synchronize, and reopened, by default](https://frontside.com/blog/2020-05-26-github-actions-pull_request/). With this change, synchronize and reopened will be dropped. Is this expected?

I was in a dilemma to open this PR. Looks like GitHub action bot takes more time to apply the edited label to a PR. I have modified the [Add feature template PR](https://github.com/googleforgames/agones/pull/3561) to `kind/feature` around noon and bot updated it after 4:30 hours. If this PR isn't necessary, I will close it.👍🏻

**Comment by markmandel** [comment]
@Kalaiselvi84 can you explain the scenario you are trying to fix? Is it when someone edits the **What type of PR is this** section after it's been created?

**Comment by Kalaiselvi84** [comment]
@markmandel, I observed that when we edit the PR body to include a new label, the labeler doesn’t update immediately. Instead, it takes a longer time to reflect the updates. Therefore, I drafted this PR to explicitly mention the types. What could be the reason for this delay?

**Comment by markmandel** [comment]
> What could be the reason for this delay?

No idea to be honest!

**Comment by gongmax** [comment]
I tried on the website generated by https://github.com/googleforgames/agones/pull/3561 to create a documentation issue, and I saw the labels were added to the issue immediately.  So maybe it was just a transient issue with the bot?

**Comment by Kalaiselvi84** [comment]
> I tried on the website generated by #3561 to create a documentation issue, and I saw the labels were added to the issue immediately. So maybe it was just a transient issue with the bot?

Yes, it seems like a transient issue. I'll go ahead and close this PR.👍🏻

**Pull request closed without merging**
