### PR TITLE
$(ALPHA_FEATURE_GATES) on gcloud-terraform-install

### PR DESCRIPTION
**Pull request by markmandel**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking
> /kind bug

/kind cleanup

> /kind documentation
> /kind feature
> /kind hotfix

**What this PR does / Why we need it**:

Minor cleanup to use the feature gate variable in the Terraform make commands.

**Which issue(s) this PR fixes**:

None

**Special notes for your reviewer**:
None

### CODE REVIEW

**Comment by markmandel** [comment]
Flaky conformance test failure:
```
{"message":"Could not find a request which was expected","request":"ready","sdkName":"go","severity":"error","source":"*sdkserver.LocalSDKServer","time":"2020-06-30T20:11:05.994958286Z"}
{"expected":["ready","allocate","setlabel","setannotation","gameserver","health","shutdown","watch","reserve"],"message":"Testing Failed","received":[],"sdkName":"go","severity":"info","source":"*sdkserver.LocalSDKServer","time":"2020-06-30T20:11:05.995053002Z"}
```

**Comment by markmandel** [comment]
Ooh, that's a new one!

```
time="2020-06-30 20:23:51.038" level=info msg="Starting e2e test(s)" featureGates="ContainerPortAllocation=false&Example=true&PlayerTracking=true&SDKWatchSendOnExecute=true" gameServerImage="gcr.io/agones-images/udp-server:0.21" namespace= perfOutputDir= pullSecret= stressTestLevel=0 version=
time="2020-06-30 20:23:51.146" level=error msg="failed to cleanup e2e namespaces" error="deleting namespace 1593548327 failed: Operation cannot be fulfilled on namespaces \"1593548327\": The system is ensuring all content is removed from this namespace.  Upon completion, this namespace will automatically be purged by the system."
FAIL	agones.dev/agones/test/e2e	0.176s
FAIL
Makefile:254: recipe for target 'test-e2e-integration' failed
```

**Comment by roberthbailey** [comment]
Do we do a one-shot call to delete the namespace? Or do we call delete and then wait (up to some timeout) for it to disappear?

**Comment by markmandel** [comment]
> Do we do a one-shot call to delete the namespace? Or do we call delete and then wait (up to some timeout) for it to disappear?

I reuse this function: https://github.com/googleforgames/agones/blob/master/test/e2e/framework/framework.go#L566

It will default to background delete though. I expect there is an error type if you try and delete a namespace that is in the process of being deleted, and we can ignore that.

**Comment by markmandel** [comment]
Ah!

`time="2020-07-01 00:17:11.915" level=error msg="failed to cleanup e2e namespaces" error="deleting namespace 1593562346 failed: Operation cannot be fulfilled on namespaces \"1593562346\": The system is ensuring all content is removed from this namespace.  Upon completion, this namespace will automatically be purged by the system."
FAIL	agones.dev/agones/test/e2e	0.603s
FAIL`

Fix for that soon!

**Comment by markmandel** [comment]
Same thing - exits after 10 minutes, some kind of deadlock:

grep Test
```
agones.dev/agones/pkg/sdkserver.TestLocalSDKServerPlayerCapacity
agones.dev/agones/pkg/sdkserver.TestLocalSDKServerPlayerCapacity.func1(0xc0008480d0, 0xc00069a0c8, 0xc000540a20)
agones.dev/agones/pkg/sdkserver.TestLocalSDKServerPlayerConnectAndDisconnect.func2
agones.dev/agones/pkg/sdkserver.TestLocalSDKServerPlayerConnectAndDisconnect.func2
agones.dev/agones/pkg/sdkserver.TestLocalSDKServerPlayerConnectAndDisconnect.func2
agones.dev/agones/pkg/sdkserver.TestLocalSDKServerPlayerConnectAndDisconnect.func2
agones.dev/agones/pkg/sdkserver.TestLocalSDKServerPlayerConnectAndDisconnect.func2
agones.dev/agones/pkg/sdkserver.TestLocalSDKServerPlayerConnectAndDisconnect.func2
agones.dev/agones/pkg/sdkserver.TestLocalSDKServerPlayerConnectAndDisconnect.func2.1(0xc00044f6c0, 0xc000532020, 0xc000287680)
agones.dev/agones/pkg/sdkserver.TestLocalSDKServerPlayerConnectAndDisconnect.func2.1(0xc00054a8f0, 0xc0005321e0, 0xc0000d4360)
agones.dev/agones/pkg/sdkserver.TestLocalSDKServerPlayerConnectAndDisconnect.func2.1(0xc000348820, 0xc000532188, 0xc000489560)
agones.dev/agones/pkg/sdkserver.TestLocalSDKServerPlayerConnectAndDisconnect.func2.1(0xc000a1cf70, 0xc000010118, 0xc000a1e360)
agones.dev/agones/pkg/sdkserver.TestLocalSDKServerPlayerConnectAndDisconnect.func2.1(0xc000abf860, 0xc000532328, 0xc000ac2360)
agones.dev/agones/pkg/sdkserver.TestLocalSDKServerPlayerConnectAndDisconnect.func2.1(0xc000ac6680, 0xc000532338, 0xc000ac2ea0)
agones.dev/agones/pkg/sdkserver.TestLocalSDKServerWatchGameServer
agones.dev/agones/pkg/sdkserver.TestLocalSDKServerWatchGameServer.func1(0xc000480b60, 0xc0001188a0, 0xc000644000, 0xc000540900)
agones.dev/agones/pkg/sdkserver.TestSDKServerWatchGameServer(0xc000276120)
```

grep _test
```
	/go/src/agones.dev/agones/pkg/sdkserver/localsdk_test.go:264 +0x2c6
	/go/src/agones.dev/agones/pkg/sdkserver/localsdk_test.go:265 +0x5d
	/go/src/agones.dev/agones/pkg/sdkserver/localsdk_test.go:308 +0x334
	/go/src/agones.dev/agones/pkg/sdkserver/localsdk_test.go:309 +0x92
	/go/src/agones.dev/agones/pkg/sdkserver/localsdk_test.go:418 +0x241
	/go/src/agones.dev/agones/pkg/sdkserver/localsdk_test.go:418 +0x241
	/go/src/agones.dev/agones/pkg/sdkserver/localsdk_test.go:418 +0x241
	/go/src/agones.dev/agones/pkg/sdkserver/localsdk_test.go:418 +0x241
	/go/src/agones.dev/agones/pkg/sdkserver/localsdk_test.go:418 +0x241
	/go/src/agones.dev/agones/pkg/sdkserver/localsdk_test.go:418 +0x241
	/go/src/agones.dev/agones/pkg/sdkserver/localsdk_test.go:419 +0x92
	/go/src/agones.dev/agones/pkg/sdkserver/localsdk_test.go:419 +0x92
	/go/src/agones.dev/agones/pkg/sdkserver/localsdk_test.go:419 +0x92
	/go/src/agones.dev/agones/pkg/sdkserver/localsdk_test.go:419 +0x92
	/go/src/agones.dev/agones/pkg/sdkserver/localsdk_test.go:419 +0x92
	/go/src/agones.dev/agones/pkg/sdkserver/localsdk_test.go:419 +0x92
	/go/src/agones.dev/agones/pkg/sdkserver/sdkserver_test.go:658 +0x278
	/go/src/agones.dev/agones/pkg/sdkserver/sdkserver_test.go:1251 +0x86
	/go/src/agones.dev/agones/pkg/sdkserver/sdkserver_test.go:1252 +0x78
	/go/src/agones.dev/agones/pkg/sdkserver/sdkserver_test.go:1259 +0x6b
	/go/src/agones.dev/agones/pkg/sdkserver/sdkserver_test.go:1259 +0x6b
	/go/src/agones.dev/agones/pkg/sdkserver/sdkserver_test.go:1259 +0x6b
	/go/src/agones.dev/agones/pkg/sdkserver/sdkserver_test.go:1260 +0x93
	/go/src/agones.dev/agones/pkg/sdkserver/sdkserver_test.go:1260 +0x93
	/go/src/agones.dev/agones/pkg/sdkserver/sdkserver_test.go:1260 +0x93
```

https://github.com/googleforgames/agones/pull/1662#issuecomment-652041201 has a similar stack

**Comment by aLekSer** [comment]
@akremsa , this was recently added, PTAL:
```
--- FAIL: TestSDKServerWatchGameServerFeatureSDKWatchSendOnExecute (9.33s)
    sdkserver_test.go:722: No gameserver in the stream, moving on.
    sdkserver_test.go:728: 
        	Error Trace:	sdkserver_test.go:728
        	Error:      	Not equal: 
        	            	expected: 2
        	            	actual  : 1
        	Test:       	TestSDKServerWatchGameServerFeatureSDKWatchSendOnExecute
```

**Pull request merged**
