### PR TITLE
Docs: Fold Sidebar-Menu

### PR DESCRIPTION
**Pull request by Kalaiselvi84**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, press enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking
> /kind bug
> /kind cleanup
> /kind documentation
> /kind feature
> /kind hotfix
> /kind release

**What this PR does / Why we need it**:

**Which issue(s) this PR fixes**:

Closes #

**Special notes for your reviewer**:
This change will fold the sidebar menu of the Agones docs, following the instructions at https://www.docsy.dev/docs/adding-content/navigation/#section-menu-options. Please share your thoughts..

### CODE REVIEW

**Comment by markmandel** [comment]
So we tried this a while ago - and found it was a really bad experience for end users, since they couldn't find anything in the nav bar -- so we rolled it back. So I don't think we should be doing this.

**Comment by Kalaiselvi84** [comment]
Thanks for letting me know about the previous attempt and the user experience. I'm okay to close this PR.

**Comment by Kalaiselvi84** [comment]
@markmandel sorry, I am not fully convinced.. How about we merge this PR and see if the user experiences any unexpected behavior?

**Comment by Kalaiselvi84** [comment]
Considering the recent upgrades to Hugo and Docsy, there is a possibility that the changes may function as expected??

**Comment by markmandel** [comment]
See: https://github.com/googleforgames/agones/pull/2204

**Pull request closed without merging**
