### PR TITLE
Update Nodejs Apt Repository to latest

### PR DESCRIPTION
**Pull request by Kalaiselvi84**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, press enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking
> /kind bug
> /kind cleanup
> /kind documentation
> /kind feature
> /kind hotfix
> /kind release

**What this PR does / Why we need it**:

**Which issue(s) this PR fixes**:

Work on #3430 

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by Kalaiselvi84** [comment]
A new image tag has been pushed to my project: 
https://screenshot.googleplex.com/8Z3bfUUAxKikGH8

Build log - https://gist.github.com/Kalaiselvi84/5996617343f683ba82d1e06a0425e17a

Please confirm whether I can proceed with pushing the new image to production.

**Comment by Kalaiselvi84** [comment]
Drafted the PR. Sorry, I'm aware that you're currently testing the removal of the Node.js dependency. Please take your time, and kindly let me know when it's appropriate to open this PR and proceed with pushing the image to production.🙂

**Comment by markmandel** [comment]
> Drafted the PR. Sorry, I'm aware that you're currently testing the removal of the Node.js dependency. Please take your time, and kindly let me know when it's appropriate to open this PR and proceed with pushing the image to production.🙂

Nope - all good - please go ahead with this PR when ready. No order of operations required here.

Also (mention this on https://github.com/googleforgames/agones/issues/3430), would love for you to test the removal of the nodejs dependency, but that's far lower priority now things are working again.

**Review by markmandel — APPROVED** [review]
Ready when you are 👍🏻

**Review by steven-supersolid — APPROVED** [review]

**Pull request merged**
