### PR TITLE
Bumps cpp-simple Image and Refactoring Example Makefiles

### PR DESCRIPTION
**Pull request by Kalaiselvi84**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, press enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking
> /kind bug
> /kind cleanup
> /kind documentation
> /kind feature
> /kind hotfix
> /kind release

**What this PR does / Why we need it**:

**Which issue(s) this PR fixes**:

Closes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by markmandel** [comment]
Do you want this before or after release?

**Comment by Kalaiselvi84** [comment]
> Do you want this before or after release?

No preference, I am fine with anything. Your choice.😀

**Comment by markmandel** [comment]
I'll leave it to after - less complicated that way.

**Comment by roberthbailey** [comment]
The title of this PR doesn't seem to match what you've changed (most of which is some refactoring of the example makefiles). Could you update the title and/or split into separate pull requests?

**Review by roberthbailey — APPROVED** [review]

**Pull request merged**
