### PR TITLE
Updated Go to 1.14.12

### PR DESCRIPTION
**Pull request by markmandel**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking
> /kind bug

/kind cleanup

> /kind documentation
> /kind feature
> /kind hotfix

**What this PR does / Why we need it**:

Security fixes really.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:
Specifically didn't upgrade to 1.15.x due to issues with SSL certificates on fleet autoscaler webhooks. See #1897.

I've also not incremented example image versions, since I figured this wasn't a breaking change, and the new version could be picked up as other changes happen to those images.

### CODE REVIEW

**Comment by roberthbailey** [comment]
> I've also not incremented example image versions, since I figured this wasn't a breaking change, and the new version could be picked up as other changes happen to those images.

If this is to pick up security fixes, shouldn't we rebuild and push new images (with the next release)? Otherwise, what is the point of updating the go version. Something like the supertuxcart example image, which isn't under active development isn't going to get a new version on its own any time soon. And things like the simple-game-server aren't likely to be changed but are used in all of our examples and it would be good to have users running a secured version.

**Review by roberthbailey — APPROVED** [review]
Code changes look good, just want to resolve the question about container image versions.

**Comment by markmandel** [comment]
> If this is to pick up security fixes, shouldn't we rebuild and push new images (with the next release)? Otherwise, what is the point of updating the go version. Something like the supertuxcart example image, which isn't under active development isn't going to get a new version on its own any time soon. And things like the simple-game-server aren't likely to be changed but are used in all of our examples and it would be good to have users running a secured version.

If I'm honest, I didn't do it, because it's a lot of busywork, and the security of an example images doesn't seem to me to be a huge priority? So figured, it would be taken care of on a best effort basis, rather than being a blocker for a release.

SuperTuxKart should actually get updated - a new version came out a little while ago, I believe with the AI connection fixes. I don't think Xonotic has though.

**Comment by roberthbailey** [comment]
That's fair. How about filing a help-wanted issue to update the example images? Collecting the list of things that need to be rebuilt would be pretty straightforward.

**Comment by markmandel** [comment]
Sounds like a plan - do we restart https://github.com/googleforgames/agones/issues/1261 or start a new one? :smile:

**Comment by roberthbailey** [comment]
That issue is sooooo close.... But since it's already open, I think we should just re-use it.

**Comment by markmandel** [comment]
How's this?
https://github.com/googleforgames/agones/issues/1261#issuecomment-729176894

**Comment by roberthbailey** [comment]
>How's this?
> #1261 (comment)

Great. Thanks!

**Pull request merged**
