### PR TITLE
Changing update list to update list values along with the capacity.

### LINKED ISSUE #3870: Beta: UpdateList using Agones 1.41 rest API doesn't update the data in the selected list
**What happened**:
Attempting to use the Lists features in Agones 1.41. I have a fleet deployed in agones and am attempting to use the:

`curl -d '{"capacity": "120", "values": ["player3", "player4"]}' -H "Content-Type: application/json" -X PATCH http://localhost:${AGONES_SDK_HTTP_PORT}/v1beta1/lists/players`

call as mentioned in the rest documentation. The list is declared on our "kind: Fleet" resource and declares a list players

```
lists:
  players:
    capacity: 20
    values:
    - player1
    - player2
    - player3
```

Once the fleet is deployed, I can run the command:

`curl -H "Content-Type: application/json" -X GET http://localhost:${AGONES_SDK_HTTP_PORT}/v1beta1/lists/players`

and will get the correct response.

`{"name":"players","capacity":"20","values":["player1","player2","player3"]}`

When I go to update that same list using the command:

`curl -d '{"capacity": "20", "values": ["player3", "player4"]}' -H "Content-Type: application/json" -X PATCH http://localhost:${AGONES_SDK_HTTP_PORT}/v1beta1/lists/players`

I get the response:

`{"name":"","capacity":"0","values":[]}`

I then check again to see if my list was updated:

`curl -H "Content-Type: application/json" -X GET http://localhost:${AGONES_SDK_HTTP_PORT}/v1beta1/lists/players`

but the reply seems to indicate nothing has changed.

`{"name":"players","capacity":"20","values":["player1","player2","player3"]}`

**What you expected to happen**:

I expected the list up update to reflect the data payload of 

`{"capacity": "20", "values": ["player3", "player4"]}`

**How to reproduce it (as minimally and precisely as possible)**:

Create a Fleet resource in agones and deploy it with a list declared as:

```
lists:
  players:
    capacity: 20
    values:
    - player1
    - player2
    - player3
```

shell into a game server in the fleet just deployed and verify that your initial values are in the list

```
curl -H "Content-Type: application/json" -X GET http://localhost:${AGONES_SDK_HTTP_PORT}/v1beta1/lists/players

{"name":"players","capacity":"20","values":["player1","player2","player3"]}
```

Attempt to update the list with new values

`curl -d '{"capacity": "20", "values": ["player3", "player4"]}' -H "Content-Type: application/json" -X PATCH http://localhost:${AGONES_SDK_HTTP_PORT}/v1beta1/lists/players`

after running the update list call, confirm that the list has not changed

```
curl -H "Content-Type: application/json" -X GET http://localhost:${AGONES_SDK_HTTP_PORT}/v1beta1/lists/players

{"name":"players","capacity":"20","values":["player1","player2","player3"]}
```

**Anything else we need to know?**:

**Environment**:
- Agones version: 1.41
- Kubernetes version (use `kubectl version`): 1.29 
- Cloud provider or hardware configuration: AWS EKS
- Install method (yaml/helm): Helm
- Troubleshooting guide log(s): 
- Others:

### PR DESCRIPTION
**Pull request by chrisfoster121**
/kind bug 

**What this PR does / Why we need it**:
This PR updates the UpdateList functionality to update the list values along side the given capacity. This is very important because without it managing game server keys gets very complicated and often causes unwanted race conditions when sending multiple additions or removals to lists in quick succession.

**Which issue(s) this PR fixes**:
Closes #3870

### CODE REVIEW

**Comment by chrisfoster121** [comment]
@igooch This built locally but it looks like the cloud build failed. I am unable to view the logs:
``````

**Comment by igooch** [comment]
Looks like it's failing on `make test`

```
            	Test:       	TestSDKServerUpdateList/set_capacity_to_max
            	            	  }
            	            	+ Values: ([]string) {
            	            	-  (string) (len=4) "four"
            	            	-  (string) (len=5) "three",
            	            	-  (string) (len=3) "two",
            	            	-  (string) (len=3) "one",
            	            	- Values: ([]string) (len=4) {
            	            	  Capacity: (int64) 1000,
            	            	@@ -2,7 +2,3 @@
            	            	+++ Actual
            	            	--- Expected
            	            	Diff:
            	            	
            	            	actual  : v1.ListStatus{Capacity:1000, Values:[]string{}}
            	            	expected: v1.ListStatus{Capacity:1000, Values:[]string{"one", "two", "three", "four"}}
            	Error:      	Not equal: 
            	Error Trace:	/go/src/agones.dev/agones/pkg/sdkserver/sdkserver_test.go:1807
        sdkserver_test.go:1807: 
            	Test:       	TestSDKServerUpdateList/set_capacity_to_max
            	            	 }
            	            	+([]string) {
            	            	- (string) (len=4) "four"
            	            	- (string) (len=5) "three",
            	            	- (string) (len=3) "two",
            	            	- (string) (len=3) "one",
            	            	-([]string) (len=4) {
            	            	@@ -1,6 +1,2 @@
            	            	+++ Actual
            	            	--- Expected
            	            	Diff:
            	            	
            	            	actual  : []string{}
            	            	expected: []string{"one", "two", "three", "four"}
            	Error:      	Not equal: 
            	Error Trace:	/go/src/agones.dev/agones/pkg/sdkserver/sdkserver_test.go:1799
        sdkserver_test.go:1799: 
    --- FAIL: TestSDKServerUpdateList/set_capacity_to_max (1.11s)
--- FAIL: TestSDKServerUpdateList (43.96s)
```

**Comment by igooch** [comment]
You need to be in https://groups.google.com/a/google.com/g/agones-discuss to get access to the build logs. 

Also looks like you're missing the CLA.

**Comment by chrisfoster121** [comment]
> Looks like it's failing on `make test`
> 
> ```
>             	Test:       	TestSDKServerUpdateList/set_capacity_to_max
>             	            	  }
>             	            	+ Values: ([]string) {
>             	            	-  (string) (len=4) "four"
>             	            	-  (string) (len=5) "three",
>             	            	-  (string) (len=3) "two",
>             	            	-  (string) (len=3) "one",
>             	            	- Values: ([]string) (len=4) {
>             	            	  Capacity: (int64) 1000,
>             	            	@@ -2,7 +2,3 @@
>             	            	+++ Actual
>             	            	--- Expected
>             	            	Diff:
>             	            	
>             	            	actual  : v1.ListStatus{Capacity:1000, Values:[]string{}}
>             	            	expected: v1.ListStatus{Capacity:1000, Values:[]string{"one", "two", "three", "four"}}
>             	Error:      	Not equal: 
>             	Error Trace:	/go/src/agones.dev/agones/pkg/sdkserver/sdkserver_test.go:1807
>         sdkserver_test.go:1807: 
>             	Test:       	TestSDKServerUpdateList/set_capacity_to_max
>             	            	 }
>             	            	+([]string) {
>             	            	- (string) (len=4) "four"
>             	            	- (string) (len=5) "three",
>             	            	- (string) (len=3) "two",
>             	            	- (string) (len=3) "one",
>             	            	-([]string) (len=4) {
>             	            	@@ -1,6 +1,2 @@
>             	            	+++ Actual
>             	            	--- Expected
>             	            	Diff:
>             	            	
>             	            	actual  : []string{}
>             	            	expected: []string{"one", "two", "three", "four"}
>             	Error:      	Not equal: 
>             	Error Trace:	/go/src/agones.dev/agones/pkg/sdkserver/sdkserver_test.go:1799
>         sdkserver_test.go:1799: 
>     --- FAIL: TestSDKServerUpdateList/set_capacity_to_max (1.11s)
> --- FAIL: TestSDKServerUpdateList (43.96s)
> ```

I am looking at that now and I see the following:

````
"set capacity to max": {
			listName: "foo",
			request: &beta.UpdateListRequest{
				List: &beta.List{
					Name:     "foo",
					Capacity: int64(1000),
				},
				UpdateMask: &fieldmaskpb.FieldMask{Paths: []string{"capacity"}},
			},
			want:                    agonesv1.ListStatus{Values: []string{"one", "two", "three", "four"}, Capacity: int64(1000)},
			updateErr:               false,
			updated:                 true,
			expectedUpdatesQueueLen: 0,
		},
````

If I am not mistaken it looks like the test is expecting the return to have values associated with it. In all my testing of the agones SDK I have not been able to get any update list call to return the correct data. I think this is due to the fact that this gets put into a queue to get processed asynchronously, for example [RemoveListValue](https://github.com/googleforgames/agones/blob/31ed93ee9c0c3070a1139b145d0d6debac8b4572/pkg/sdkserver/sdkserver.go#L1174) also returns an empty object.

Would adjusting the test to match this pattern be a reasonable approach?

**Comment by igooch** [comment]
The test is failing on lines `Error Trace:	/go/src/agones.dev/agones/pkg/sdkserver/sdkserver_test.go:1807` and `Error Trace:	/go/src/agones.dev/agones/pkg/sdkserver/sdkserver_test.go:1799`. 

These are checking that the values from GetList and the K8s API are as expected after the update. An important line in the test is `UpdateMask: &fieldmaskpb.FieldMask{Paths: []string{"capacity"}},` which means that the request is only updating the capacity, and not the list values, so the list values should not change. 

https://github.com/googleforgames/agones/blob/31ed93ee9c0c3070a1139b145d0d6debac8b4572/pkg/sdkserver/sdkserver_test.go#L1797-L1800
https://github.com/googleforgames/agones/blob/31ed93ee9c0c3070a1139b145d0d6debac8b4572/pkg/sdkserver/sdkserver_test.go#L1805-L1809

From taking a quick look at your code it doesn't use the [fieldMask](https://google.aip.dev/161) values. You can take a look at the [localsdkserver code](https://github.com/googleforgames/agones/blob/31ed93ee9c0c3070a1139b145d0d6debac8b4572/pkg/sdkserver/localsdk.go#L716-L768) which uses the field masks.

**Pull request closed without merging**
