### PR TITLE
Update allocator-service.md

### PR DESCRIPTION
**Pull request by freegroup**
fixes https://github.com/googleforgames/agones/issues/2390

---
Please notice, that I'm not a native speaker. Review is heavily recommended

### CODE REVIEW

**Comment by roberthbailey** [comment]
@pooneh-m - Since you added support for multi-cluster allocation, can you review this documentation change? Thanks!

**Comment by roberthbailey** [comment]
@freegroup - it looks like the CLA bot is failing. Have you signed the CLA?

**Comment by freegroup** [comment]
I already signed the CLA. Other pull requests accept them. Maybe you must run the validation check again?

Screen Shot 2021-12-29 at 08 40 10

**Comment by roberthbailey** [comment]
I re-ran the check and it seems happy now. Thanks!

**Comment by markmandel** [comment]
Thanks for the submission! - but I'm not quite 100% sure what the aim of the documentation change is here. If you could please expand some more on your step and the confusion you originally faced, I expect we can improve things considerably 👍🏻 

Some comments/questions as well, so hopefully this helps:

> You can communicate with the Agones controller via the kubernetes API and the agones CRD's. This way, you don't have the feature set offered by a multi cluster setups.

I think we can drop this statement, since:
1. The fact there is communication with the controller, I'm not sure is relevant to the functionality of what is being done, so likely just confuses the point.
2. We cover reasons for using the kubernetes api vs the service [already here](https://agones.dev/site/docs/advanced/allocator-service/#gameserverallocation-vs-allocator-service), and in more detail.

With the extra comments on `GameServerAllocationPolicy` - I'm assuming that the documentation at https://agones.dev/site/docs/advanced/multi-cluster-allocation/#define-cluster-priority was not clear? Can you expand on the confusion?

**Comment by markmandel** [comment]
I'm going to mark this PR as stale, and if it isn't being worked on currently, we can close it .

If you still have time to work on it, and want to discuss the issues you faced with the documentation, please feel free to come back to it, or reopen if it gets closed.

**Pull request closed without merging**
