### PR TITLE
Changed cmake required version to 3.5 to work on more machines

### PR DESCRIPTION
**Pull request by devjgm**
The current cmake files don't actually *require* 3.13, so lowering the version they claim to require will allow the cmake files to work on more machines. Related to #718

### CODE REVIEW

**Comment by dsazonoff** [comment]
I don't think that cmake version should be downgraded. It is very easy to upgrade it. And SDK supports docker build, so it doesn't matter for a machine what version to have.
There was a request from @markmandel to silent CMake output and there was a bug in older versions of CMake when output was not silenced for some platforms. If necessary, I can find an issue in cmake bugtracker. But it is not critical.

Don't forget to patch 'cpp/cmake/clang-verify.in' file and Dockerfile that are responsible for SDK builds (installation of CMake).

**Comment by devjgm** [comment]
> I don't think that cmake version should be downgraded. It is very easy to upgrade it.

My distro is using a debian mirror that's slightly behind, and the newest cmake I can get is 3.12.1. So my only choice is to either: (A) download cmake from kitware.com (yuck), or (B) edit the "cmake_minimum_required" version to something slightly lower, which works fine.

FTR, we choose to require cmake 3.5 for https://github.com/googleapis/google-cloud-cpp because it's *easily* available on a large variety of important Linux distros, and it actually has most of the major modern features that people want/need with cmake. 
 
> And SDK supports docker build, so it doesn't matter for a machine what version to have.

Are there instructions for that? Because running `make`, as I did, used my locally installed cmake and did not use docker.

> Don't forget to patch 'cpp/cmake/clang-verify.in' file and Dockerfile that are responsible for SDK builds (installation of CMake).

I'm sorry, but I don't see any mention of `clang-verify.in`. Can you please provide a few more details or point me at the documentation? Thanks.

**Comment by dsazonoff** [comment]
Now I agree about downgrading cmake version.
>Are there instructions for that? Because running make, as I did, used my locally installed cmake and did not use docker.

You may look [here](https://github.com/googleforgames/agones/tree/master/build/build-sdk-images). Or [here](https://github.com/googleforgames/agones/blob/master/examples/cpp-simple/Makefile). But I usually build everything locally, without docker.
I was talking about this [Dockerfile](https://github.com/googleforgames/agones/blob/master/build/build-sdk-images/cpp/Dockerfile#L21). I was wrong in my previous comment. I think we should downgrade cmake version in CMakeLists.txt files, but keep use v3.14 in docker build. So minimal supported version will be 3.5, but cloud build will use 3.14.

>I'm sorry, but I don't see any mention of clang-verify.in

I noticed that you created your PR before #855 was merged.

Please, update from master and fix cmake version in [clang-verify](https://github.com/googleforgames/agones/blob/master/sdks/cpp/cmake/clang-verify.in#L15) too.
Other things are fine.

**Comment by devjgm** [comment]
Updated. Requiring 3.5 but using 3.14 in Docker sounds like a good idea to me.

**Comment by roberthbailey** [comment]
@devjgm - should we also update https://github.com/googleforgames/agones/blob/master/examples/cpp-simple/CMakeLists.txt to specify cmake 3.5?

**Comment by devjgm** [comment]
I think so, yes. I didn't know "examples/cpp-simple" existed, otherwise I'd have updated it. But I see no reason for it to be different. Thanks for pointing this out.

**Pull request merged**
