### PR TITLE
Bump examples/crd-client

### PR DESCRIPTION
**Pull request by Kalaiselvi84**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, press enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking
> /kind bug

/kind cleanup

> /kind documentation
> /kind feature
> /kind hotfix
> /kind release

**What this PR does / Why we need it**:

**Which issue(s) this PR fixes**:

Closes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by markmandel** [comment]
That's a new flake, will keep an eye out.

```
--- FAIL: TestMultiClusterAllocationFromRemote (13.30s)
    --- FAIL: TestMultiClusterAllocationFromRemote/Handle_allocation_request_remotely (0.10s)
        controller_test.go:451: 
            	Error Trace:	/go/src/agones.dev/agones/pkg/gameserverallocations/controller_test.go:451
            	Error:      	Received unexpected error:
            	            	json: cannot unmarshal string into Go struct field GameServerAllocation.status of type v1.GameServerAllocationStatus
            	Test:       	TestMultiClusterAllocationFromRemote/Handle_allocation_request_remotely
```

**Review by markmandel — COMMENTED** [review]
Looks just - just to confirm before approving - you've testing building the image, and the image get's built?

**Comment by Kalaiselvi84** [comment]
> Looks just - just to confirm before approving - you've testing building the image, and the image get's built?

Yes, the build and push processes for the `crd-client` image have succeeded.🙂

https://gist.github.com/Kalaiselvi84/8e6ff111db46918ac0826151653964f3

 https://screenshot.googleplex.com/AHYSmqcsGNMLFmX

**Comment by Kalaiselvi84** [comment]
Production now has the new tag for the `crd-client` image.

https://screenshot.googleplex.com/5bzQva4NGJuv79p

**Pull request merged**
