### PR TITLE
#54 Preliminary Windows Image Support

### LINKED ISSUE #54: Running windows game server
Game production usually works on windows first then port to linux eventually at the end of the development. Having windows support would help the adoption rate.

What does it takes to run a windows game server ?

- We should find a way to detect that the game server resource is windows ? May be a resource parameter ?
- Does windows support sidecar concept ? Apparently from [here at the bottom](http://blog.kubernetes.io/2017/09/windows-networking-at-parity-with-linux.html) it says windows support only one container per pod, but should work on windows server 1709. We should try it.
- If yes, create a sidecar using [windows nano](https://hub.docker.com/r/microsoft/nanoserver/).
- add a windows game server example.

Testing will be difficult as windows support is still in beta since k8s 1.5 but apparently greatly improve in 1.9.

Documentation :
https://kubernetes.io/docs/getting-started-guides/windows/
http://blog.kubernetes.io/2017/09/windows-networking-at-parity-with-linux.html
https://github.com/kubernetes/community/tree/master/sig-windows
https://docs.microsoft.com/en-us/windows-server/get-started/whats-new-in-windows-server-1709

### LINKED ISSUE #110: Support Agones sidecar Windows build
Windows 1709 supports LCOW (linux container on Windows) and sharing the pod with linux and Windows containers side-by-side. Containers also share the same network namespace.

This would allow deploying Agones on a Kubernetes Windows node with the main game server in a Windows container.

However, this requires Hyper-v with nested virtualization. This makes deployment options more complicated, either on-prem or on external providers. Some compute providers supports 1709 Windows images, but it's not clear which ones support nested virtualization.

Agones sidecar doesn't seem to have much assumptions about running on a linux node.

Ideally, the sidecar should be cross-platform and also have a Windows build version, using either `microsoft/windowsservercore:1709` or `microsoft/nanoserver:1709`.

Some limitations right now is that service account tokens do not work well on Windows containers, so this needs to be resolved to have the token injected correctly by kubelet:

https://github.com/kubernetes/kubernetes/issues/52419

This issue is related to the Windows support discussed here #54

### PR DESCRIPTION
**Pull request by jeremyje**
**What type of PR is this?**
/kind feature
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking
> /kind bug
> /kind cleanup
> /kind documentation
> /kind feature
> /kind hotfix

**What this PR does / Why we need it**:
This adds some basic Windows container support to Agones.

This PR is focused on getting the Windows support in Agones started rather than be a complete PR.
There's a few changes that Agones needs to properly support Windows:

* `make WITH_WINDOWS=1` will add Windows container artifacts for sdk-server. This option is disabled by default a follow up PR will be sent to turn it on.
* Like the `sdk-server` any binaries that can run in Windows should be written to the local file system rather than in the context of a base docker container. `COPY --from` does not work between Linux and Windows container images.
* The changes here will work on Linux and should work on Google Cloud Build since they run 19.03+ (required for buildx) on the backend.
* There's a bug in buildx where the `os.platform` cannot easily be set, see https://github.com/docker/cli/pull/2578 (fixed in docker 20+). The tagged bug goes into detail but since you're only able to target 1 version of Windows I strongly suggest Windows Server 2019 (WINDOWS_LTSC).
* `WINDOWS_VERSION` was introduced to provide a set of Windows versions to target. It is set to `1809` which is aliased to `ltsc2019` (not all Windows images support the `ltsc2019` tagging).
* The `Makefile` in general will need to be updated to have image tagging for Linux container images to have the suffix `-linux_amd64`. This will allow you to have [multi-arch](https://www.docker.com/blog/multi-arch-images/) and [multi-platform](https://www.docker.com/blog/multi-platform-docker-builds/) images going forward. This means that you can use the old references for Agones (no platform/OS modifier in the tag) and it'll pull the correct image that aligns with the host.
* Windows Server container images have a strong host compatibility requirement. Windows Server 2019 (LTSC) images will NOT work on Windows Server 1909. Effectively you need to treat them as separate platforms.
* You'll need to avoid running `powershell` or `cmd` commands in your `Dockerfile.windows`. If you do this you WILL need a Windows host. The alternative is to run all the modifications in a Linux container export it to local file system (as is) and use the `COPY` command in your `Dockerfile.windows`.

**Which issue(s) this PR fixes**:

First set of changes for #54 
Fixes #110

**Special notes for your reviewer**:

The `Dockerfile.windows` naming convention is following how Kubernetes is typically introducing Windows support. There's no strong guidance there.
The `make` targets are not added to the official build. 
I did a very simple build pass to see if things compile.
The PR is very verbose and there's a lot of duplication. This is intentional, there are deeper changes to the Agones build system that are needed to properly fix them.

### CODE REVIEW

**Comment by jeremyje** [comment]
cc: @WeetA34 @markmandel

**Comment by markmandel** [comment]
@WeetA34 are you able to take this for a spin? You're probably placed as the best person to see how well it works.

**Comment by WeetA34** [comment]
Hi @markmandel 
agones-sdk 1.10.0-8d42fa4 windows image is not found
```
  Warning  Failed     11s               kubelet, gke-agones-win-windows-2e403fc4-ch0p  Failed to pull image "gcr.io/agones-images/agones-sdk:1.10.0-8d42fa4": rpc error: code = Unknown desc = image operating system "linux" cannot be used on this platform
```

**Comment by markmandel** [comment]
> Hi @markmandel
> agones-sdk 1.10.0-8d42fa4 windows image is not found
> 
> ```
>   Warning  Failed     11s               kubelet, gke-agones-win-windows-2e403fc4-ch0p  Failed to pull image "gcr.io/agones-images/agones-sdk:1.10.0-8d42fa4": rpc error: code = Unknown desc = image operating system "linux" cannot be used on this platform
> ```

Yes, you would still need to apply it to your own registry, you don't have access to the `agones-images` project.

You can see details in our development guide: https://github.com/googleforgames/agones/blob/master/build/README.md#running-a-test-google-kubernetes-engine-cluster

**Comment by WeetA34** [comment]
i thought images have been built and were available on the agones-images registry like the stable images

**Comment by markmandel** [comment]
> i thought images have been built and were available on the agones-images registry like the stable images

Given this is currently just a PR, I'm not sure how that would have happened :smile: 

If you are able to read the description of the PR, and see if it works for you to build the images as expected and you are able to use them -- would be very useful to get your feedback.

**Comment by jeremyje** [comment]
The PR will not build the Windows images by default you have to specifically run the new make file commands.

**Comment by WeetA34** [comment]
> Given this is currently just a PR, I'm not sure how that would have happened 😄
yep of course 🤦‍♂️ artifacts 🤣 

> If you are able to read the description of the PR, and see if it works for you to build the images as expected and you are able to use them -- would be very useful to get your feedback.
Ok i'll try it and use agones.image.registry helm overrides to test

**Comment by WeetA34** [comment]
> The PR will not build the Windows images by default you have to specifically run the new make file commands.
> `make push-agones-sdk-image-multi`
> 
> and run the `make push-multi-arch-image` in the simple-tcp. You'll need to override the registry as well.

Ok will try this tomorrow

**Comment by WeetA34** [comment]
Thx to both of you

**Comment by jeremyje** [comment]
You'll multiple images for the same thing. `-windows_amd64-1809` suffix for the direct image for Windows 2019. And `-multi` that will work on Linux or Windows. Try the `-windows_amd64-1809` first since that's avoiding a hop. Then try `-multi` to confirm that the image build will work crossplatform.

@markmandel I don't have really any more cycles to work on this. Can someone take this PR over?

**Comment by markmandel** [comment]
> @markmandel I don't have really any more cycles to work on this. Can someone take this PR over?

I honestly don't know anyone who has the knowledge you do here :grimacing:

**Comment by jeremyje** [comment]
@markmandel The PR in its current form won't break Agones. I can add some instructions on how to build the binaries and containers. Though it's been over a week and no one has reviewed it so it's not clear if this is a priority for Agones.

@markmandel @WeetA34 if you have a list of artifacts you want to be built on Windows I might be able to slip that in (untested).

**Comment by WeetA34** [comment]
Hello,
sorry for the delay.
I've tried to compile on my WSL.
For now, i'm investigating the following error during make push-agones-sdk-image-multi on windows part:
`auto-push is currently not implemented for docker driver`

**Comment by jeremyje** [comment]
I don't know about WSL2 but it should work in a Linux VM. I cannot test this because my WSL2 environment is tainted (I run make on the host).
Make sure that your Docker installation is current otherwise try linux.

**Comment by markmandel** [comment]
Expected failure, or flakiness?

```
Already have image: make-docker
mkdir -p ~/.kube/
mkdir -p /workspace/build//.gocache
mkdir -p /workspace/build//.config/gcloud
mkdir -p ~/.config/helm
mkdir -p ~/.cache/helm
/usr/bin/make ensure-image IMAGE_TAG=agones-build:f5378ddabe BUILD_TARGET=build-build-image
make[1]: Entering directory '/workspace/build'
make[1]: Leaving directory '/workspace/build'
docker push gcr.io/agones-images/agones-controller:1.11.0-59ebcf4
docker push gcr.io/agones-images/agones-sdk:1.11.0-59ebcf4-linux_amd64
docker push gcr.io/agones-images/agones-ping:1.11.0-59ebcf4
docker push gcr.io/agones-images/agones-allocator:1.11.0-59ebcf4
The push refers to repository [gcr.io/agones-images/agones-allocator]
The push refers to repository [gcr.io/agones-images/agones-controller]
6fe5e06d42a9: Preparing
4d36935cfadc: Preparing
ef167023d537: Preparing
The push refers to repository [gcr.io/agones-images/agones-sdk]
3e207b409db3: Preparing
The push refers to repository [gcr.io/agones-images/agones-ping]
5314e2ad398b: Preparing
c1f25e205343: Preparing
ef167023d537: Preparing
3e207b409db3: Preparing
3e207b409db3: Waiting
ef167023d537: Waiting
5314e2ad398b: Preparing
9a3987255414: Preparing
ef167023d537: Preparing
3e207b409db3: Preparing
3e207b409db3: Waiting
ef167023d537: Waiting
5314e2ad398b: Waiting
9a3987255414: Waiting
1253f678b740: Preparing
be3f5eef7a2c: Preparing
ef167023d537: Preparing
3e207b409db3: Preparing
1253f678b740: Waiting
be3f5eef7a2c: Waiting
3e207b409db3: Waiting
3e207b409db3: Layer already exists
6fe5e06d42a9: Pushed
ef167023d537: Pushed
3e207b409db3: Layer already exists
5314e2ad398b: Pushed
5314e2ad398b: Pushed
ef167023d537: Layer already exists
3e207b409db3: Layer already exists
ef167023d537: Pushed
1253f678b740: Pushed
ef167023d537: Layer already exists
3e207b409db3: Layer already exists
4d36935cfadc: Pushed
9a3987255414: Pushed
c1f25e205343: Pushed
1.11.0-59ebcf4: digest: sha256:b5acc16242b9405ceaaf6e69039fab1682c3b4575637dc34f4fddf088083d197 size: 1160
1.11.0-59ebcf4: digest: sha256:1e86462b3c6383c01590e3365c3eb91e730753517eefc7ea1add0207f4a74c56 size: 1159
1.11.0-59ebcf4: digest: sha256:cf03c406645e57639c1b1f03eb914e148a88c6f2da325dd785baed47bcbad081 size: 1160
be3f5eef7a2c: Pushed
unknown blob
Makefile:471: recipe for target 'push-agones-sdk-linux-image' failed
make: *** [push-agones-sdk-linux-image] Error 1
```

**Comment by markmandel** [comment]
Did a quick smoke test with `WITH_WINDOWS` enabled to ensure everything still works on Linux. Was able to build the image, and push it up, and everything worked as expected.

Nice first step! Approving!

**Review by markmandel — APPROVED** [review]

**Comment by WeetA34** [comment]
Hi @jeremyje @markmandel,
FYI, i successfully built and pushed images with Docker Desktop 2.5.0.1 with WSL2 Integration.

Regarding agones-sdk windows image, you can get a smaller image by using @EricFortin 's docker file
https://github.com/googleforgames/agones/issues/54#issuecomment-637633950

Thank you to both of you

**Comment by WeetA34** [comment]
On a second workstation which is behind a proxy, i had to add ARG in build-image/Dockerfile.
Then, i encountered the following error:
```
------
 > [1/3] FROM mcr.microsoft.com/windows/servercore:ltsc2019@sha256:0da0b0e6cf9cf435c6470f23a97a0b9b80495f3712529abc748d80c5fb59209c:
------
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to build LLB: failed to register layer: Error processing tar file(exit status 1): link /Files/Program Files/common files/Microsoft Shared/Ink/en-US/micaut.dll.mui /Files/Program Files (x86)/common files/Microsoft Shared/ink/en-US/micaut.dll.mui: no such file or directory
Makefile:412: recipe for target 'build-agones-sdk-image-windows-ltsc2019' failed
make: *** [build-agones-sdk-image-windows-ltsc2019] Error 1
```

**Comment by jeremyje** [comment]
I've seen this a few times you can see others on the internet as well reasons why this happens off the top of my head.

1. The buildx context is pointing to default and is not backed by the qemu instance that's created.
1. I find that buildx works better on a Linux host. If you're on windows run it straight with `docker build` though the `Makefile` is not configured for that since the expectation is that it's always running in a Linux host. (It probably will run in WSL2 but this might be an awkward artifact).
1. Running concurrent builds. If that's the case each artifact can have a separate context though you'll want to delete them after a build completes.

The way I develop is running a Hyper-V VM that runs Linux and build there. On the Windows host I run in Windows Container mode which allows me to build and run those containers. There's a Xonotic example that is not linked up that should build and run exclusively in a Windows Container environment. The qemu backed buildx context will not build Xonotic because it has powershell in it.

**Comment by WeetA34** [comment]
At the end, it worked fine on both workstations running Docker Desktop 2.5.0.1 with WSL2 integration.

**Pull request merged**
