### PR TITLE
Move gRPC version to 1.57.1

### LINKED ISSUE #3467: Cleanup: Synchronise gRPC versions across the repository
Thanks to dependabot, I noticed we have both gRPC `v1.57.0` and `v1.53.0` in a variety of places.

* https://github.com/search?q=repo%3Agoogleforgames%2Fagones+%221.57.0%22&ype=code
* https://github.com/search?q=repo%3Agoogleforgames%2Fagones+%221.53.0%22&type=code

We should move it all to 1.57.1 (as depdendabot would like us to do).

Thankfully we have a checklist for this for Kubernetes updates, so I'll steal that:

- [ ] Update the SDK [base image grpc version](https://github.com/googleforgames/agones/blob/main/build/includes/sdk.mk#L30) and rebuild the image. Note that this can take a while and in the past we have had to manually push it to gcr because cloud build doesn't like how long it takes.
- [ ] Regenerate allocated API endpoints: [make gen-allocation-grpc](https://github.com/googleforgames/agones/blob/main/build/includes/allocation.mk#L55)
- [ ] Regenerate all client sdks: [make gen-all-sdk-grpc](https://github.com/googleforgames/agones/blob/main/build/README.md#make-gen-all-sdk-grpc)
- [ ] Update the version number in C++ Cmake scripts [here](https://github.com/googleforgames/agones/blob/main/sdks/cpp/CMakeLists.txt#L100) and [here](https://github.com/googleforgames/agones/blob/main/sdks/cpp/cmake/prerequisites.cmake#L34)

### PR DESCRIPTION
**Pull request by Kalaiselvi84**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, press enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking
> /kind bug

/kind cleanup

> /kind documentation
> /kind feature
> /kind hotfix
> /kind release

**What this PR does / Why we need it**:

**Which issue(s) this PR fixes**:

Closes #3467 

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by Kalaiselvi84** [comment]
`build-sdks` step is failing in CI:

```
CMake Error at CMakeLists.txt:32 (_message):
  Build step for grpc failed: 2
Call Stack (most recent call first):
  /usr/share/cmake-3.18/Modules/FetchContent.cmake:987 (message)
  /usr/share/cmake-3.18/Modules/FetchContent.cmake:1011 (__FetchContent_directPopulate)
  cmake/prerequisites.cmake:62 (FetchContent_Populate)
  cmake/prerequisites.cmake:153 (download_git_repo)
  CMakeLists.txt:73 (include)


-- Configuring incomplete, errors occurred!
See also "/go/src/agones.dev/agones/sdks/cpp/.build/CMakeFiles/CMakeOutput.log".
See also "/go/src/agones.dev/agones/sdks/cpp/.build/CMakeFiles/CMakeError.log".
make: *** [Makefile:29: build] Error 1
make[1]: *** [includes/sdk.mk:88: run-sdk-command] Error 2
make: *** [includes/sdk.mk:72: run-sdk-command-cpp] Error 2
```

But the same target is succeeded on local:  https://gist.github.com/Kalaiselvi84/cee55e8c3fd922974d40d1c99bf0fa0c

**Comment by gongmax** [comment]
> `build-sdks` step is failing in CI:
> 
> ```
> CMake Error at CMakeLists.txt:32 (_message):
>   Build step for grpc failed: 2
> Call Stack (most recent call first):
>   /usr/share/cmake-3.18/Modules/FetchContent.cmake:987 (message)
>   /usr/share/cmake-3.18/Modules/FetchContent.cmake:1011 (__FetchContent_directPopulate)
>   cmake/prerequisites.cmake:62 (FetchContent_Populate)
>   cmake/prerequisites.cmake:153 (download_git_repo)
>   CMakeLists.txt:73 (include)
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/go/src/agones.dev/agones/sdks/cpp/.build/CMakeFiles/CMakeOutput.log".
> See also "/go/src/agones.dev/agones/sdks/cpp/.build/CMakeFiles/CMakeError.log".
> make: *** [Makefile:29: build] Error 1
> make[1]: *** [includes/sdk.mk:88: run-sdk-command] Error 2
> make: *** [includes/sdk.mk:72: run-sdk-command-cpp] Error 2
> ```
> 
> But the same target is succeeded on local: https://gist.github.com/Kalaiselvi84/cee55e8c3fd922974d40d1c99bf0fa0c

Not sure how it worked in your local environment, but seems https://github.com/gRPC/gRPC.git v1.57.1 does not exist: https://github.com/grpc/grpc/releases/tag/v1.57.1

**Comment by Kalaiselvi84** [comment]
> Not sure how it worked in your local environment, but seems https://github.com/gRPC/gRPC.git v1.57.1 does not exist: https://github.com/grpc/grpc/releases/tag/v1.57.1

Yes, I am aware that the release version 1.57.1 is not in the [gRPC release](https://github.com/grpc/grpc/releases)

**Comment by markmandel** [comment]
Oh that's interesting! Is the security issue only in the Go version???

**Comment by markmandel** [comment]
Aaah! It is!

https://github.com/advisories/GHSA-qppj-fm5r-hxr3

Okay fun. So.... in which case, let's bump the Go libraries to 1.57.1, but everything else should be 1.57.0

Good catch @gongmax and @Kalaiselvi84 !

Sound good?

**Comment by Kalaiselvi84** [comment]
Aw, did force push instead revert the commits, sorry...

**Pull request closed without merging**
