### PR TITLE
Supress fatal message in CPP example build

### LINKED ISSUE #1091: Building the cpp-simple example prints a fatal message and hangs for a long time before finishing
**What happened**: Tried to build the cpp-simple application. The build hangs, with the error `fatal: not a git repository (or any of the parent directories): .git` (see full output below).

**What you expected to happen**: A successful build. 

**How to reproduce it (as minimally and precisely as possible)**: Check out the master branch, `cd examples/cpp-simple; make`.

**Anything else we need to know?**:

**Environment**:
- Agones version: HEAD
- Kubernetes version (use `kubectl version`): _n/a_
- Cloud provider or hardware configuration: _n/a_
- Install method (yaml/helm): _n/a_
- Troubleshooting guide log(s):

```
$ make build
cd /Users/robertbailey/Work/agones && docker build -f /Users/robertbailey/Work/agones/examples/cpp-simple//Dockerfile --tag=gcr.io/agones-images/cpp-simple-server:0.10 .
Sending build context to Docker daemon  612.8MB
Step 1/17 : FROM gcc:8 as builder
 ---> f7858e844b06
Step 2/17 : WORKDIR /project
 ---> Running in b9f00356eb49
Removing intermediate container b9f00356eb49
 ---> 7c646916c0de
Step 3/17 : RUN wget -q https://cmake.org/files/v3.14/cmake-3.14.1-Linux-x86_64.sh -O /cmake-3.14.1-Linux-x86_64.sh
 ---> Running in d1ebb362af59
Removing intermediate container d1ebb362af59
 ---> b9063c7e9065
Step 4/17 : RUN mkdir /opt/cmake
 ---> Running in 9745a9d64bde
Removing intermediate container 9745a9d64bde
 ---> da69e694b77d
Step 5/17 : RUN sh /cmake-3.14.1-Linux-x86_64.sh --prefix=/opt/cmake --skip-license
 ---> Running in d102596aaa1c
CMake Installer Version: 3.14.1, Copyright (c) Kitware
This is a self-extracting archive.
The archive will be extracted to: /opt/cmake

Using target directory: /opt/cmake
Extracting, please wait...

Unpacking finished successfully
Removing intermediate container d102596aaa1c
 ---> 0ba7af421b90
Step 6/17 : RUN ln -s /opt/cmake/bin/cmake /usr/local/bin/cmake
 ---> Running in 446f1cb448ab
Removing intermediate container 446f1cb448ab
 ---> 85ec5294fd26
Step 7/17 : RUN cmake --version
 ---> Running in 55085ea402e0
cmake version 3.14.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).
Removing intermediate container 55085ea402e0
 ---> c20f0e50f9df
Step 8/17 : COPY ./sdks/cpp sdk
 ---> c409ea8d8b41
Step 9/17 : RUN cd sdk && mkdir -p .build &&     cd .build &&     cmake .. -DCMAKE_BUILD_TYPE=Release -DAGONES_SILENT_OUTPUT=ON -G "Unix Makefiles" -Wno-dev &&     cmake --build . --target install
 ---> Running in e481d0c5aafb
fatal: not a git repository (or any of the parent directories): .git
```

### PR DESCRIPTION
**Pull request by aLekSer**
There is no .git folder in Docker when `make build` on `examples/cpp-simple`.
variable.
Note that when running next command `AGONES_VERSION` set as it should:
` make run-sdk-command SDK_FOLDER=cpp COMMAND=build`

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking
> /kind bug

 /kind cleanup

**What this PR does / Why we need it**:

**Which issue(s) this PR fixes**:

Closes #1091 

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by roberthbailey** [comment]
This looks reasonable to me (since the output is only used if the return code from the child process is 0). 

@dsazonoff - you had some thoughts on https://github.com/googleforgames/agones/issues/1091 so I wanted to see if you had opinions about this solution?

**Comment by aLekSer** [comment]
And adding my latest comment on the ticket:
https://github.com/googleforgames/agones/issues/1091#issuecomment-661169738
This code actually updates to, when we build SDK itself, not with an example:
```
set(agones_VERSION 1.7.0)
```

**Comment by dsazonoff** [comment]
Original error message was produced because of missing .git folder. It is an output of a `git describe --tags --abbrev=0` command, and actually not an error at all from build point of view.

@aLekSer solution looks good, I think it can be merged.

Possible improvements is to do next steps to fill the version variable:

1. Check for an existing environment variable "VERSION" and use it if possible.
2. Otherwise check if it's a git repo (we need to locate .git folder). If yes - get version from git as in existing code
3. Otherwise just do not specify a version

Pseudocode:
```
if (DEFINED $ENV{VERSION)
  set(AGONES_VERSION $ENV{VERSION)
else()
  # keep existing code, but set AGONES_VERSION only for successful git execution
  find_package(git...)
  if (git_FOUND ...)
   ...
  endif()

set(project_version_param)
if (DEFINED AGONES_VERSION)
  set(project_version_param VERSION ${AGONES_VERSION})
endif()

project( ... ${project_version_param })
```

P.S. I'll do a new PR if I'll have some free time.

**Pull request merged**
