### PR TITLE
Upgrade Go version to latest

### PR DESCRIPTION
**Pull request by markmandel**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking
> /kind bug

/kind cleanup

> /kind documentation
> /kind feature
> /kind hotfix

**What this PR does / Why we need it**:

It had been a while, and there were some security fixes, so figured it was worth doing again.

**Which issue(s) this PR fixes**:

N/A

**Special notes for your reviewer**:

I've not incremented example image versions, since I figured this wasn't
a breaking change, and the new version could be picked up as other
changes happen to those images.

### CODE REVIEW

**Review by roberthbailey — APPROVED** [review]

**Comment by markmandel** [comment]
Something in 
```
--- FAIL: TestFleetAutoscalerTLSWebhook (368.86s)
    fleetautoscaler_test.go:640: error waiting for fleet condition on fleet simple-fleet-p72kt
FAIL
time="2020-11-12 23:14:11.772" level=info msg="Namespace 1605222429 is deleted"
FAIL	agones.dev/agones/test/e2e	422.848s
```

Seems to consistently fail. Will have to dig in and see what it might be?

**Comment by markmandel** [comment]
Running the tests locally, I'm getting this error:

```
  Warning  FleetAutoscaler  70s (x4 over 74s)  fleetautoscaler-controller  Error calculating desired fleet size on FleetAutoscaler simple-fleet-9wbw8-autoscaler. Error: Post "https://autoscaler-tls-service.default.svc:8000/scale": dial tcp 10.3.242.176:8000: connect: connection refused
  Warning  FleetAutoscaler  9s (x21 over 69s)  fleetautoscaler-controller  Error calculating desired fleet size on FleetAutoscaler simple-fleet-9wbw8-autoscaler. Error: Post "https://autoscaler-tls-service.default.svc:8000/scale": x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0
```

Seems like a change in cert handling! Will need to work out what is happening there.

**Comment by markmandel** [comment]
Found context on this one. Apparently it's a 20 (?) year old deprecation that has decided to be enforced with this version of Go:
https://github.com/golang/go/issues/39568
https://github.com/golang/go/issues/39568#issuecomment-671424481 < gives a bit more details.

In theory we should be able to update our test certs, and it'll be fine - but we should also make sure to update our documentation to match when creating certs for webhooks - and a troubleshooting guide would also help just in case.

**Comment by markmandel** [comment]
I'm going to close this, and upgrade to 1.14.x for the security fixes -- for the life of me, I cannot get this to work by either:

* incorporating `GODEBUG=x509ignoreCN=0`
* Updating certs to using SANs rather than Common Name

Filing an issue to upgrade to 1.15.x and migrate webhooks to SAN based certs.

**Pull request closed without merging**
