### PR TITLE
flaky/TestFleetRollingUpdate

### PR DESCRIPTION
**Pull request by markmandel**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, press enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking

/kind bug

> /kind cleanup
> /kind documentation
> /kind feature
> /kind hotfix

**What this PR does / Why we need it**:

Looks like the issue is that sometimes the test can't update the Fleet, so added some logging to see if we can see why.

Also:
* Updated deprecated methods
* Removed parallel for subtests (see if that makes things more stable).

**Which issue(s) this PR fixes**:

Work on #2522

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by markmandel** [comment]
e2e log Still failing.

<summary>
Grepped e2e Log
<details>
<code>
time="2023-01-12 22:53:54.775" level=info msg="waiting for fleet condition" fleet=simple-fleet-1.0tz8nf test="TestFleetRollingUpdate/Use_fleet_Patch_true_25%_cycle_false"
time="2023-01-12 22:53:56.584" level=info msg="Checking Fleet Ready replicas" expected=1 fleet=simple-fleet-1.0tz8nf fleetStatus="{Replicas:1 ReadyReplicas:0 ReservedReplicas:0 AllocatedReplicas:0 Players:<nil>}" test="TestFleetRollingUpdate/Use_fleet_Patch_true_25%_cycle_false"
time="2023-01-12 22:54:00.961" level=info msg="Checking Fleet Ready replicas" expected=1 fleet=simple-fleet-1.0tz8nf fleetStatus="{Replicas:1 ReadyReplicas:0 ReservedReplicas:0 AllocatedReplicas:0 Players:<nil>}" test="TestFleetRollingUpdate/Use_fleet_Patch_true_25%_cycle_false"
time="2023-01-12 22:54:04.960" level=info msg="Checking Fleet Ready replicas" expected=1 fleet=simple-fleet-1.0tz8nf fleetStatus="{Replicas:1 ReadyReplicas:0 ReservedReplicas:0 AllocatedReplicas:0 Players:<nil>}" test="TestFleetRollingUpdate/Use_fleet_Patch_true_25%_cycle_false"
time="2023-01-12 22:54:07.761" level=info msg="Checking Fleet Ready replicas" expected=1 fleet=simple-fleet-1.0tz8nf fleetStatus="{Replicas:1 ReadyReplicas:0 ReservedReplicas:0 AllocatedReplicas:0 Players:<nil>}" test="TestFleetRollingUpdate/Use_fleet_Patch_true_25%_cycle_false"
time="2023-01-12 22:54:10.560" level=info msg="Checking Fleet Ready replicas" expected=1 fleet=simple-fleet-1.0tz8nf fleetStatus="{Replicas:1 ReadyReplicas:0 ReservedReplicas:0 AllocatedReplicas:0 Players:<nil>}" test="TestFleetRollingUpdate/Use_fleet_Patch_true_25%_cycle_false"
time="2023-01-12 22:54:12.761" level=info msg="Checking Fleet Ready replicas" expected=1 fleet=simple-fleet-1.0tz8nf fleetStatus="{Replicas:1 ReadyReplicas:0 ReservedReplicas:0 AllocatedReplicas:0 Players:<nil>}" test="TestFleetRollingUpdate/Use_fleet_Patch_true_25%_cycle_false"
time="2023-01-12 22:54:16.959" level=info msg="Checking Fleet Ready replicas" expected=1 fleet=simple-fleet-1.0tz8nf fleetStatus="{Replicas:1 ReadyReplicas:0 ReservedReplicas:0 AllocatedReplicas:0 Players:<nil>}" test="TestFleetRollingUpdate/Use_fleet_Patch_true_25%_cycle_false"
time="2023-01-12 22:54:21.560" level=info msg="Checking Fleet Ready replicas" expected=1 fleet=simple-fleet-1.0tz8nf fleetStatus="{Replicas:1 ReadyReplicas:1 ReservedReplicas:0 AllocatedReplicas:0 Players:<nil>}" test="TestFleetRollingUpdate/Use_fleet_Patch_true_25%_cycle_false"
time="2023-01-12 22:54:24.996" level=info msg="waiting for fleet condition" fleet=simple-fleet-1.0tz8nf test="TestFleetRollingUpdate/Use_fleet_Patch_true_25%_cycle_false"
time="2023-01-12 22:54:27.788" level=info msg="Checking Fleet Ready replicas" expected=8 fleet=simple-fleet-1.0tz8nf fleetStatus="{Replicas:8 ReadyReplicas:1 ReservedReplicas:0 AllocatedReplicas:0 Players:<nil>}" test="TestFleetRollingUpdate/Use_fleet_Patch_true_25%_cycle_false"
time="2023-01-12 22:54:32.760" level=info msg="Checking Fleet Ready replicas" expected=8 fleet=simple-fleet-1.0tz8nf fleetStatus="{Replicas:8 ReadyReplicas:4 ReservedReplicas:0 AllocatedReplicas:0 Players:<nil>}" test="TestFleetRollingUpdate/Use_fleet_Patch_true_25%_cycle_false"
time="2023-01-12 22:54:36.562" level=info msg="Checking Fleet Ready replicas" expected=8 fleet=simple-fleet-1.0tz8nf fleetStatus="{Replicas:8 ReadyReplicas:6 ReservedReplicas:0 AllocatedReplicas:0 Players:<nil>}" test="TestFleetRollingUpdate/Use_fleet_Patch_true_25%_cycle_false"
time="2023-01-12 22:54:40.360" level=info msg="Checking Fleet Ready replicas" expected=8 fleet=simple-fleet-1.0tz8nf fleetStatus="{Replicas:8 ReadyReplicas:8 ReservedReplicas:0 AllocatedReplicas:0 Players:<nil>}" test="TestFleetRollingUpdate/Use_fleet_Patch_true_25%_cycle_false"
time="2023-01-12 22:55:55.598" level=info msg="waiting for fleet condition" fleet=simple-fleet-1.0tz8nf test="TestFleetRollingUpdate/Use_fleet_Patch_true_25%_cycle_false"
time="2023-01-12 22:55:58.160" level=info msg="Checking Fleet Ready replicas" expected=1 fleet=simple-fleet-1.0tz8nf fleetStatus="{Replicas:1 ReadyReplicas:1 ReservedReplicas:0 AllocatedReplicas:0 Players:<nil>}" test="TestFleetRollingUpdate/Use_fleet_Patch_true_25%_cycle_false"
time="2023-01-12 22:55:58.160" level=info msg="waiting for fleet condition" fleet=simple-fleet-1.0tz8nf test="TestFleetRollingUpdate/Use_fleet_Patch_true_25%_cycle_false"
time="2023-01-12 22:56:05.794" level=info msg="waiting for fleet condition" fleet=simple-fleet-1.0zvx6l test="TestFleetRollingUpdate/Use_fleet_Patch_true_10%_cycle_false"
time="2023-01-12 22:56:08.393" level=info msg="Checking Fleet Ready replicas" expected=1 fleet=simple-fleet-1.0zvx6l fleetStatus="{Replicas:1 ReadyReplicas:0 ReservedReplicas:0 AllocatedReplicas:0 Players:<nil>}" test="TestFleetRollingUpdate/Use_fleet_Patch_true_10%_cycle_false"
time="2023-01-12 22:56:12.960" level=info msg="Checking Fleet Ready replicas" expected=1 fleet=simple-fleet-1.0zvx6l fleetStatus="{Replicas:1 ReadyReplicas:1 ReservedReplicas:0 AllocatedReplicas:0 Players:<nil>}" test="TestFleetRollingUpdate/Use_fleet_Patch_true_10%_cycle_false"
time="2023-01-12 22:56:15.600" level=info msg="waiting for fleet condition" fleet=simple-fleet-1.0zvx6l test="TestFleetRollingUpdate/Use_fleet_Patch_true_10%_cycle_false"
time="2023-01-12 22:56:17.360" level=info msg="Checking Fleet Ready replicas" expected=8 fleet=simple-fleet-1.0zvx6l fleetStatus="{Replicas:8 ReadyReplicas:1 ReservedReplicas:0 AllocatedReplicas:0 Players:<nil>}" test="TestFleetRollingUpdate/Use_fleet_Patch_true_10%_cycle_false"
time="2023-01-12 22:56:21.456" level=info msg="Checking Fleet Ready replicas" expected=8 fleet=simple-fleet-1.0zvx6l fleetStatus="{Replicas:8 ReadyReplicas:5 ReservedReplicas:0 AllocatedReplicas:0 Players:<nil>}" test="TestFleetRollingUpdate/Use_fleet_Patch_true_10%_cycle_false"
time="2023-01-12 22:56:25.117" level=info msg="Checking Fleet Ready replicas" expected=8 fleet=simple-fleet-1.0zvx6l fleetStatus="{Replicas:8 ReadyReplicas:8 ReservedReplicas:0 AllocatedReplicas:0 Players:<nil>}" test="TestFleetRollingUpdate/Use_fleet_Patch_true_10%_cycle_false"
time="2023-01-12 22:56:59.997" level=info msg="waiting for fleet condition" fleet=simple-fleet-1.0zvx6l test="TestFleetRollingUpdate/Use_fleet_Patch_true_10%_cycle_false"
time="2023-01-12 22:57:01.160" level=info msg="Checking Fleet Ready replicas" expected=1 fleet=simple-fleet-1.0zvx6l fleetStatus="{Replicas:1 ReadyReplicas:1 ReservedReplicas:0 AllocatedReplicas:0 Players:<nil>}" test="TestFleetRollingUpdate/Use_fleet_Patch_true_10%_cycle_false"
time="2023-01-12 22:57:01.160" level=info msg="waiting for fleet condition" fleet=simple-fleet-1.0zvx6l test="TestFleetRollingUpdate/Use_fleet_Patch_true_10%_cycle_false"
time="2023-01-12 22:57:03.000" level=info msg="waiting for fleet condition" fleet=simple-fleet-1.0cfdh9 test="TestFleetRollingUpdate/Use_fleet_Patch_false_25%_cycle_false"
time="2023-01-12 22:57:03.381" level=info msg="Checking Fleet Ready replicas" expected=1 fleet=simple-fleet-1.0cfdh9 fleetStatus="{Replicas:0 ReadyReplicas:0 ReservedReplicas:0 AllocatedReplicas:0 Players:<nil>}" test="TestFleetRollingUpdate/Use_fleet_Patch_false_25%_cycle_false"
time="2023-01-12 22:57:05.445" level=info msg="Checking Fleet Ready replicas" expected=1 fleet=simple-fleet-1.0cfdh9 fleetStatus="{Replicas:1 ReadyReplicas:0 ReservedReplicas:0 AllocatedReplicas:0 Players:<nil>}" test="TestFleetRollingUpdate/Use_fleet_Patch_false_25%_cycle_false"
time="2023-01-12 22:57:07.452" level=info msg="Checking Fleet Ready replicas" expected=1 fleet=simple-fleet-1.0cfdh9 fleetStatus="{Replicas:1 ReadyReplicas:1 ReservedReplicas:0 AllocatedReplicas:0 Players:<nil>}" test="TestFleetRollingUpdate/Use_fleet_Patch_false_25%_cycle_false"
time="2023-01-12 22:57:07.648" level=info msg="waiting for fleet condition" fleet=simple-fleet-1.0cfdh9 test="TestFleetRollingUpdate/Use_fleet_Patch_false_25%_cycle_false"
time="2023-01-12 22:57:07.712" level=info msg="Checking Fleet Ready replicas" expected=8 fleet=simple-fleet-1.0cfdh9 fleetStatus="{Replicas:1 ReadyReplicas:1 ReservedReplicas:0 AllocatedReplicas:0 Players:<nil>}" test="TestFleetRollingUpdate/Use_fleet_Patch_false_25%_cycle_false"
time="2023-01-12 22:57:09.963" level=info msg="Checking Fleet Ready replicas" expected=8 fleet=simple-fleet-1.0cfdh9 fleetStatus="{Replicas:8 ReadyReplicas:1 ReservedReplicas:0 AllocatedReplicas:0 Players:<nil>}" test="TestFleetRollingUpdate/Use_fleet_Patch_false_25%_cycle_false"
time="2023-01-12 22:57:11.776" level=info msg="Checking Fleet Ready replicas" expected=8 fleet=simple-fleet-1.0cfdh9 fleetStatus="{Replicas:8 ReadyReplicas:3 ReservedReplicas:0 AllocatedReplicas:0 Players:<nil>}" test="TestFleetRollingUpdate/Use_fleet_Patch_false_25%_cycle_false"
time="2023-01-12 22:57:13.777" level=info msg="Checking Fleet Ready replicas" expected=8 fleet=simple-fleet-1.0cfdh9 fleetStatus="{Replicas:8 ReadyReplicas:6 ReservedReplicas:0 AllocatedReplicas:0 Players:<nil>}" test="TestFleetRollingUpdate/Use_fleet_Patch_false_25%_cycle_false"
time="2023-01-12 22:57:15.779" level=info msg="Checking Fleet Ready replicas" expected=8 fleet=simple-fleet-1.0cfdh9 fleetStatus="{Replicas:8 ReadyReplicas:7 ReservedReplicas:0 AllocatedReplicas:0 Players:<nil>}" test="TestFleetRollingUpdate/Use_fleet_Patch_false_25%_cycle_false"
time="2023-01-12 22:57:17.775" level=info msg="Checking Fleet Ready replicas" expected=8 fleet=simple-fleet-1.0cfdh9 fleetStatus="{Replicas:8 ReadyReplicas:8 ReservedReplicas:0 AllocatedReplicas:0 Players:<nil>}" test="TestFleetRollingUpdate/Use_fleet_Patch_false_25%_cycle_false"
time="2023-01-12 22:57:48.743" level=info msg="waiting for fleet condition" fleet=simple-fleet-1.0cfdh9 test="TestFleetRollingUpdate/Use_fleet_Patch_false_25%_cycle_false"
time="2023-01-12 22:57:48.806" level=info msg="Checking Fleet Ready replicas" expected=1 fleet=simple-fleet-1.0cfdh9 fleetStatus="{Replicas:8 ReadyReplicas:8 ReservedReplicas:0 AllocatedReplicas:0 Players:<nil>}" test="TestFleetRollingUpdate/Use_fleet_Patch_false_25%_cycle_false"
time="2023-01-12 22:57:50.894" level=info msg="Checking Fleet Ready replicas" expected=1 fleet=simple-fleet-1.0cfdh9 fleetStatus="{Replicas:1 ReadyReplicas:1 ReservedReplicas:0 AllocatedReplicas:0 Players:<nil>}" test="TestFleetRollingUpdate/Use_fleet_Patch_false_25%_cycle_false"
time="2023-01-12 22:57:50.894" level=info msg="waiting for fleet condition" fleet=simple-fleet-1.0cfdh9 test="TestFleetRollingUpdate/Use_fleet_Patch_false_25%_cycle_false"
time="2023-01-12 22:57:51.434" level=info msg="waiting for fleet condition" fleet=simple-fleet-1.069vh7 test="TestFleetRollingUpdate/Use_fleet_Patch_false_10%_cycle_false"
time="2023-01-12 22:57:51.526" level=info msg="Checking Fleet Ready replicas" expected=1 fleet=simple-fleet-1.069vh7 fleetStatus="{Replicas:0 ReadyReplicas:0 ReservedReplicas:0 AllocatedReplicas:0 Players:<nil>}" test="TestFleetRollingUpdate/Use_fleet_Patch_false_10%_cycle_false"
time="2023-01-12 22:57:53.596" level=info msg="Checking Fleet Ready replicas" expected=1 fleet=simple-fleet-1.069vh7 fleetStatus="{Replicas:1 ReadyReplicas:0 ReservedReplicas:0 AllocatedReplicas:0 Players:<nil>}" test="TestFleetRollingUpdate/Use_fleet_Patch_false_10%_cycle_false"
time="2023-01-12 22:57:55.592" level=info msg="Checking Fleet Ready replicas" expected=1 fleet=simple-fleet-1.069vh7 fleetStatus="{Replicas:1 ReadyReplicas:1 ReservedReplicas:0 AllocatedReplicas:0 Players:<nil>}" test="TestFleetRollingUpdate/Use_fleet_Patch_false_10%_cycle_false"
time="2023-01-12 22:57:55.772" level=info msg="waiting for fleet condition" fleet=simple-fleet-1.069vh7 test="TestFleetRollingUpdate/Use_fleet_Patch_false_10%_cycle_false"
time="2023-01-12 22:57:55.835" level=info msg="Checking Fleet Ready replicas" expected=8 fleet=simple-fleet-1.069vh7 fleetStatus="{Replicas:1 ReadyReplicas:1 ReservedReplicas:0 AllocatedReplicas:0 Players:<nil>}" test="TestFleetRollingUpdate/Use_fleet_Patch_false_10%_cycle_false"
time="2023-01-12 22:57:57.900" level=info msg="Checking Fleet Ready replicas" expected=8 fleet=simple-fleet-1.069vh7 fleetStatus="{Replicas:8 ReadyReplicas:1 ReservedReplicas:0 AllocatedReplicas:0 Players:<nil>}" test="TestFleetRollingUpdate/Use_fleet_Patch_false_10%_cycle_false"
time="2023-01-12 22:57:59.902" level=info msg="Checking Fleet Ready replicas" expected=8 fleet=simple-fleet-1.069vh7 fleetStatus="{Replicas:8 ReadyReplicas:2 ReservedReplicas:0 AllocatedReplicas:0 Players:<nil>}" test="TestFleetRollingUpdate/Use_fleet_Patch_false_10%_cycle_false"
time="2023-01-12 22:58:01.903" level=info msg="Checking Fleet Ready replicas" expected=8 fleet=simple-fleet-1.069vh7 fleetStatus="{Replicas:8 ReadyReplicas:7 ReservedReplicas:0 AllocatedReplicas:0 Players:<nil>}" test="TestFleetRollingUpdate/Use_fleet_Patch_false_10%_cycle_false"
time="2023-01-12 22:58:03.902" level=info msg="Checking Fleet Ready replicas" expected=8 fleet=simple-fleet-1.069vh7 fleetStatus="{Replicas:8 ReadyReplicas:8 ReservedReplicas:0 AllocatedReplicas:0 Players:<nil>}" test="TestFleetRollingUpdate/Use_fleet_Patch_false_10%_cycle_false"
time="2023-01-12 22:58:31.882" level=info msg="waiting for fleet condition" fleet=simple-fleet-1.069vh7 test="TestFleetRollingUpdate/Use_fleet_Patch_false_10%_cycle_false"
time="2023-01-12 22:58:31.973" level=info msg="Checking Fleet Ready replicas" expected=1 fleet=simple-fleet-1.069vh7 fleetStatus="{Replicas:8 ReadyReplicas:8 ReservedReplicas:0 AllocatedReplicas:0 Players:<nil>}" test="TestFleetRollingUpdate/Use_fleet_Patch_false_10%_cycle_false"
time="2023-01-12 22:58:34.047" level=info msg="Checking Fleet Ready replicas" expected=1 fleet=simple-fleet-1.069vh7 fleetStatus="{Replicas:1 ReadyReplicas:1 ReservedReplicas:0 AllocatedReplicas:0 Players:<nil>}" test="TestFleetRollingUpdate/Use_fleet_Patch_false_10%_cycle_false"
time="2023-01-12 22:58:34.047" level=info msg="waiting for fleet condition" fleet=simple-fleet-1.069vh7 test="TestFleetRollingUpdate/Use_fleet_Patch_false_10%_cycle_false"
time="2023-01-12 22:58:34.302" level=info msg="waiting for fleet condition" fleet=simple-fleet-1.0x2nmk test="TestFleetRollingUpdate/Use_fleet_Patch_true_25%_cycle_true"
time="2023-01-12 22:58:34.389" level=info msg="Checking Fleet Ready replicas" expected=1 fleet=simple-fleet-1.0x2nmk fleetStatus="{Replicas:0 ReadyReplicas:0 ReservedReplicas:0 AllocatedReplicas:0 Players:<nil>}" test="TestFleetRollingUpdate/Use_fleet_Patch_true_25%_cycle_true"
time="2023-01-12 22:58:36.456" level=info msg="Checking Fleet Ready replicas" expected=1 fleet=simple-fleet-1.0x2nmk fleetStatus="{Replicas:1 ReadyReplicas:0 ReservedReplicas:0 AllocatedReplicas:0 Players:<nil>}" test="TestFleetRollingUpdate/Use_fleet_Patch_true_25%_cycle_true"
time="2023-01-12 22:58:38.458" level=info msg="Checking Fleet Ready replicas" expected=1 fleet=simple-fleet-1.0x2nmk fleetStatus="{Replicas:1 ReadyReplicas:1 ReservedReplicas:0 AllocatedReplicas:0 Players:<nil>}" test="TestFleetRollingUpdate/Use_fleet_Patch_true_25%_cycle_true"
time="2023-01-12 22:58:38.553" level=info msg="waiting for fleet condition" fleet=simple-fleet-1.0x2nmk test="TestFleetRollingUpdate/Use_fleet_Patch_true_25%_cycle_true"
time="2023-01-12 22:58:38.614" level=info msg="Checking Fleet Ready replicas" expected=8 fleet=simple-fleet-1.0x2nmk fleetStatus="{Replicas:1 ReadyReplicas:1 ReservedReplicas:0 AllocatedReplicas:0 Players:<nil>}" test="TestFleetRollingUpdate/Use_fleet_Patch_true_25%_cycle_true"
time="2023-01-12 22:58:40.681" level=info msg="Checking Fleet Ready replicas" expected=8 fleet=simple-fleet-1.0x2nmk fleetStatus="{Replicas:8 ReadyReplicas:1 ReservedReplicas:0 AllocatedReplicas:0 Players:<nil>}" test="TestFleetRollingUpdate/Use_fleet_Patch_true_25%_cycle_true"
time="2023-01-12 22:58:42.681" level=info msg="Checking Fleet Ready replicas" expected=8 fleet=simple-fleet-1.0x2nmk fleetStatus="{Replicas:8 ReadyReplicas:1 ReservedReplicas:0 AllocatedReplicas:0 Players:<nil>}" test="TestFleetRollingUpdate/Use_fleet_Patch_true_25%_cycle_true"
time="2023-01-12 22:58:44.683" level=info msg="Checking Fleet Ready replicas" expected=8 fleet=simple-fleet-1.0x2nmk fleetStatus="{Replicas:8 ReadyReplicas:3 ReservedReplicas:0 AllocatedReplicas:0 Players:<nil>}" test="TestFleetRollingUpdate/Use_fleet_Patch_true_25%_cycle_true"
time="2023-01-12 22:58:46.686" level=info msg="Checking Fleet Ready replicas" expected=8 fleet=simple-fleet-1.0x2nmk fleetStatus="{Replicas:8 ReadyReplicas:3 ReservedReplicas:0 AllocatedReplicas:0 Players:<nil>}" test="TestFleetRollingUpdate/Use_fleet_Patch_true_25%_cycle_true"
time="2023-01-12 22:58:48.683" level=info msg="Checking Fleet Ready replicas" expected=8 fleet=simple-fleet-1.0x2nmk fleetStatus="{Replicas:8 ReadyReplicas:3 ReservedReplicas:0 AllocatedReplicas:0 Players:<nil>}" test="TestFleetRollingUpdate/Use_fleet_Patch_true_25%_cycle_true"
time="2023-01-12 22:58:50.677" level=info msg="Checking Fleet Ready replicas" expected=8 fleet=simple-fleet-1.0x2nmk fleetStatus="{Replicas:8 ReadyReplicas:6 ReservedReplicas:0 AllocatedReplicas:0 Players:<nil>}" test="TestFleetRollingUpdate/Use_fleet_Patch_true_25%_cycle_true"
time="2023-01-12 22:58:52.681" level=info msg="Checking Fleet Ready replicas" expected=8 fleet=simple-fleet-1.0x2nmk fleetStatus="{Replicas:8 ReadyReplicas:8 ReservedReplicas:0 AllocatedReplicas:0 Players:<nil>}" test="TestFleetRollingUpdate/Use_fleet_Patch_true_25%_cycle_true"
time="2023-01-12 22:58:52.744" level=info msg="waiting for fleet condition" fleet=simple-fleet-1.0x2nmk test="TestFleetRollingUpdate/Use_fleet_Patch_true_25%_cycle_true"
time="2023-01-12 22:59:58.597" level=info msg="waiting for fleet condition" fleet=simple-fleet-1.0x2nmk test="TestFleetRollingUpdate/Use_fleet_Patch_true_25%_cycle_true"
time="2023-01-12 22:59:58.659" level=info msg="Checking Fleet Ready replicas" expected=1 fleet=simple-fleet-1.0x2nmk fleetStatus="{Replicas:8 ReadyReplicas:2 ReservedReplicas:0 AllocatedReplicas:4 Players:<nil>}" test="TestFleetRollingUpdate/Use_fleet_Patch_true_25%_cycle_true"
time="2023-01-12 23:00:00.726" level=info msg="Checking Fleet Ready replicas" expected=1 fleet=simple-fleet-1.0x2nmk fleetStatus="{Replicas:4 ReadyReplicas:0 ReservedReplicas:0 AllocatedReplicas:4 Players:<nil>}" test="TestFleetRollingUpdate/Use_fleet_Patch_true_25%_cycle_true"
time="2023-01-12 23:00:02.725" level=info msg="Checking Fleet Ready replicas" expected=1 fleet=simple-fleet-1.0x2nmk fleetStatus="{Replicas:3 ReadyReplicas:0 ReservedReplicas:0 AllocatedReplicas:3 Players:<nil>}" test="TestFleetRollingUpdate/Use_fleet_Patch_true_25%_cycle_true"
time="2023-01-12 23:00:04.727" level=info msg="Checking Fleet Ready replicas" expected=1 fleet=simple-fleet-1.0x2nmk fleetStatus="{Replicas:2 ReadyReplicas:0 ReservedReplicas:0 AllocatedReplicas:2 Players:<nil>}" test="TestFleetRollingUpdate/Use_fleet_Patch_true_25%_cycle_true"
time="2023-01-12 23:00:06.723" level=info msg="Checking Fleet Ready replicas" expected=1 fleet=simple-fleet-1.0x2nmk fleetStatus="{Replicas:2 ReadyReplicas:0 ReservedReplicas:0 AllocatedReplicas:2 Players:<nil>}" test="TestFleetRollingUpdate/Use_fleet_Patch_true_25%_cycle_true"
time="2023-01-12 23:00:08.725" level=info msg="Checking Fleet Ready replicas" expected=1 fleet=simple-fleet-1.0x2nmk fleetStatus="{Replicas:1 ReadyReplicas:0 ReservedReplicas:0 AllocatedReplicas:1 Players:<nil>}" test="TestFleetRollingUpdate/Use_fleet_Patch_true_25%_cycle_true"
time="2023-01-12 23:00:10.724" level=info msg="Checking Fleet Ready replicas" expected=1 fleet=simple-fleet-1.0x2nmk fleetStatus="{Replicas:1 ReadyReplicas:0 ReservedReplicas:0 AllocatedReplicas:0 Players:<nil>}" test="TestFleetRollingUpdate/Use_fleet_Patch_true_25%_cycle_true"
agones.dev/agones/test/e2e.TestFleetRollingUpdate(0x0?)
agones.dev/agones/test/e2e.TestFleetRollingUpdate.func1(0xc00079f1e0)
</code>
</details>

<summary>

It fails with Fleet `simple-fleet-1.0x2nmk`, but if I look at that Fleet yaml in the e2e cluster, it has 1 `Ready` `GameServer ` like it is supposed to.

```yaml
apiVersion: agones.dev/v1
kind: Fleet
metadata:
  annotations:
    agones.dev/sdk-version: 1.29.0-2a238bf
  creationTimestamp: "2023-01-12T22:58:34Z"
  generateName: simple-fleet-1.0
  generation: 4
  name: simple-fleet-1.0x2nmk
  namespace: "1673563811"
  resourceVersion: "8625554"
  uid: 78df8f7f-f8ea-4aec-bb08-227b0ed1aba2
spec:
  replicas: 1
  scheduling: Packed
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
    spec:
      container: game-server
      health: {}
      ports:
        - containerPort: 7655
          name: udp-port
          portPolicy: Dynamic
          protocol: UDP
      sdkServer: {}
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - image: us-docker.pkg.dev/agones-images/examples/simple-game-server:0.14
              imagePullPolicy: IfNotPresent
              name: game-server
              resources:
                limits:
                  cpu: 30m
                  memory: 32Mi
                requests:
                  cpu: 30m
                  memory: 32Mi
status:
  allocatedReplicas: 0
  readyReplicas: 1
  replicas: 1
  reservedReplicas: 0
```

**Comment by markmandel** [comment]
That's a new flake.

```
--- FAIL: TestDevelopmentGameServerLifecycle (17.25s)
    gameserver_test.go:539: 
        	Error Trace:	/go/src/agones.dev/agones/test/e2e/gameserver_test.go:539
        	Error:      	Not equal: 
        	            	expected: "udp-servergxp6z"
        	            	actual  : ""
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-udp-servergxp6z
        	            	+
        	Test:       	TestDevelopmentGameServerLifecycle
```

**Comment by markmandel** [comment]
Once RC is out, I think this is good to go. Probably should merge this before #2904 though.

**Comment by zmerlynn** [comment]
FWIW, my intent with #2904 is not to paper over the flakes - but we still need to figure out how to report them. It'll probably end up something we have to do a bit adhoc (through logs download / rummaging).

**Comment by markmandel** [comment]
My point is I believe/hope this actually fixes the flaky issue. The test just sometimes needs some more time to complete - that's really about it.

**Review by zmerlynn — APPROVED** [review]
LGTM, honestly don't mind this going in during RC. I think it meets the criteria for a bug fix - I'll leave it up to you

**Comment by markmandel** [comment]
Yeah we're just in the middle of doing the RC release process. Once that is done, I agree - this can be merged.

**Pull request merged**
