### PR TITLE
fix: Label PR Warning

### PR DESCRIPTION
**Pull request by aimuz**
Signed-off-by: aimuz <mr.imuz@gmail.com>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, press enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking
> /kind bug
> /kind cleanup
> /kind documentation
> /kind feature
> /kind hotfix

**What this PR does / Why we need it**:

**Which issue(s) this PR fixes**:

Closes #

**Special notes for your reviewer**:

```
Warning: Unexpected input(s) 'repo-token', valid inputs are ['script', 'github-token', 'debug', 'user-agent', 'previews', 'result-encoding']
```

### CODE REVIEW

**Comment by markmandel** [comment]
@Kalaiselvi84 you are the expert on this one - this look good to you?

**Comment by Kalaiselvi84** [comment]
> @Kalaiselvi84 you are the expert on this one - this look good to you?

I have tested it in my fork without including `repo-token: ${{ secrets.GITHUB_TOKEN }}`, and it is working fine. According to the documentation at https://docs.github.com/en/actions/security-guides/automatic-token-authentication, the secrets.GITHUB_TOKEN is automatically available to all workflows running in the repository, and there is no need to explicitly define or store it in the repository's secrets. However, it is important to consider the security implications, as using this token could potentially grant unauthorized access to the repository. Nevertheless, since it is an open-source project, it should be acceptable to omit its usage. WDYT?

**Comment by aimuz** [comment]
In https://github.com/actions/github-script, the repo-token is not valid

https://github.com/actions/github-script#using-a-separate-github-token

**Review by markmandel — APPROVED** [review]
Sounds like this is a valid fix then.

**Pull request merged**
