### PR TITLE
Remove the documentation for helm v2

### LINKED ISSUE #1853: Remove support / docs for helm v2
https://github.com/googleforgames/agones/issues/1436 migrated Agones from helm v2 to helm v3. But we still have [documentation for helm v2](https://agones.dev/site/docs/installation/install-agones/helm/#helm-2). 

We should remove the docs and clean up any code / charts that were kept for backwards compatibility. 

According to https://helm.sh/blog/helm-v2-deprecation-timeline/ helm v2 is hitting end-of-life is ~1 month (November 13, 2020).

### PR DESCRIPTION
**Pull request by roberthbailey**
It is reaching EOL on 2020-11-13.

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking
> /kind bug
> /kind cleanup

 /kind documentation

> /kind feature
> /kind hotfix

**What this PR does / Why we need it**:

**Which issue(s) this PR fixes**: 

**Special notes for your reviewer**:

I gated this on the next release, which will cause the documentation to be updated ~3 days before the helm v2 EOL date. If you think it would be better to mark the docs as deprecated _now_ to put up a warning, that would be a simple change to add. 

/assign @markmandel

### CODE REVIEW

**Comment by roberthbailey** [comment]
The link checker is failing with a bunch of 429 errors trying to look up github.com urls.

**Review by pooneh-m — APPROVED** [review]
Thanks for removing the helm 2 documentations.

**Comment by markmandel** [comment]
I'm hoping #1861  will resolve the stuck CI.

**Comment by markmandel** [comment]
Yep #1861 fixed things!

**Pull request merged**
