### PR TITLE
[Unreal SDK] Added a response code check to some functions

### PR DESCRIPTION
**Pull request by dotcom**
**What type of PR is this?**
/kind bug

**Which issue(s) this PR fixes**:
Added a response code check to some functions about Unreal SDK.

### CODE REVIEW

**Review by domgreen — APPROVED** [review]
LGTM

Looks like a good addition :+1:

**Comment by markmandel** [comment]
Only questions I have - is this a breaking change?

Other than that, I'm happy to push this through :+1:

**Comment by dotcom** [comment]
@markmandel 
No. The user interface has not changed. It can still be used. This makes it less confusing for the user.
Users can execute an Error callback in case of a bad response code in addition to communication errors.

**Review by markmandel — APPROVED** [review]
seal of approval

**Pull request merged**
