### PR TITLE
add vendor grpc third_party to be referenced by protos

### PR DESCRIPTION
**Pull request by pooneh-m**
Following these steps: https://github.com/googleforgames/agones/blob/master/build/README.md#dependencies
Third_party directory does not get added with go mod vendor as described.

### CODE REVIEW

**Comment by markmandel** [comment]
Just so I'm 100% clear, did you add this in manually?

Happy to approve this going through,  I'm just concerned it might get accidentally deleted on a `go mod` operation that updates the vendor directory -- such as updating the grpc-gateway library itself, will that delete this third_party directory? or will we need to manually ensure it always is there?

**Comment by markmandel** [comment]
Sounds like this is a fun(?) common problem: https://github.com/golang/go/issues/26366

**Comment by pooneh-m** [comment]
Exactly, running go mod vendor recreates the vendor directory therefore removes the third_party directory.

I followed [this](https://github.com/googleforgames/agones/blob/master/build/README.md#dependencies) to add the third_party directory, which is exactly what I needed:
AGONES_PATH=/wherever/your/agones/path/is
cp -R $GOPATH/pkg/mod/github.com/grpc-ecosystem/grpc-gateway@v1.5.1/third_party $AGONES_PATH/vendor/github.com/grpc-ecosystem/grpc-gateway/

Ideally we should remove the dependency to vendor and only use go.mod?

**Comment by markmandel** [comment]
Got it - so in a previous life, someone already encountered this :+1: 

Maybe in a future PR we could do something like `make go-deps` and it would do all the appropriate things...? But for the future.

I'm assuming in a future PR we are going to remove the protos in /protos and update the tooling to reference this `third_party` directory instead?

**Comment by pooneh-m** [comment]
Good idea.

**Pull request merged**
