### PR TITLE
Update the minikube driver flag name (--vm-driver is deprecated)

### PR DESCRIPTION
**Pull request by roberthbailey**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, press enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking
> /kind bug

/kind cleanup

> /kind documentation
> /kind feature
> /kind hotfix

**What this PR does / Why we need it**:

**Which issue(s) this PR fixes**:

Closes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by roberthbailey** [comment]
Flake in e2e-feature-gates:

```
--- FAIL: TestFleetAutoscalerTLSWebhook (318.36s)
    framework.go:284: 
        	Error Trace:	framework.go:284
        	            				fleetautoscaler_test.go:709
        	Error:      	Received unexpected error:
        	            	timed out waiting for the condition
        	Test:       	TestFleetAutoscalerTLSWebhook
        	Messages:   	error waiting for fleet condition on fleet: simple-fleet-p6v9r
FAIL
```

**Comment by roberthbailey** [comment]
Another flake in e2e-feature gates:

```
--- FAIL: TestFleetAutoscalerTLSWebhook (317.10s)
    framework.go:284: 
        	Error Trace:	framework.go:284
        	            				fleetautoscaler_test.go:709
        	Error:      	Received unexpected error:
        	            	timed out waiting for the condition
        	Test:       	TestFleetAutoscalerTLSWebhook
        	Messages:   	error waiting for fleet condition on fleet: simple-fleet-w698n
FAIL
```

**Comment by roberthbailey** [comment]
Flakes in e2e-feature-gates:

```
--- FAIL: TestAutoscalerBasicFunctions (356.34s)
    framework.go:284: 
        	Error Trace:	framework.go:284
        	            				fleetautoscaler_test.go:89
        	Error:      	Received unexpected error:
        	            	timed out waiting for the condition
        	Test:       	TestAutoscalerBasicFunctions
        	Messages:   	error waiting for fleet condition on fleet: simple-fleet-8lwfq
...
--- FAIL: TestFleetAutoscalerTLSWebhook (315.91s)
    framework.go:284: 
        	Error Trace:	framework.go:284
        	            				fleetautoscaler_test.go:709
        	Error:      	Received unexpected error:
        	            	timed out waiting for the condition
        	Test:       	TestFleetAutoscalerTLSWebhook
        	Messages:   	error waiting for fleet condition on fleet: simple-fleet-dl6gt
FAIL
```

**Review by cindy52 — APPROVED** [review]

**Comment by roberthbailey** [comment]
More flaky tests in e2e-feature-gates.... :/

```
--- FAIL: TestAutoscalerStressCreate (336.59s)
    framework.go:284: 
        	Error Trace:	framework.go:284
        	            				fleetautoscaler_test.go:355
        	            				fleetautoscaler_test.go:363
        	Error:      	Received unexpected error:
        	            	timed out waiting for the condition
        	Test:       	TestAutoscalerStressCreate
        	Messages:   	error waiting for fleet condition on fleet: simple-fleet-twt44
...
--- FAIL: TestAutoscalerBasicFunctions (328.17s)
    framework.go:284: 
        	Error Trace:	framework.go:284
        	            				fleetautoscaler_test.go:89
        	Error:      	Received unexpected error:
        	            	timed out waiting for the condition
        	Test:       	TestAutoscalerBasicFunctions
        	Messages:   	error waiting for fleet condition on fleet: simple-fleet-s64ns
FAIL
```

**Comment by roberthbailey** [comment]
tests are now failing from the link checker:

```
  Get https://v1-18.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/: x509: certificate is valid for *.netlify.app, netlify.app, not v1-18.docs.kubernetes.io --- site/docs/faq/index.html --> https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#containerport-v1-core
```

It looks like the 1.18 kubernetes docs are no longer being published. The 1.19 docs still appear to work.

**Comment by roberthbailey** [comment]
I've created a separate PR to fix the broken links: https://github.com/googleforgames/agones/pull/2405

**Pull request merged**
