### PR TITLE
ensure context is set before spawning goroutines using it

### LINKED ISSUE #2568: Panic in sidecar in 1.22.0
**What happened**:

We now got this panic a few times, but I can't say what triggers it:

```
2022-05-04 16:48:15	
{"ctlConf":{"Address":"localhost","IsLocal":false,"LocalFile":"","Delay":0,"Timeout":0,"Test":"","TestSdkName":"","GRPCPort":9357,"HTTPPort":9358},"featureGates":"CustomFasSyncInterval=false\u0026Example=true\u0026NodeExternalDNS=true\u0026PlayerAllocationFilter=true\u0026PlayerTracking=true\u0026SDKGracefulTermination=true\u0026StateAllocationFilter=true","message":"Starting sdk sidecar","severity":"info","source":"main","time":"2022-05-04T14:48:15.111106903Z","version":"1.22.0"}
2022-05-04 16:48:15	
{"gsKey":"ourgame/ourgame-ncnfh-chvkh","message":"Created GameServer sidecar","severity":"info","source":"*sdkserver.SDKServer","time":"2022-05-04T14:48:15.112166489Z"}
2022-05-04 16:48:15	
{"grpcEndpoint":"localhost:9357","message":"Starting SDKServer grpc service...","severity":"info","source":"main","time":"2022-05-04T14:48:15.112648367Z"}
2022-05-04 16:48:15	
{"httpEndpoint":"localhost:9358","message":"Starting SDKServer grpc-gateway...","severity":"info","source":"main","time":"2022-05-04T14:48:15.113900376Z"}
2022-05-04 16:48:15	
panic: runtime error: invalid memory address or nil pointer dereference
2022-05-04 16:48:15	
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1550dc5]
2022-05-04 16:48:15	
2022-05-04 16:48:15	
goroutine 87 [running]:
2022-05-04 16:48:15	
agones.dev/agones/pkg/sdkserver.(*SDKServer).WatchGameServer(0xc00008b040, 0x182abe0, {0x1bb69c0, 0xc000904210})
2022-05-04 16:48:15	
	/go/src/agones.dev/agones/pkg/sdkserver/sdkserver.go:536 +0x1e5
2022-05-04 16:48:15	
agones.dev/agones/pkg/sdk._SDK_WatchGameServer_Handler({0x18f51e0, 0xc00008b040}, {0x1bb3090, 0xc0002a0840})
2022-05-04 16:48:15	
	/go/src/agones.dev/agones/pkg/sdk/sdk.pb.go:904 +0xd0
2022-05-04 16:48:15	
google.golang.org/grpc.(*Server).processStreamingRPC(0xc00035cd80, {0x1bc2488, 0xc000678000}, 0xc000906300, 0xc000625860, 0x28d93a0, 0x0)
2022-05-04 16:48:15	
	/go/src/agones.dev/agones/vendor/google.golang.org/grpc/server.go:1237 +0xd63
2022-05-04 16:48:15	
google.golang.org/grpc.(*Server).handleStream(0xc00035cd80, {0x1bc2488, 0xc000678000}, 0xc000906300, 0x0)
2022-05-04 16:48:15	
	/go/src/agones.dev/agones/vendor/google.golang.org/grpc/server.go:1317 +0xa10
2022-05-04 16:48:15	
google.golang.org/grpc.(*Server).serveStreams.func1.1()
2022-05-04 16:48:15	
	/go/src/agones.dev/agones/vendor/google.golang.org/grpc/server.go:722 +0x98
2022-05-04 16:48:15	
created by google.golang.org/grpc.(*Server).serveStreams.func1
2022-05-04 16:48:15	
	/go/src/agones.dev/agones/vendor/google.golang.org/grpc/server.go:720 +0xef
```

**What you expected to happen**:
no panic

**How to reproduce it (as minimally and precisely as possible)**:
I don't know

**Anything else we need to know?**:
Agones never tried to kill the pod although the sidecar was dead. Is that expected?

**Environment**:
- Agones version: 1.22.0
- Kubernetes version (use `kubectl version`): `Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b", GitCommit:"5236faf39f1b7a7dabea8df12726f25608131aa9", GitTreeState:"clean", BuildDate:"2021-10-29T23:32:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider or hardware configuration: AWS EKS
- Install method (yaml/helm): Helm
- Troubleshooting guide log(s):
- Others:

### PR DESCRIPTION
**Pull request by Hades32**
**What type of PR is this?**
/kind bug

**What this PR does / Why we need it**:
should fix the panic in the linked issue

**Which issue(s) this PR fixes**:

Closes #2568

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by roberthbailey** [comment]
sdk conformance tests failed (that's the second time I've seen that recently, so we may have a new flake to track down).

**Comment by roberthbailey** [comment]
@Hades32 - Thanks for the PR!

Have you had a chance to test out this fix? Your comment

> hopefully fixes the panic in the linked issue

makes me wonder if this is more of a guess or something that you have been able to verify. 

I realize that the underlying issue is a race condition and probably not deterministically reproducible, but it's pretty straightforward using some of the load testing tools to spin up a few hundred / thousand test game servers and verify that none of them have a panic in the sidecar. 

Since we are in between a release candidate and a release we only merge bug fixes and documentation (see [here](https://github.com/googleforgames/agones/blob/main/docs/governance/release_process.md#release-cadence)) so if this is known to be a bug fix then we can consider merging it before the 1.23 release. Otherwise we can merge it right after that release to let it bake for a while in our continuous integration tests for the following release.

**Comment by roberthbailey** [comment]
Given that the build failure looked like a flake I've restarted it. Assuming it works, a link to grab the SDK built by CI should be posted here and you can try it out.

**Comment by Hades32** [comment]
I'm confused why the bot didn't post the one image I actually needed... I'm no rebuilding locally and hope the results will be the same. Will report back tomorrow if the panics disappeared

**Comment by roberthbailey** [comment]
It looks like we don't post links to all of the containers that are built for each PR, but there is a sdk image that was built: `gcr.io/agones-images/agones-sdk:1.23.0-3f5b6bc-linux-amd64`

There are also arm / windows ones if you need those instead, but we don't have a multi-arch manifest that gets generated by CI (see https://github.com/googleforgames/agones/issues/2280).

**Comment by Hades32** [comment]
Ah, seems I just had a typo when I tried that out. Anyway, my local build (which got tagged exactly the same, so I'm confident it's identical) didn't crash for 24h which is longer than the 1.22.0 ever lasted, so I consider this test successful.

Is there anything else you want me to do to get this merged? @roberthbailey

**Comment by Hades32** [comment]
bad news, the exact same panic is back. But TBH I don't see how that's even possible... I'll try again with the build from CI in case mine was somehow not correct, but seems like this PR is not fixing the issue

**Comment by roberthbailey** [comment]
> How long will the preview images be available?

I think they get automatically cleaned up after a few weeks, but I'm not exactly sure. If you rebase this PR it will build a new image for you though if that one gets garbage collected.

**Comment by Hades32** [comment]
OK, I think I now really understand what's going on and my latest push should fix it:
Our gameserver starts up extremely fast and therefore the `WatchGameserver` gRPC call arrives before initialization has finished. Now two bugs really: 1) the context wasn't set early enough and 2) the waitGroup was notified too early. Once CI is done I'll test this out again

**Comment by Hades32** [comment]
If I interpret those logs correctly, then there are only errors in `htmltest` which this PR shouldn't affect...

**Comment by roberthbailey** [comment]
Yeah, there are some new link check failures from old blog posts.

**Comment by Hades32** [comment]
@roberthbailey so they newest build is working fine for us. Is there anything else I should do?

**Comment by roberthbailey** [comment]
I've created https://github.com/googleforgames/agones/pull/2573 to address the html test errors.

**Review by roberthbailey — APPROVED** [review]

**Pull request merged**
