### PR TITLE
Avoid miscalculation when fleet replicas equals zero

### PR DESCRIPTION
**Pull request by danieloliveira079**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, press enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking
>
/kind bug
> /kind cleanup
> /kind documentation
> /kind feature
> /kind hotfix

**What this PR does / Why we need it**:
This is an exploratory work where I am investigating https://github.com/googleforgames/agones/issues/2509.

I am opening that as a Draft PR because I still want to create the e2e tests.

**Which issue(s) this PR fixes**:

Closes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by SaitejaTamma** [comment]
Hello @danieloliveira079 just wanted to know if you are still working on this, let us know if you need some help.

Thank you.

**Comment by danieloliveira079** [comment]
Hello @SaitejaTamma I would like to follow up on this ticket next week.  Apparently the solution works but I need a e2e test case that covers the scenario. 

There was also a comment on slack that maybe https://github.com/googleforgames/agones/pull/2420 would fix the problem. Though, I am not sure it did.

I could work on the e2e test and ask for help if I need it. WDYT?

**Comment by SaitejaTamma** [comment]
> 
sounds good.

**Comment by danieloliveira079** [comment]
After a long fight with my local environment using Docker-Desktop on Mac I finally managed to execute the e2e test I am working on using minikube.

The setup required a few manual steps like changing the KUBECONFIG file generated by minikube, loading images into minikube that were not part of the `make minikube-push` command. Apparently this command is not loading the images without the `amd64` suffix. That is affecting: controller, allocator and the SDK image.

If I manage to deliver this PR I will look into those changes properly.

**Comment by danieloliveira079** [comment]
I am closing this issue without implementing the fix. I could not setup a proper environment and a productive workflow on mac.

Running all the e2e tests locally did not work. Therefore, waiting for cloud build to run tests o every single change is counter productive.

I will try again at some point using a Linux machine.

Sorry about that.

**Pull request closed without merging**
