### PR TITLE
Add owners files for the nodejs code

### PR DESCRIPTION
**Pull request by roberthbailey**
Two reasons:

1. To document that @steven-supersolid is handling the bulk of the code reviews (especially for style).
1. This will cause the blunderbuss plugin for prow to auto assign code reviews.

/assign @steven-supersolid

### CODE REVIEW

**Comment by pooneh-m** [comment]
@roberthbailey Prow has tagged this as do-not-merge/invalid-owners-file. It seems that for some reason Prow cannot verify the owner.

**Comment by roberthbailey** [comment]
I created https://github.com/googleforgames/agones/issues/1120 and assigned it to @thisisnotapril to figure out how we want to manage collaborators in this repo (and the org).

**Comment by roberthbailey** [comment]
/hold

Waiting on #1120

**Comment by markmandel** [comment]
Is this still on hold?

Meta question - @steven-supersolid have you [met the criteria to become a full approver](https://github.com/googleforgames/agones/blob/master/docs/governance/community_membership.md#requirements)?

**Comment by roberthbailey** [comment]
/hold cancel

@steven-supersolid is now a repo collaborator so regardless of approver status this should be ok to go in now.

**Comment by roberthbailey** [comment]
boom! assignment totally works now. :)

**Comment by steven-supersolid** [comment]
Thanks for adding me! I think I meet the requirements for approver too if that is ever required but happy to just review for now

**Comment by roberthbailey** [comment]
Build error:
```
includes/sdk.mk:102: recipe for target 'build-build-sdk-image' failed
The command '/bin/sh -c go get github.com/golang/protobuf/protoc-gen-go@v1.2.0 &&     go get -u golang.org/x/tools/cmd/goimports' returned a non-zero code: 1
make[4]: *** [build-build-sdk-image] Error 1
make[4]: Leaving directory '/workspace/build'
make[3]: *** [ensure-image] Error 2
includes/build-image.mk:53: recipe for target 'ensure-image' failed
includes/sdk.mk:119: recipe for target 'ensure-build-sdk-image' failed
make[2]: *** [ensure-build-sdk-image] Error 2
Unable to find image 'agones-build-sdk-go:4861e7b00a' locally
docker: Error response from daemon: pull access denied for agones-build-sdk-go, repository does not exist or may require 'docker login'.
See 'docker run --help'.
includes/sdk.mk:84: recipe for target 'run-sdk-command' failed
make[1]: *** [run-sdk-command] Error 125
includes/sdk.mk:76: recipe for target 'run-sdk-command-go' failed
make: *** [run-sdk-command-go] Error 2
```

Retrying to see if this was transient or is repeatable.

**Pull request merged**
