### PR TITLE
Unreal SDK - Added counters to unreal sdk

### LINKED ISSUE #3648: Unreal CountsAndLists SDK implementation
Arbitrary Counters and Lists for GameServers, SDKs and Allocation #2716 has been released in Alpha, and is looking for a contributor with Unreal experience to implement the Unreal SDK. The SDK methods to implement are listed in #2716, and have been implemented in Go https://github.com/googleforgames/agones/blob/main/sdks/go/alpha.go:

- func (a *Alpha) GetCounterCount(key string) (int64, error)
- func (a *Alpha) IncrementCounter(key string, amount int64) (error)
- func (a *Alpha) DecrementCounter(key string, amount int64) (error)
- func (a *Alpha) SetCounterCount(key string, amount int64) (error)
- func (a *Alpha) GetCounterCapacity(key string) (int64, error)
- func (a *Alpha) SetCounterCapacity(key string, amount int64) (error)
- func (a *Alpha) GetListCapacity(key string) (int64, error)
- func (a *Alpha) SetListCapacity(key string, amount int64) (error)
- func (a *Alpha) ListContains(key, value string) (bool, error)
- func (a *Alpha) GetListLength(key string) (int, error)
- func (a *Alpha) GetListValues(key string) ([]string, error)
- func (a *Alpha) AppendListValue(key, value string) (error)
- func (a *Alpha) DeleteListValue(key, value string) (error)

The Unreal SDK should be implemented in the https://github.com/googleforgames/agones/tree/main/sdks/unreal/Agones directory.

The Go proto is https://github.com/googleforgames/agones/blob/main/proto/sdk/alpha/alpha.proto. Note that the proto methods do not exactly match the above listed SDK methods. This is due to the difference between the design in #2716 and the Google AIP https://google.aip.dev/general  guidance that the proto follows as closely as possible.

Due to licensing issues we don’t have a way to do unit or conformance testing for Unreal as part of the CI/CD pipeline. Please make sure that this SDK is as well tested as possible.

### PR DESCRIPTION
**Pull request by GloryOfNight**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, press enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking
> /kind bug
> /kind cleanup
> /kind documentation

/kind feature
> /kind hotfix
> /kind release

**What this PR does / Why we need it**:
Added counters to unreal sdk

**Which issue(s) this PR fixes**:
n/a

Closes #3648 (partially)

**Special notes for your reviewer**:

Validity of http requests not tested.
Build log as requested in CONTRIBUTING.md:

[buildWin64Editor.log](https://github.com/user-attachments/files/16553302/buildWin64Editor.log)

### CODE REVIEW

**Comment by GloryOfNight** [comment]
[buildWin64Editor.log](https://github.com/user-attachments/files/16558811/buildWin64Editor.log)

**Comment by igooch** [comment]
@tvandijck and @KiaArmani as the most recent contributors to the Unreal SDK, would you review this PR?

**Comment by zifter** [comment]
Any updates? It would be great to have it in 1.43 :)

**Comment by igooch** [comment]
> Any updates? It would be great to have it in 1.43 :)

1.43 release is getting cut in a few hours, so it's probably too close for this release. 

@zifter would you be able to test and validate the changes?

**Comment by zifter** [comment]
@igooch I'm working with @GloryOfNight in the same company and these changes are made by my request.

I actually can confirm, that it's tested, because we are using those changes currently in production.

**Review by KiaArmani — APPROVED** [review]
LGTM!

**Comment by GloryOfNight** [comment]
Tested, found issue with GetCounters() call related to default initialized string. Fixed it.
Everything looks good now.

**Review by zifter — APPROVED** [review]

**Comment by zifter** [comment]
Any updates?

**Review by KiaArmani — APPROVED** [review]

**Review by igooch — APPROVED** [review]
Approving based on reviews by  @KiaArmani and @zifter. Thank you for the contribution!

**Pull request merged**
