### PR TITLE
Update Debian image version for SDK base

### LINKED ISSUE #1488: Update build image Debian version
We should move this from stretch to buster.

### PR DESCRIPTION
**Pull request by aLekSer**
Update SDK base image.

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking
> /kind bug

/kind cleanup
> /kind documentation
> /kind feature
> /kind hotfix

**What this PR does / Why we need it**:
There are some critical vulnerabilities which can be detected in `Stretch` release and are fixed in `Buster`, Debian v10 release. 
**Which issue(s) this PR fixes**:

For #1154
Closes #1488

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by aLekSer** [comment]
For example container analysis of CPP image.

After the fix:
```
Total Fixes Critical High Medium
50    0     0        0      3
```
Before: 
```
Total Fixes Critical High Medium
81    1     0        7      8
```

**Comment by aLekSer** [comment]
There is a need to push fresh `agones-build-sdk-base` for CI to complete:
```
Step #7 - "pull-build-sdk-base-image": Error response from daemon: manifest for gcr.io/agones-images/agones-build-sdk-base:dc5387dbd7 not found
```

**Comment by markmandel** [comment]
I feel like we ran into this before, `ensure-build-sdk-image-base` should pick up the building process on the new image (the `pull-remote-build-image` will exit without a non-0 error, so that's a red herring), but I think the build possibly takes way too long, since the whole build times out after 1 hr 43 sec.

(See top of page: Timed out: 951c30b5)

We might want to allow builds to run for longer than an hour, but I'll manually build this image for now.

**Comment by markmandel** [comment]
Hmnn, I can't get this to build. Here's the tail end of the build output from `make build-build-sdk-image-base`:

```
[C]       Compiling third_party/boringssl/crypto/base64/base64.c
[C]       Compiling third_party/boringssl/crypto/bio/bio.c
[C]       Compiling third_party/boringssl/crypto/bio/bio_mem.c
[C]       Compiling third_party/boringssl/crypto/bio/connect.c
[C]       Compiling third_party/boringssl/crypto/bio/fd.c
[C]       Compiling third_party/boringssl/crypto/bio/file.c
third_party/boringssl/crypto/bio/connect.c: In function 'conn_callback_ctrl':
third_party/boringssl/crypto/bio/connect.c:491:29: error: cast between incompatible function types from 'bio_info_cb' {aka 'long int (*)(struct bio_st *, int,  const char *, int,  long int,  long int)'} to 'int (*)(const struct bio_st *, int,  int)' [-Werror=cast-function-type]
       data->info_callback = (int (*)(const struct bio_st *, int, int))fp;
                             ^
[C]       Compiling third_party/boringssl/crypto/bio/hexdump.c
[C]       Compiling third_party/boringssl/crypto/bio/pair.c
[C]       Compiling third_party/boringssl/crypto/bio/printf.c
[C]       Compiling third_party/boringssl/crypto/bio/socket.c
[C]       Compiling third_party/boringssl/crypto/bio/socket_helper.c
[C]       Compiling third_party/boringssl/crypto/bn_extra/bn_asn1.c
[C]       Compiling third_party/boringssl/crypto/bn_extra/convert.c
[C]       Compiling third_party/boringssl/crypto/buf/buf.c
[C]       Compiling third_party/boringssl/crypto/bytestring/asn1_compat.c
cc1: all warnings being treated as errors
make: *** [Makefile:2899: /var/local/git/grpc/objs/opt/third_party/boringssl/crypto/bio/connect.o] Error 1
make: *** Waiting for unfinished jobs....
[C]       Compiling third_party/boringssl/crypto/bytestring/ber.c
The command '/bin/sh -c git clone -b $GRPC_RELEASE_TAG --depth=5 https://github.com/grpc/grpc /var/local/git/grpc &&            cd /var/local/git/grpc &&     git submodule update --init &&     echo "--- installing protobuf ---" &&     cd third_party/protobuf &&     ./autogen.sh && ./configure --enable-shared &&     make -j$(nproc) && make install && make clean && ldconfig &&     echo "--- installing grpc ---" &&     cd /var/local/git/grpc &&     make -j$(nproc) && make install && make clean && ldconfig' returned a non-zero code: 2
make: *** [includes/sdk.mk:102: build-build-sdk-image-base] Error 2
```

**Comment by aLekSer** [comment]
Well I will try the proposed fix.

**Comment by aLekSer** [comment]
1 hour is not enough to build all these images.

**Comment by markmandel** [comment]
> 1 hour is not enough to build all these images.

Should we try changing the timeout in cloudbuild.yaml to 2h ?

**Comment by aLekSer** [comment]
This Dockerfile builds pretty fast on a small Compute Engine with Docker 18.09.3:
```
cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
```

**Comment by markmandel** [comment]
I would recommend breaking this PR apart into separate PRs that can be tested individually, so that we can work out the root cause, and also so we can distribute the workload.

**Comment by aLekSer** [comment]
https://github.com/protocolbuffers/protobuf/issues/3930
The reason could be in that we use the whole RAM available. I will remove `make -j$(nproc)` or could change to some reasonable number less than all cores of `n1-highcpu-8`.

**Comment by aLekSer** [comment]
Congrats, now build of image is working. But SDK conformance test is failing.

**Comment by aLekSer** [comment]
Removing `example/` changes to separate two PRs

**Comment by markmandel** [comment]
Curious, would `-j4` be faster? Or a value that will pass.

Nice find on the issue with nproc, I wonder what causes that.

**Pull request merged**
