### PR TITLE
Updates GRPC to v1.20.1

### PR DESCRIPTION
**Pull request by cyriltovena**
This version is the one used by the latest release of OpenCensus which is why I made this PR.

I've also update protobuf to the same version as OpenCensus and grpc-gateway.

### CODE REVIEW

**Comment by markmandel** [comment]
Not 100% sure why this is failing. If it's the cpp build cache, may need to adjust the `_CPP_SDK_BUILD_CACHE_KEY` in cloudbuild.yaml to hash a file or just add a `-v2` to it or something.

**Comment by cyriltovena** [comment]
failing too locally but it wasn't earlier. I'll investigate.

**Comment by aLekSer** [comment]
@markmandel This solves `sdk.swagger.json` definition file. I could send an updated PR after this one merged. 
However I could not test the resulting schema, because for now there is an issue with `x-stream-definitions` in both swagger generators I have tried (details are in that issue).

**Comment by aLekSer** [comment]
Thanks for an update. So this PR would also break new HTTP test which uses swagger generator.
```
$ make  run-sdk-conformance-test SDK_FOLDER=restapi HTTP_PORT=9050                              
{"httpEndpoint":":9050","message":"Starting SDKServer grpc-gateway...","severity":"info","source":"main","time":"2019-10-25T13:06:06.3917168Z"}                                                          
# agones.dev/agones/test/sdk/restapi/swagger
swagger/api_sdk.go:742:63: undefined: XStreamDefinitionssdkGameServer
swagger/api_sdk.go:748:23: undefined: XStreamDefinitionssdkGameServer
swagger/api_sdk.go:806:10: undefined: XStreamDefinitionssdkGameServer
make[2]: *** [run-sdk-command] Error 2
{"message":"shutting down sdk server","severity":"info","source":"main","time":"2019-10-25T13:06:36.358519Z"}                                                                                            
{"message":"Compare","severity":"info","time":"2019-10-25T13:06:36.3586729Z"}
{"message":"Testing Failed [ready allocate setlabel setannotation gameserver health shutdown watch reserve] []","severity":"info","time":"2019-10-25T13:06:36.358818Z"}                                  
make[1]: *** [run-sdk-conformance-no-build] Error 1
make: *** [run-sdk-conformance-test] Error 2
```

**Comment by cyriltovena** [comment]
I'm struggling with the cpp SDK. I'm backtracking my changes one by one and rebuilding to see what's wrong. (And building when I have time, cpp build is horribly slow.)

**Comment by markmandel** [comment]
@cyriltovena did you want a hand with this? I can take a stab, if you would like?

**Comment by markmandel** [comment]
So I rebased to master on my [local branch](https://github.com/markmandel/agones/tree/pull/1144), and ran the compilation script. I just wanted to capture the output, so we can start to take it apart:

Here it is:
https://gist.github.com/markmandel/a6a000491740fff08fb05d9da00910e8

**Comment by cyriltovena** [comment]
yes this is the problem. The cmake has a version that he uses to get source code https://github.com/googleforgames/agones/blob/master/sdks/cpp/CMakeLists.txt#L98 and build against it.

**Comment by markmandel** [comment]
Kicking off a retry, see if that helps.

**Comment by markmandel** [comment]
... I think this is timing out!

**Comment by markmandel** [comment]
Since it seems like this is not going to build on Cloud Build - should I build it on my workstation (I may have it already), and push it up to gcr.io?

**Comment by markmandel** [comment]
@cyriltovena if you want to resolve the conflicts, I'm happy to build the image on my workstation and push this up.

**Comment by cyriltovena** [comment]
Will do

**Comment by cyriltovena** [comment]
While 1.20.1 is the last version used by OpenCensus, OpenTelemetry uses 1.24, I'm thinking while we are at it and since GRPC is backward compatible should we move to 1.24 instead ? 🤷‍♂

**Comment by cyriltovena** [comment]
Mark can you build it ?

**Comment by cyriltovena** [comment]
@markmandel Can you let me know if you can build locally ? You have to start with a clean setup.

**Comment by markmandel** [comment]
Sure! I'll try and get on it today. Not sure if it's worth the experiment, but you could also change the name of the CPP build cache, which would force a clean build on Cloud Build.

**Comment by markmandel** [comment]
...building on my workstation!

**Comment by markmandel** [comment]
So I just realised something - I can build the image, but the image isn't the issue (we don't even store the cpp sdk build image) - the issue is to have the cpp build cache - is it not?

Can you edit https://github.com/cyriltovena/agones/blob/grpc/cloudbuild.yaml#L280 to make it something like "cpp-sdk-build-1" or even edit it to include a hash of https://github.com/cyriltovena/agones/blob/grpc/sdks/cpp/CMakeLists.txt (might be a good option).

See if things build from there?

**Comment by aLekSer** [comment]
As I mentioned above there is an issue with swagger codegen:
`make  run-sdk-conformance-test SDK_FOLDER=restapi HTTP_PORT=9050` is failing because of
`swagger/api_sdk.go:742:63: undefined: XStreamDefinitionssdkGameServer`
I am working on adding new version of the test which would override this issue.

**Comment by cyriltovena** [comment]
>  the issue is to have the cpp build cache - is it not?

Yes works for me locally.

**Comment by cyriltovena** [comment]
alright I sinked enough time into this. I'm done !

**Comment by cyriltovena** [comment]
also quite mad about C++.

**Comment by markmandel** [comment]
Okay, I'm going to take this over. We will make this work!

**Comment by markmandel** [comment]
So I'm digging into this - it looks like it did actually compile correctly, but it failed on @aLekSer 's afformentioned issue:

```
# agones.dev/agones/test/sdk/restapi/swagger
swagger/api_sdk.go:742:63: undefined: XStreamDefinitionssdkGameServer
swagger/api_sdk.go:748:23: undefined: XStreamDefinitionssdkGameServer
swagger/api_sdk.go:806:10: undefined: XStreamDefinitionssdkGameServer
includes/sdk.mk:84: recipe for target 'run-sdk-command' failed
make[3]: *** [run-sdk-command] Error 2
{"grpcEndpoint":":9357","message":"Starting SDKServer grpc service...","severity":"info","source":"main","time":"2019-12-06T16:48:18.569904778Z"}
{"httpEndpoint":":9050","message":"Starting SDKServer grpc-gateway...","severity":"info","source":"main","time":"2019-12-06T16:48:18.570635165Z"}
{"message":"shutting down sdk server","severity":"info","source":"main","time":"2019-12-06T16:48:48.569699733Z"}
{"message":"Compare","severity":"info","time":"2019-12-06T16:48:48.569899218Z"}
{"message":"Testing Failed [ready allocate setlabel setannotation gameserver health shutdown watch reserve] []","severity":"info","time":"2019-12-06T16:48:48.569943486Z"}
```

@aLekSer when do you think this will be updated?

**Pull request closed without merging**
