### PR TITLE
[UrealSDK] Creating requests should work in all versions of UE4

### LINKED ISSUE #1940: Unable to COMPILE after added agones plugin in UE4.26
Unable to compile ue project after adding agones plugin .Error message is shown below----

Error	C2440	'initializing': cannot convert from 'TSharedRef<IHttpRequest,ESPMode::ThreadSafe>' to 'TSharedRef<IHttpRequest,ESPMode::NotThreadSafe>'

	****/Plugins\Agones\Source\Agones\Private\AgonesComponent.cpp	55	

**Environment**:
- Agones version:  version 1.12.0

### PR DESCRIPTION
**Pull request by domgreen**
**What type of PR is this?**
/kind hotfix

**What this PR does / Why we need it**:

We are replacing the usage if `TSharedRef<IHttpRequest>`  with `FHttpRequestRef` to allow it to work across versions.

It seems that this basically a typedef under the hood to make this work nicely for the current versions.

**Which issue(s) this PR fixes**:
Closes #1940

**Special notes for your reviewer**:
- Have tested with `4.25.1`
- Need to have someone test with `4.26` prior to merging.

### CODE REVIEW

**Comment by domgreen** [comment]
^ had a look at build log seems like the tests failed ... nothing jumped out at me apart from website failing to build:
```
includes/website.mk:72: recipe for target 'site-test' failed
make[1]: Leaving directory '/workspace/build'
includes/website.mk:65: recipe for target 'hugo-test' failed
```

**Review by aLekSer — APPROVED** [review]
Change seems reasonable to me.

**Comment by domgreen** [comment]
Thanks @aLekSer will wait for confirmation of it working wtih `4.26` before asking for a merge

**Comment by comerford** [comment]
good news and bad news - the good news is that the version of the plugin from Dom compiled just fine, the bad news is that so did the previous version. This is either due to the fact that we use a customised version of the engine or it is because we only have limited usage of the plugin so far (the end game state change is not yet wired up for example). Seems like I am a poor tester for this one for now.

**Comment by domgreen** [comment]
Thanks for trying @comerford :+1: 

As @gamedevix is the original reporter might be best to see if they can see it being fixed with this fork.

**Comment by domgreen** [comment]
As mentioned on #1940 by @Gamedevix , this is due to our return type still being:

```
TSharedRef<IHttpRequest> UAgonesComponent::BuildAgonesRequest
```

This explains why it compiles for me and not in `4.26` will muse over it ... ideas welcome :+1:

**Comment by comerford** [comment]
@domgreen Does specifying the ESPMode explicitly rather than using auto break older versions?

`TSharedRef<IHttpRequest, ESPMode::ThreadSafe> Request = Http->CreateRequest();`

**Comment by domgreen** [comment]
So the issue is that in `4.25.1` its:
```
TSharedRef<IHttpRequest, ESPMode::Fast> Request = Http->CreateRequest();
```
Meaning that the signature of `CreateRequest` seems to have changed ... some more digging required :smile:

**Review by markmandel — CHANGES_REQUESTED** [review]
Just kicking this to "request changes" so it doesn't get accidentally merged until we can work out a good fix :+1:

**Comment by domgreen** [comment]
@Gamedevix @comerford @mbc-audiovisuales would you mind checking this wiht `4.26`

**Comment by highlyunavailable** [comment]
This is a required change for me to use Agones with 4.26 - it compiles fine on 4.26.1 and I had to manually patch the Agones SDK with these changes to get it to compile. What is blocking a merge of this? I can help test it on 4.25 and 4.26 if needed.

**Comment by markmandel** [comment]
@domgreen to confirm, but I'm pretty sure that testing on a variety of versions is the blocking issue.

If we can confirm the fix works across versions, I'm good to merge :+1:

**Comment by highlyunavailable** [comment]
If we just need a variety of versions I can provide that, given the matrix you need tested. I have 4.25.3 and 4.26.1 are immediately available, but I can try to get more if needed.

Apologies if you already know this as well, but the other method (rather than using `auto` for the variable type) is to use `#IF` by doing the following:

`#include "Runtime/Launch/Resources/Version.h"`

And then wrap the signature or variable assignments in the code:

```c++
#if ENGINE_MAJOR_VERSION == 4 && ENGINE_MINOR_VERSION >= 26 && ENGINE_PATCH_VERSION >= 0
    FHttpRequestRef BuildAgonesRequest(FString Path = "", const FHttpVerb Verb = FHttpVerb::Post, const FString Content = "{}");
#else
    TSharedRef<IHttpRequest> BuildAgonesRequest(FString Path = "", const FHttpVerb Verb = FHttpVerb::Post, const FString Content = "{}");
#endif
```

It's a little messier looking but it removes the need for `auto` if that's also a blocker and this is the supported Unreal Way to do changes across versions like this and is used in multiple portions of the engine.

**Comment by domgreen** [comment]
@markmandel yeah just waiting on confirmation that it works on 4.26.1 I have it working with 4.25.4 and UDN says this should work with all versions just haven't had confirmation till now👍 

@highlyunavailable thank you so much for testing and recommendations

**Comment by domgreen** [comment]
@markmandel i think with this confirmation we are good to merge :dancers:

**Comment by highlyunavailable** [comment]
> yeah just waiting on confirmation that it works on 4.26.1 I have it working with 4.25.4 and UDN says this should work with all versions just haven't had confirmation till now👍

Yep it _absolutely_ does. If you ever need Unreal testing feel free to @ me, I'm an Unreal jockey at the moment and happy to wrangle the CPP.

**Comment by markmandel** [comment]
Sweet. I'll hit that approve button!

**Review by markmandel — APPROVED** [review]

**Pull request merged**
