### PR TITLE
Remove Unreachable AltaVR from the main page

### PR DESCRIPTION
**Pull request by aLekSer**
Link check will soon crash on CI because website is not reachable.
http://altavr.io/
Hello @TimoSchmechel What is the state of the project? Would the site be up in the near future? Or should we proceed with this PR?

### CODE REVIEW

**Comment by TimoSchmechel** [comment]
Sorry about this, our website was down temporarily. We will fix it up today

**Comment by markmandel** [comment]
If it becomes an issue, we could always do a `data-proofer-ignore` attribute on the link while we wait for the website to come back up - rather than remove it entirely.

**Comment by TimoSchmechel** [comment]
We took a look and for some reason our provider flagged the website as containing malware. So just resolving that now. If this is blocking the automated builds, the ignore attribute sounds like a easy quick fix until we resolve this on our end.

**Comment by TimoSchmechel** [comment]
well turns out our website was compromised and someone placed a bunch of malware on it. Its fixed now though. So can probably close this PR

**Comment by markmandel** [comment]
Nice to see you back up! Closing!

**Comment by aLekSer** [comment]
> we could always do a data-proofer-ignore attribute on the link while we wait for the website to come back up - rather than remove it entirely.
@TimoSchmechel , nice to hear that, I also was thinking to open an issue instead of PR. Just I was not able to check what was the reason of the website being down, but noticed that it was down for a while.

**Pull request closed without merging**
