### PR TITLE
Update simple-game-server to 0.11 everywhere

### PR DESCRIPTION
**Pull request by markmandel**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, press enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking
> /kind bug

/kind cleanup

> /kind documentation
> /kind feature
> /kind hotfix

**What this PR does / Why we need it**:

This increments the sinmple-game-server because of the bug fixes in the Go SDK.

Also updates the e2e test suit, so that we can test the fixes in the Go SDK.

**Which issue(s) this PR fixes**:

Unblocks #2503

**Special notes for your reviewer**:

Image has been uploaded.

### CODE REVIEW

**Comment by markmandel** [comment]
oooh this is a weird one - something stuck / change with pushing docker manifests?

step: `push-images`

```
7e65a6aff1da: Pushed
367c178ee1ad: Pushed
8ad1dbbdee2e: Pushed
1.22.0-dfaf01c-linux_amd64: digest: sha256:fc84f8153b8cc206077cdef22be5a5db9282b1373f33152d4630e68596185030 size: 1160
1.22.0-dfaf01c: digest: sha256:b48b332989b30c2a44208633c1e95a8b84aaca3662794ce2f6777b684503238a size: 1160
# Ensure that the sidecar manifest is removed before creating a new one.
DOCKER_CLI_EXPERIMENTAL=enabled docker manifest rm gcr.io/agones-images/agones-sdk:1.22.0-dfaf01c

Usage:	docker manifest COMMAND

The **docker manifest** command has subcommands for managing image manifests and
manifest lists. A manifest list allows you to use one name to refer to the same image
built for multiple architectures.

To see help for a subcommand, use:

    docker manifest CMD --help

For full details on using docker manifest lists, see the registry v2 specification.

Commands:
  annotate    Add additional information to a local image manifest
  create      Create a local manifest list for annotating and pushing to a registry
  inspect     Display an image manifest, or manifest list
  push        Push a manifest list to a repository

Run 'docker manifest COMMAND --help' for more information on a command.
make: [Makefile:466: push-agones-sdk-image] Error 1 (ignored)
```

**Comment by markmandel** [comment]
Ah, may be a red-herring, looks like the message pops up always. Just tested locally, and everything still works.

```
received unexpected HTTP status: 503 Service Unavailable
make: *** [Makefile:456: push-allocator-image] Error 1
```

I think there was a flaky error with the container registry. Going to retry.

**Comment by roberthbailey** [comment]
> Update simple-game-server to 0.11 everywhere

There are some other places that need updating too, e.g. `examples/simple-game-server/*.yaml` `test/load/allocation/grpc/fleet.yaml`, `examples/fleet.yaml`, etc if it's going to be "everywhere". If you want to rename the PR to updating it for the e2e tests, then happy to merge as-is.

**Comment by markmandel** [comment]
@roberthbailey that is a good point. Lemme update this PR with those changes!

**Comment by markmandel** [comment]
Updated!

**Review by roberthbailey — APPROVED** [review]
That's much more complete.

**Pull request merged**
