### PR TITLE
Upgrade Docker to 24.0.6 

### PR DESCRIPTION
**Pull request by Kalaiselvi84**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, press enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking
> /kind bug

/kind cleanup
> /kind documentation
> /kind feature
> /kind hotfix
> /kind release

**What this PR does / Why we need it**:

**Which issue(s) this PR fixes**:

Work on #3530 

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by Kalaiselvi84** [comment]
`gcr.io/cloud-builders/docker` is present in other files outside of the `/example` dir. Should we also update these files?

https://github.com/googleforgames/agones/blob/a9348781de27f642cba28cbbf72903e44173900a/ci/e2e-test-cloudbuild.yaml#L22

https://github.com/googleforgames/agones/blob/a9348781de27f642cba28cbbf72903e44173900a/build/build-image/cache/cloudbuild.yaml#L30

https://github.com/googleforgames/agones/blob/a9348781de27f642cba28cbbf72903e44173900a/build/release/pre_cloudbuild.yaml#L44

https://github.com/googleforgames/agones/blob/a9348781de27f642cba28cbbf72903e44173900a/site/cloudbuild.yaml#L27

**Comment by markmandel** [comment]
That's a good question - yeah, let's be consistent across the board.

The only one I would exclude is `[agones/build/build-image/cache/cloudbuild.yaml](https://github.com/googleforgames/agones/blob/a9348781de27f642cba28cbbf72903e44173900a/build/build-image/cache/cloudbuild.yaml#L30)`  just because we're essentially vendoring a third party cloud build script - so it's easier to keep it as close to the original as possible.

Did you want to make that change in this PR?

**Comment by Kalaiselvi84** [comment]
I've updated the docker version outside of `/examples` and excluded the [agones/build/build-image/cache/cloudbuild.yaml](https://github.com/googleforgames/agones/blob/a9348781de27f642cba28cbbf72903e44173900a/build/build-image/cache/cloudbuild.yaml#L30) file

**Comment by Kalaiselvi84** [comment]
@gongmax We have updated all the necessary files with version 24.0.6 in this PR.

**Review by gongmax — APPROVED** [review]

**Pull request merged**
