### PR TITLE
Added logic to modify sdk metadataPrefix

### PR DESCRIPTION
**Pull request by eddie-knight**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking
> /kind bug
> /kind cleanup
> /kind documentation
/kind feature
> /kind hotfix

**What this PR does / Why we need it**:
This proposes a new exported function to allow sdk users to modify the metadata prefix used in labels and annotations.

**Which issue(s) this PR fixes**:

Closes #

**Special notes for your reviewer**:
I haven't written any tests for this. If this is considered for merging, let me know and I can swing back to add a unit test.

### CODE REVIEW

**Comment by roberthbailey** [comment]
Hi @eddie-knight! Thanks for sending in a proposed change. 

Before we talk about whether or not to add tests, can you provide a bit of background about _why_ you want to make this change? What is your use case for setting a different prefix on labels and annotations from the game server SDK? (as an aside, it might be easiest to do this in an issue rather than on a PR)

https://agones.dev/site/docs/guides/client-sdks/#setlabelkey-value says:

> To maintain isolation, the key value is automatically prefixed with “agones.dev/sdk-”.

**Comment by eddie-knight** [comment]
>  it might be easiest to do this in an issue rather than on a PR

Sorry about that- I threw this PR out as part of [this conversation](https://agones.slack.com/archives/C9DGM5DS8/p1617719986148300?thread_ts=1617716269.148200&cid=C9DGM5DS8). I hope that link works... it's a conversation with @domgreen in #users :+1:

**Comment by roberthbailey** [comment]
I was reading up on the slack discussion this morning, but for posterity I think it makes sense to capture the discussion in an issue (since slack history doesn't last forever and not everyone may have access to it).

**Comment by domgreen** [comment]
Related to #2053

**Comment by markmandel** [comment]
Shall we close this until the discussion in #2053 is completed?

The code isn't really doing anything at the moment anyway? 🤷🏻

**Comment by roberthbailey** [comment]
Based on the latest comments in #2053 it sounds like we should close this. Please re-open if you disagree.

**Pull request closed without merging**
