### PR TITLE
Static/TCPUDP support for the container ports

### LINKED ISSUE #2314: TCPUDP not supported
**What happened**:

Pod "gameserver" is invalid: spec.containers[0].ports[0].protocol: Unsupported value: "TCPUDP": supported values: "SCTP", "TCP", "UDP"

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

```
apiVersion: agones.dev/v1
kind: GameServer
spec:
  ports:
     portPolicy: Static
     containerPort: 7000
     hostPort: 7000
     protocol: TCPUDP
```

**Anything else we need to know?**:

**Environment**:
- Agones version: v1.18.0
- Kubernetes version (use `kubectl version`): v1.22.1
- Install method (yaml/helm): helm

### PR DESCRIPTION
**Pull request by SaitejaTamma**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, press enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking
> /kind bug
> /kind cleanup
> /kind documentation

/kind feature

> /kind hotfix

**What this PR does / Why we need it**:

**Which issue(s) this PR fixes**:
Closes #2314

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by markmandel** [comment]
In the previous PR we had discussed having an e2e test to complete the level of testing. I'd like to see that in this PR.

**Comment by SaitejaTamma** [comment]
> In the previous PR we had discussed having an e2e test to complete the level of testing. I'd like to see that in this PR.

Sure, working on that part will update once done

**Comment by markmandel** [comment]
I can replicate this locally, when running `kubectl describe gs` on the Unhealthy GameServer I see int the events:

```
Events:
  Type     Reason     Age   From                    Message
  ----     ------     ----  ----                    -------
  Warning  Error      28s   gameserver-controller   Pod "game-servervfprv" is invalid: spec.containers[1].ports[0].protocol: Unsupported value: "TCPUDP": supported values: "SCTP", "TCP", "UDP"
  Warning  Unhealthy  28s   missing-pod-controller  Pod is missing
```

**Comment by markmandel** [comment]
So confirmed that the e2e test is not working:

```
--- FAIL: TestGameServerTcpUdpProtocol (0.01s)
    --- FAIL: TestGameServerTcpUdpProtocol/Validating_tcpudp_protocol_for_Static (304.87s)
        gameserver_test.go:815: 
            	Error Trace:	gameserver_test.go:815
            	Error:      	Could not get a GameServer ready
            	Test:       	TestGameServerTcpUdpProtocol/Validating_tcpudp_protocol_for_Static
            	Messages:   	waiting for {game-server [{gameserver Static <nil> 7654 7654 TCPUDP}] {false 0 0 0}  { 0 0} {{      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] []  []} {[] [] [{game-server gcr.io/agones-images/simple-game-server:0.13 [] []  [] [] [{TCP TRUE nil}] {map[cpu:{{30 -3} {<nil>} 30m DecimalSI} memory:{{33554432 0} {<nil>}  BinarySI}] map[cpu:{{30 -3} {<nil>} 30m DecimalSI} memory:{{33554432 0} {<nil>}  BinarySI}]} [] [] nil nil nil nil   IfNotPresent nil false false false}] []  <nil> <nil>  map[]   <nil>  false false false <nil> nil []   nil  [] []  <nil> nil [] <nil> <nil> <nil> map[] [] <nil>}} <nil>} GameServer instance readiness timed out (): waiting for GameServer to be Ready 1656016918/game-server2w4xf: timed out waiting for the condition
    --- FAIL: TestGameServerTcpUdpProtocol/Validating_tcpudp_protocol_for_Dynamic (305.10s)
        gameserver_test.go:815: 
            	Error Trace:	gameserver_test.go:815
            	Error:      	Could not get a GameServer ready
            	Test:       	TestGameServerTcpUdpProtocol/Validating_tcpudp_protocol_for_Dynamic
            	Messages:   	waiting for {game-server [{gameserver Static <nil> 7654 7654 TCPUDP}] {false 0 0 0}  { 0 0} {{      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] []  []} {[] [] [{game-server gcr.io/agones-images/simple-game-server:0.13 [] []  [] [] [{TCP TRUE nil}] {map[cpu:{{30 -3} {<nil>} 30m DecimalSI} memory:{{33554432 0} {<nil>}  BinarySI}] map[cpu:{{30 -3} {<nil>} 30m DecimalSI} memory:{{33554432 0} {<nil>}  BinarySI}]} [] [] nil nil nil nil   IfNotPresent nil false false false}] []  <nil> <nil>  map[]   <nil>  false false false <nil> nil []   nil  [] []  <nil> nil [] <nil> <nil> <nil> map[] [] <nil>}} <nil>} GameServer instance readiness timed out (): waiting for GameServer to be Ready 1656016918/game-servern6fk7: timed out waiting for the condition
FAIL
```
e2e-stable

**Comment by markmandel** [comment]
I'm going to close this, and we can reassign the work at a later date.

**Pull request closed without merging**
